# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mailman-db-app
  namespace: mailman
type: kubernetes.io/basic-auth
stringData:
  username: mailman
  password: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: mailman-secret
  namespace: mailman
type: Opaque
stringData:
  HYPERKITTY_API_KEY: REPLACE_ME
  SECRET_KEY: REPLACE_ME
  MAILMAN_REST_USER: restadmin
  MAILMAN_REST_PASSWORD: REPLACE_ME
  MAILMAN_ADMIN_USER: admin
  MAILMAN_ADMIN_EMAIL: admin@jit.services # CHANGE ME
  SMTP_HOST_USER: lists@jit.services # CHANGE ME
  SMTP_HOST_PASSWORD: REPLACE_ME
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
  name: mailman-backup-s3
  namespace: mailman
type: Opaque
stringData:
  ACCESS_KEY_ID: REPLACE_ME
  SECRET_ACCESS_KEY: REPLACE_ME
