# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: mailman-db-app
    namespace: mailman
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:yIZZZflq4A==,iv:8Dadj8dqA21glYoX27FRjwU4aI78Gxeh4lyhGc/XbmQ=,tag:ZGT3AU9EzS/AeIUfqycHPA==,type:str]
    password: ENC[AES256_GCM,data:Nqy/utGdNJKIjA==,iv:rLkhHmcMcbLToAH2c6vlc/oi7Sn4osb+LLVrhyRlugw=,tag:ITjh6F4/xN6sRUB7XNrpQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWStONTE4QlM3Q0dqZHZG
            bHNUb2pXVXhEUGt1V2xsaVYyN3hDL0FTK0hFCnBjcE5MeGpmMElNTjNMRHVsbDJ5
            ZHpMZ01YWjh5Z28vV1I1ekg0Z1puNkUKLS0tIG1iemZLeFBPVCswRFFadTNEQ0JG
            NUZKSnBWcFJhNUJRbXdRd0NTQS9wbGsKT4tCrwamHI0d7cV3NTXNm6tQMSYjauh+
            TXWyIBlpxuEYANBZzO7R55LHwFa0YkupbGlgFSd0eNi48XWlRi4+Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:bneGdMWjbjzvowGr8Dc+ungTjP8X6aYXLni5I3kJ+alJz9PPEVhz/MtWgLjR18Oeksa3JYjjPEGKz66suqi9DL4ZI9VTgVARQgJva9J94h+WgwEek7KUXCegY9Xqh1sQcoMmQ5r31Xyu42Dbt/kI4/l2sZaQTBQvIK8vGBMRd38=,iv:SFxfE42D0dAfwe7B4EsVwDr5vG/B6yTHfaDDabVnwhU=,tag:FS0r2Wnk24xQ2BJxTXY1Mw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mailman-secret
    namespace: mailman
type: Opaque
stringData:
    HYPERKITTY_API_KEY: ENC[AES256_GCM,data:yW+VY2zPSy/kXw==,iv:VcAlNdWTzeFtA/pj6S70NtzeyWmWJid3t6jIoTiUR8I=,tag:QR7h8mpQq3NRwYhlCjS7Aw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:xU5wK2wGKMNnnw==,iv:4xOQKRMRY4baFweogMVFyLHUBq85LnubgnZ9IZTCpSw=,tag:W2K+vxOlyabaf6XZlPRBIQ==,type:str]
    MAILMAN_REST_USER: ENC[AES256_GCM,data:y/miBT3T/Qa7,iv:jnfEZP6n7ZpgSXhXMpuvcM21p8joStAmJ6DPQiKDar8=,tag:SAoG3GqrVQ77uFmwcamc9A==,type:str]
    MAILMAN_REST_PASSWORD: ENC[AES256_GCM,data:3ll3hd55lzHlMg==,iv:+N/4bvM3RuH0u5waGEEugAVevsAIoqapB4h7RSi+nuQ=,tag:avnb/evBKeybzYdv6B1azw==,type:str]
    MAILMAN_ADMIN_USER: ENC[AES256_GCM,data:sWorDc8=,iv:EELZ/kwD8yvpC06iunHOVM+k94Si+jp1sy/vJUM1c7U=,tag:RRroVvjMRh0u6fpKqYO5EQ==,type:str]
    MAILMAN_ADMIN_EMAIL: ENC[AES256_GCM,data:roQJuNSFk4XHoFivVhkwgBZj,iv:ePn88XUYLnMcAshdpCzrZ6fYuQX+JnWNDgTEqPvEQ6A=,tag:+RBHuFJpUhip3WJ0YTvZww==,type:str] #ENC[AES256_GCM,data:yUSYIvpHM6jBuw==,iv:Q5q5ovVwi4XxCZDxSvnnQbkYtYJapPAADsxGBC5TdY4=,tag:mzHHsUephdH8bXpIvyPMGA==,type:comment]
    SMTP_HOST_USER: ENC[AES256_GCM,data:EWZHjCh9wWu3wMv0nMaBFam0,iv:E/LVlwh1+PGDtP2oVnx6AcFUSdOtjk9ji4MyK84k7tc=,tag:KP4nbr8hMM4q46xMCteLhg==,type:str] #ENC[AES256_GCM,data:klvnJsJVcYxr3A==,iv:TJGfRcfqVLrNfNSjiB7P2OFEw1lsx6ONbsKuJl4n6B8=,tag:kiO8U6FeGTHAQa06GBWdvg==,type:comment]
    SMTP_HOST_PASSWORD: ENC[AES256_GCM,data:K1rXEsOVsxrrkw==,iv:j4j/4rJfCkh3QjvmN3rBGaOeqfkw3G5xQcdzMzxp6HE=,tag:iAMERaKFOS6W3inhoCykBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWStONTE4QlM3Q0dqZHZG
            bHNUb2pXVXhEUGt1V2xsaVYyN3hDL0FTK0hFCnBjcE5MeGpmMElNTjNMRHVsbDJ5
            ZHpMZ01YWjh5Z28vV1I1ekg0Z1puNkUKLS0tIG1iemZLeFBPVCswRFFadTNEQ0JG
            NUZKSnBWcFJhNUJRbXdRd0NTQS9wbGsKT4tCrwamHI0d7cV3NTXNm6tQMSYjauh+
            TXWyIBlpxuEYANBZzO7R55LHwFa0YkupbGlgFSd0eNi48XWlRi4+Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:bneGdMWjbjzvowGr8Dc+ungTjP8X6aYXLni5I3kJ+alJz9PPEVhz/MtWgLjR18Oeksa3JYjjPEGKz66suqi9DL4ZI9VTgVARQgJva9J94h+WgwEek7KUXCegY9Xqh1sQcoMmQ5r31Xyu42Dbt/kI4/l2sZaQTBQvIK8vGBMRd38=,iv:SFxfE42D0dAfwe7B4EsVwDr5vG/B6yTHfaDDabVnwhU=,tag:FS0r2Wnk24xQ2BJxTXY1Mw==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: mailman-backup-s3
    namespace: mailman
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:pfpvccOikcF+vg==,iv:niOYI/ELWkivclIu3SAcRf/gHaOlEC7I6FqDyiYJ8gE=,tag:Vt0TnhdR559KeejkeTBbCg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pgmOsxc8Qz129w==,iv:pLS154XS78VtPthC3dvOf83b8pv7iAyK9FftYX/uRzs=,tag:TvwA3IHgOydHHWwUcDp8Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWStONTE4QlM3Q0dqZHZG
            bHNUb2pXVXhEUGt1V2xsaVYyN3hDL0FTK0hFCnBjcE5MeGpmMElNTjNMRHVsbDJ5
            ZHpMZ01YWjh5Z28vV1I1ekg0Z1puNkUKLS0tIG1iemZLeFBPVCswRFFadTNEQ0JG
            NUZKSnBWcFJhNUJRbXdRd0NTQS9wbGsKT4tCrwamHI0d7cV3NTXNm6tQMSYjauh+
            TXWyIBlpxuEYANBZzO7R55LHwFa0YkupbGlgFSd0eNi48XWlRi4+Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:bneGdMWjbjzvowGr8Dc+ungTjP8X6aYXLni5I3kJ+alJz9PPEVhz/MtWgLjR18Oeksa3JYjjPEGKz66suqi9DL4ZI9VTgVARQgJva9J94h+WgwEek7KUXCegY9Xqh1sQcoMmQ5r31Xyu42Dbt/kI4/l2sZaQTBQvIK8vGBMRd38=,iv:SFxfE42D0dAfwe7B4EsVwDr5vG/B6yTHfaDDabVnwhU=,tag:FS0r2Wnk24xQ2BJxTXY1Mw==,type:str]
    version: 3.13.1
