apiVersion: v1
kind: Secret
metadata:
    name: mailman-db-app
    namespace: mailman
stringData:
    password: ENC[AES256_GCM,data:fm0Xi4FG9QNLY6GOIOhAJPvdQ9CY15nHNCQx8oBR23g=,iv:jXBRgkvjot03HNfFy23K6ixrRpgTWTg072/ECmrFNx8=,tag:wRYY1CNu4hF/oTkSV9slHg==,type:str]
    username: ENC[AES256_GCM,data:3iOHCiiABQ==,iv:zaQqRSnoknbShVvyIiC5P/cpAuWJ0Fgey+8h8Vtat8g=,tag:KPMhtMiQ0vk+YmGDBvYRTg==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZS9JU0g0SGJmZ2E5Sys3
            M3d0REtIT1N0eC9UdkVxVGRWREYrTWFJYkdjCndOQXkyb1JxNUkyZEJNb3lCV2xH
            ZzlJZW50ZE1OTlI2WjJ2ZDhCbDVadFkKLS0tIEU2YXdPbTNid011VzZ1SUs2SXY3
            eTJacmdQYkIvWHFTTDFWZC9TcHByMG8KvJdexyQJYXy26fbT2Qb+U2xljqdJRu19
            XFZbK7AueC+mbBNWboCz1PhSEH7uVimppkXLN4gR7xpGtmnl5rC4/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:35:14Z"
    mac: ENC[AES256_GCM,data:44OpEYMI9nOMusGx/XqgtRlK+JQT2ly1I78xf9udWxxmN6flbS/EH6uRCnfKwKs8rnarGk4Sn4wW6uAZR8s/yEYFJ3rZWg2KAiGyT0voJ8EMWZApFSzIGNiA/uyCPp41iN1uhYXebF4bv5FAQQtt/YKiMx31C9gHbLs87erS6g4=,iv:4D2kG6j3vrzwpo/BKwdHNE3PLHTriFCCaFLSTzjMvl0=,tag:L//aaoKYPoxvdyB+Qfn2+Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mailman-secret
    namespace: mailman
stringData:
    HYPERKITTY_API_KEY: ENC[AES256_GCM,data:DPl3A3vfSYuSayLN8Eiqgz96jM9k7ir4wjAHynNkyRXZgJZ7L9fsZWS7AmdiY7sPWhnrSsWFsSMw7bjDbkXPFg==,iv:dusQpo7m0EonN9ObdFx4yso2kX19RuxzuvE68cj32MY=,tag:xUpDIQovspNtjlNCq3BbGQ==,type:str]
    MAILMAN_ADMIN_EMAIL: ENC[AES256_GCM,data:QzSIx1wik/bYevpyFGeuSB5CzDC2VhzsMDw=,iv:siBgD2mqdZ49JNQt8fd71ji7b67LJ5Z/KVPVuef6kLc=,tag:1z87g126ILll2AhnN5Qq6w==,type:str]
    MAILMAN_ADMIN_USER: ENC[AES256_GCM,data:GpEuMm8tUcgEXftO,iv:RwfjqF3M+BevSxDwrLC+t0CMo94wAkezXErK5Nx+QBw=,tag:LNXbPlt9Usz1Orah0VSd9g==,type:str]
    MAILMAN_REST_PASSWORD: ENC[AES256_GCM,data:jKHqmbDbSJlUIHTw3jHMN527Wfn6PMb/vyCZ,iv:b8/UeuFfGR6TKO2/u6zSNHQJK9cqi/vZd4ZsIwzZ0E4=,tag:u2BNw4k7gmy0PwJ/PBbXPw==,type:str]
    MAILMAN_REST_USER: ENC[AES256_GCM,data:nOW2T22kXiiN,iv:jgfj0wwR/vTvHDGPAcXKHawk6O3JkEpw5Yd66Gmzc9w=,tag:TmZzQIOUxvwqIDZjcpRXoQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:oZ/VwEmj8QdriZm26oOdiej5dX8f7dceuBd/bkQnW7rznrQgeRgRc+rr/udnZE+0S2kMOxnWciiMgkdzfovVDA==,iv:fqCqDiKZdUGsWWWHmQ2tv4PZ+WivSThLalk6QHwA8U8=,tag:CdkuqfefTHubUhXz8gSGRQ==,type:str]
    SMTP_HOST_PASSWORD: ""
    SMTP_HOST_USER: ""
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZS9JU0g0SGJmZ2E5Sys3
            M3d0REtIT1N0eC9UdkVxVGRWREYrTWFJYkdjCndOQXkyb1JxNUkyZEJNb3lCV2xH
            ZzlJZW50ZE1OTlI2WjJ2ZDhCbDVadFkKLS0tIEU2YXdPbTNid011VzZ1SUs2SXY3
            eTJacmdQYkIvWHFTTDFWZC9TcHByMG8KvJdexyQJYXy26fbT2Qb+U2xljqdJRu19
            XFZbK7AueC+mbBNWboCz1PhSEH7uVimppkXLN4gR7xpGtmnl5rC4/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:35:14Z"
    mac: ENC[AES256_GCM,data:44OpEYMI9nOMusGx/XqgtRlK+JQT2ly1I78xf9udWxxmN6flbS/EH6uRCnfKwKs8rnarGk4Sn4wW6uAZR8s/yEYFJ3rZWg2KAiGyT0voJ8EMWZApFSzIGNiA/uyCPp41iN1uhYXebF4bv5FAQQtt/YKiMx31C9gHbLs87erS6g4=,iv:4D2kG6j3vrzwpo/BKwdHNE3PLHTriFCCaFLSTzjMvl0=,tag:L//aaoKYPoxvdyB+Qfn2+Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mailman-backup-s3
    namespace: mailman
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:sP6poJ/Q5WgHrglR+WNymGJmHHWZKewnCwo=,iv:mbgWZM6wxOK1V5iTeAbu3gfb2VInGyUYVAUPwTOJ9cU=,tag:TERMOI5Y1PCPtc/7P37qXg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vFeDfaUpB20evYzqJs/E0N9NwsihvAVeVCFVK6DtBG/lry2H5cQg/9UsMqO54JGx7WSxKIh50nmXPlncztfzoQ==,iv:SxPEp988GoGoOUo6lDJyYZvPupozkXUFb2bz2Dq5Xec=,tag:bniUFj7lKV1gTQWYARwLbQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZS9JU0g0SGJmZ2E5Sys3
            M3d0REtIT1N0eC9UdkVxVGRWREYrTWFJYkdjCndOQXkyb1JxNUkyZEJNb3lCV2xH
            ZzlJZW50ZE1OTlI2WjJ2ZDhCbDVadFkKLS0tIEU2YXdPbTNid011VzZ1SUs2SXY3
            eTJacmdQYkIvWHFTTDFWZC9TcHByMG8KvJdexyQJYXy26fbT2Qb+U2xljqdJRu19
            XFZbK7AueC+mbBNWboCz1PhSEH7uVimppkXLN4gR7xpGtmnl5rC4/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:35:14Z"
    mac: ENC[AES256_GCM,data:44OpEYMI9nOMusGx/XqgtRlK+JQT2ly1I78xf9udWxxmN6flbS/EH6uRCnfKwKs8rnarGk4Sn4wW6uAZR8s/yEYFJ3rZWg2KAiGyT0voJ8EMWZApFSzIGNiA/uyCPp41iN1uhYXebF4bv5FAQQtt/YKiMx31C9gHbLs87erS6g4=,iv:4D2kG6j3vrzwpo/BKwdHNE3PLHTriFCCaFLSTzjMvl0=,tag:L//aaoKYPoxvdyB+Qfn2+Q==,type:str]
    version: 3.13.1
