apiVersion: v1
kind: Secret
metadata:
    name: collabora-secret
    namespace: collabora
stringData:
    password: ENC[AES256_GCM,data:cQvE1RGRax8=,iv:nww049y2qfmmkoDD1Cp3bczo+bWggXMtoItG9wS1Ars=,tag:LenYcw7qmqdVe/BUCHhilg==,type:str]
    username: ENC[AES256_GCM,data:Vxrb,iv:IQK+ZNe5qu61TRTD9AhNXFmMJ6pxABUqH/QoTvx3rhc=,tag:qAI0cQAJzuk6+jNIHFMINA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU2JIa1pWeEduZE9xMjNv
            WmpaT3Jad2c1eElPLy9DbFNwWjNORVlYVWlvCnhJUEhSWWplNTl4Z3BVTFFoenpr
            U3FOL2tUZUZSZ2k5S0hWSE5UQnZhczgKLS0tIEI1cU54aU9jT21aU1Y1Tm84NUU2
            TEMrQzllbFgzMEtFeG9BVHlKVjZBMFkKAW4Colz/GyZwcl+NAAgNz5TrO839psVg
            7wDvxKVqtyC3GWj2fvpdJ6L53sbD7Y616yYzZR+B8j/NCL/1rKkHTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T18:22:47Z"
    mac: ENC[AES256_GCM,data:UTlYwKIWdccDvdQvkkreR9EQDM2XMRMKdJMXOVjX48Opeus66BdAQ1GzGGy88X/nxjoATef8qIFxIn0ip27oDiK79hqksr0BmBckM/GVJ4fQXB0Y95sAo9ll2u5DMlzDdjF+3+ACsTnHVRUvvCn3tULmx0BEHqRX9xvGrhtqk34=,iv:E8+YvGHeIzq+JhFxgUe198YKnCloE3ugm8xJbEnhfV0=,tag:cFxiTWJHZ1RaHEuUwHWvCg==,type:str]
    version: 3.13.1
