# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: collabora-secret
  namespace: collabora
type: Opaque
stringData:
  username: admin
  password: REPLACE_ME # Collabora admin console
