# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: collabora-secret
    namespace: collabora
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IfWM1uo=,iv:08TS8BZ8tKH4IUcjw3PhN9jjp11jZoJ7xDUrvNXwS7k=,tag:bAuuHTFBx5Y9RZFcHLQ+GA==,type:str]
    password: ENC[AES256_GCM,data:bNGp6YQb9pM6ng==,iv:+54UbK4pmekas6PkchLRqdwETNoVg3W23iK3MkgecSw=,tag:ZhR/F1QoUnTVWfeqLPuBVg==,type:str] #ENC[AES256_GCM,data:k0CIbr92FidxBf0+0BgEQOiFJCX8ZhfN,iv:KDaloyjwftdgdGLfF7u1gWa73wSQ9EnUCmUB5+hVOU8=,tag:EYHVVKeqGOc0Fec4m7ELnw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdjdUZW8yeW9qQlc5L0hO
            aVVPRU5EZ3lHL3Zud2lqV2ZTU0NhbFZ2M25zCmwreHZiMXo1aWJiSk1acEJXYldJ
            U25WcE5NMk5kZXk2RlZ1UjEwaDFjcFEKLS0tIDMzUFc0Um1FWk5JTVdhTGt6bUxs
            amlkYm56bDJnNU5LMGZFREpTRGU1RU0Ko8Oph2OwTPVvTkYSzfyLDRncN3/blst5
            2lOGskAOQtyWL9vWkn9b7bOrUb6i8a0OoJsZRrljZCOc3ulHUG01aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:1npUi/ryWzdzxaC4dM4wdXQ0dOH530sAsE3pfjQUg9RQShRxuk2CWrh41kUIxa34VnnB8+XcYuxkgPtng2D8znx5QKUT/RznUbUWpOl8Zqk1VT6ehK9K6PqrCrWMCl5OqWQSeUA/tB417/TtctIW3MItjYCPGkq8ingCJsrYoV4=,iv:TFsygVVoEOB6Afalp4GvsFdJTQDbDKCxv4UwoGVE6do=,tag:0G/R9ipMw+uz/NP97e9Skg==,type:str]
    version: 3.13.1
