apiVersion: v1
kind: Secret
metadata:
    name: kubernetes-mcp-basic-auth
    namespace: kubernetes-mcp
stringData:
    htpasswd: ENC[AES256_GCM,data:1fzlmD9nV9VbmEunmtth+g/zh93eMXYbk3HKjAMwwaiKu9EBERjfAs8=,iv:s3NXm8i/fPQ4k4HJxSIxbKsZkOTIe3mPEwFNyN07A6E=,tag:CZADfMDwzB4hFnvKNFcv9w==,type:str]
    password: ENC[AES256_GCM,data:Ti6x0dKSFITelR56y/a0d9Chmyk4TOcP,iv:oQxbHzv6C7PBwCKFVXx7eRHC/fJ6dSxWWTnTdbZQPpQ=,tag:dUnNgCgO2RKI8LnhGqapZA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYTcrQ1pwT05YblZiNG8r
            MzhHaU5KbStJcmxXeitSMjRrTkxCQTh4eVRnCjg1UGFDaEdnMmd6a29qbGlCYTRi
            bmxISEtXdit2NGxUZmpRdEoyb2k1OW8KLS0tIHp1ZjZoclczWDNqdlNDTG9jQzFL
            bzI2OEFtZ2g0TENRYXdNTTAzalVOdmMK9BlrtYh84oYiQbq53bhCsdkZC+SYM0WT
            3xXwjZXkU0Ra21nOYcTkt/2iqIjbPvo8Lr6GQbR5+GYwF2UsLubrmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T08:02:37Z"
    mac: ENC[AES256_GCM,data:lfph06ZrVFL39z6AcX70DZsRoFzivnKbSLdRvCcEbxawqNFUPexcQqBG5MMVt5XOPzFxmmQRu/eLWZw5nePAXffGU+yDweKvdc7lHmu2L7MzgooUUyboQxL68Eu0iUIuoLxZWcpQKncxWpKSm34P8N2uZN8Fci6j/+0pRonrdrs=,iv:QHt5PLbPfNZeJ54otmg9L6qkGKFvcD8M/7s4vp3POyg=,tag:Kr7y00y1W7VRIl7rfVn6AQ==,type:str]
    version: 3.13.1
