apiVersion: v1
kind: Secret
metadata:
    name: kubernetes-mcp-basic-auth
    namespace: kubernetes-mcp
stringData:
    htpasswd: ENC[AES256_GCM,data:vN2waP94zUw9+hxVTOFcRUP85biKdh39AuRrvOse2h7+M52xGcMgLF0=,iv:8GL3dlcUp+9dtpaVnHC0QnIEx63jmpMZWaMtDChCB0Q=,tag:1dt8q6FQB4jIkf4mjXdeng==,type:str]
    password: ENC[AES256_GCM,data:Iu/SfEIlDDm3lre9Mgi4D0Q3mvu2UILR,iv:AbK6BPr+4TK58g9hgY3jOmE/hWDtEjA4mthFavEXqG8=,tag:fn1JB/PhNA+dMgu0mTZwUQ==,type:str]
type: nginx.org/htpasswd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmJuc0VJV0RXdnpFenFv
            N2NzenNGWUlEeG9aT01kRE1Cd1FMM2tQeHl3Ck9yMUoxS0NIY0wrSE9kaWZGMDJw
            SGlwUkpuWFNKRmR1TWU0UCtTdmdyamsKLS0tIFFwTSs3Z0NFT1JBbFpzM0s2RmNa
            cGNheUVkamFoOGZvemxMNUhGR2FZUEkK+DN9WV6HkY388GGu2RQM5fUBw/7y5GOh
            +DoHd1GiZExa7oRSwTiUmkg5vw9NhuZxZ6SFO8O/jWggvuiaJIdu+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:23:48Z"
    mac: ENC[AES256_GCM,data:oj7lee5JJhp39xBngY5Kum7VO7BQxRmPk4FjAo9eoO/svWu4DMhXy9h7YHtV4ppypHLcvZUsHkGIEVT8icmCtTImMvNWNft7tz+ad90PTqAgX2QZ7QwULI326LHbVKBRFzu9LQZutlSU6OJQw0l38WliYlu2g1cDkKyyiuRD4Mc=,iv:35/fljm+jT94CHic9KlbTWtluHNneZUP+oJVtEJLTbY=,tag:C4hKhGoCT6oSToKs3Q63Ow==,type:str]
    version: 3.13.1
