apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-3
resources:
  - ../../../base/wordpress
patches:
  - target: { kind: Ingress }
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: site3.jit.services
      - op: replace
        path: /spec/tls/0/hosts/0
        value: site3.jit.services
  - target: { kind: Backup, name: wordpress-mariadb }
    patch: |
      - op: replace
        path: /spec/storage/s3/prefix
        value: mariadb-wordpress-3
