version: 1
metadata:
  name: Homelab Kimai OIDC
  labels:
    blueprints.goauthentik.io/description: OAuth2 provider and application for Kimai
entries:
  - model: authentik_providers_oauth2.oauth2provider
    id: kimai-provider
    identifiers:
      client_id: kimai-client-id # CHANGE ME
    attrs:
      name: Provider for Kimai
      client_type: confidential
      client_id: kimai-client-id
      client_secret: placeholder-change-me # CHANGE ME (also set in apps/base/kimai/secret.sops.yaml)
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      redirect_uris:
        - matching_mode: strict
          url: https://kimai.jit.platzhalter/auth/login # CHANGE ME
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
  - model: authentik_core.application
    identifiers:
      slug: kimai
    attrs:
      name: Kimai
      slug: kimai
      provider: !KeyOf kimai-provider
      launch_url: https://kimai.jit.platzhalter
      meta_launch_url: https://kimai.jit.platzhalter
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/kimai.svg
