apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: icecast
# Icecast is a stateless stream server. Source clients publish to port 8000.
resources:
  - workload.yaml

generators:
  - ./secret-generator.yaml
