# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: icecast-secret
    namespace: icecast
type: Opaque
stringData:
    ICECAST_SOURCE_PASSWORD: ENC[AES256_GCM,data:Qp1LBfnA5froZQ==,iv:k1GRH0cFNjLo+pZ8xXlL1BMRrmQDNYctEfhaGQldtlk=,tag:+p5sGBpRCbJDgvnUS3fYYg==,type:str]
    ICECAST_ADMIN_PASSWORD: ENC[AES256_GCM,data:KQ4bJEOf37c8cQ==,iv:A6KzctAoejFJPw74mt5kzpdvyO3kBwiau1wBDBXaoYI=,tag:16iosMsVvk24HkmjMBJxtg==,type:str]
    ICECAST_RELAY_PASSWORD: ENC[AES256_GCM,data:w1/3kA0behuf3g==,iv:KtlQDnQfVTjkYUraGsnXUxNdEbOqnu4k/chTaXvJKMo=,tag:BnfjXUnvAPliJg0xqoSnoA==,type:str]
    ICECAST_ADMIN_USERNAME: ENC[AES256_GCM,data:Xi9oXHI=,iv:gaaGIeyPjKq1Is1q2F4L9veYJnJwEX920FJ8qjvewLc=,tag:JfNC7VRRpz0tVuAiZljfeg==,type:str]
    ICECAST_ADMIN_EMAIL: ENC[AES256_GCM,data:LloNG8Glhi+vaUqud3ETxvU+,iv:wrCawfzwJaE78FV7ZG2tK7bCMu1ReU0Ni0ETZcDcMuI=,tag:nk0oLG6iyWWTA/VR7u+Vxg==,type:str] #ENC[AES256_GCM,data:nv8arQESnDVkXQ==,iv:SIca3gFvI6VaaAH+LXFNggxj+Zvxv5fVN5ooAlbrqtM=,tag:mO9A7/flv0D+yF6glZolRg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTkgrbjdySmYzL3BMakJ1
            YzcrTjJpUUNYWXBoM2JSV3VKSFdEbnN1QlhBCmdLMWpYYnVjc293RkM2aGQzY3Bo
            NGhPbVNTby9QUWZibkdqSUozd0ZGN3cKLS0tIE9GUy9lTDNkQVlaZnR1aGRQZDNX
            SkpCVGxrbDRXWUdYUHkxZnV2a1FBejgKj4oYV0l5eT9jTJJedcYQBnTm4jr4G9Ut
            5vf7hgNLAsBeIP6cp6juDuDXh0qDY47bkpPh1gw/nOn7MdVdxd3P4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:VmQp4EG6v1GKSYI+gGhFHFhD1VfwSm9Wn6K3+g1zIr9VhNB49FYbmWK2+Yuflzu4Bz+iLzOHD08qohF33op46pT4PMogVYK6BwuKlAFTzhTlQIKBA27kyg/W957kIXvb/NXfyKraWE/Bc2sDcVTr2OOOqJlz8SLk+lCf0K4XA3A=,iv:KXNXO+fR/6ivAIB99woWF+C1I09yDvzcW72MjWkKBDE=,tag:z+HHGQd2hsRrD81GbMe3SQ==,type:str]
    version: 3.13.1
