# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: icecast-secret
    namespace: icecast
type: Opaque
stringData:
    ICECAST_SOURCE_PASSWORD: ENC[AES256_GCM,data:m/ZCl719e01XVQ==,iv:RbYR8fhHR2GddSlAr3Thvmr4GQEQD1ENhaEvZdi0CCg=,tag:oW2wBW6BgiNWRMKToNeUbQ==,type:str]
    ICECAST_ADMIN_PASSWORD: ENC[AES256_GCM,data:hosK56+LMaCYhg==,iv:/SvEQOV1iu3QqI97zQYzqfNQBoNLUF6R+ihcy2YEOag=,tag:gspkLjufjHLDRWY368/Zaw==,type:str]
    ICECAST_RELAY_PASSWORD: ENC[AES256_GCM,data:es7TgF3uP9p8pA==,iv:Ep8bzwNQc7IN0rc2L8dgwsJ5Qu+mEDITa5Dqy5obOkQ=,tag:sVUwZ4p+Nl4bO3BaO8FUcw==,type:str]
    ICECAST_ADMIN_USERNAME: ENC[AES256_GCM,data:/eIQ6Dc=,iv:dWHRLfIw2zXmNaQCa2EgR0IjRPiSrkFVt0vhh/Qr+wU=,tag:r2V5CB5pv9eB3BGvfr0FJQ==,type:str]
    ICECAST_ADMIN_EMAIL: ENC[AES256_GCM,data:0j+/1K2SBjX4gK9TWmui/vvC,iv:yPySlO04SIVJi6Txxhv+mQvd0q9iggjdp/CO9IuFe4Q=,tag:2nB1fJC+Yjy9Fv0267odZQ==,type:str] #ENC[AES256_GCM,data:2KS1oMADQ6qm0w==,iv:8qoW0lPeIGvXaNZHpMGMoFfQgQ4zTNcxAe+pVR+Atjg=,tag:lLvQPen4fRkH+64hXFDg+g==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUEg5Y2JhSTQzN0NwUDND
            cis5VjJGYklicmQzN3JuMHpZRVdLbklUK1N3CkE4QzNQcytTT01YTlA2NEpuYnZp
            M1JXMlhTaVJ1WE5oRFNKOXlGT0VObU0KLS0tIFdwanZXMWVibmNyYjNNdEF0NFlh
            S1g3V0xtL3RhNHpjRmVnNTArd1puSEkK3rgJlrMvdijwB31K0djQnfugo+36oUOY
            rvIiwXgE0od6cnltkB1ojKqihZj6AVOCfSDyMkjPFbWSB2UMV6iNMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:Gif0j6IPXpzaUr99bhsN+2rRbo9rjg302eKrgp4ZFAzeZ2fX2Vn3VM9CtrleStlOekrjjHmhaUkC647XKZ9k3h4GQWjkBboGkidzTJDqjgfirlrbbMPdQv2pVeDybRPZI4Vh2rf67JYB5w+z380Q4joFXjjtTImueB3stkHQmlY=,iv:CARqd6DArX6mswjfUILfedCsA555t5rwm3U8H4PoiHY=,tag:ikNZ8InGYvO59OuFoRzv7g==,type:str]
    version: 3.13.1
