apiVersion: v1
kind: Secret
metadata:
    name: eurooffice-secret
    namespace: eurooffice
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:DY+JXfW5nB+VOlLr3Y4insAmOsi+OSUec0HyRq+X3uEOVpGc6x4Ph1v5g41/otNDyqo8pkVzyFtpjR4ItcEpTg==,iv:6wN2IEUtvK00VWlPRlC19qS/OnAwh3nRvO6JzXkH3ZU=,tag:iSD9DiTJ5P5ujcUEsFopvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYVpxZk1WNFNPd0lidGJW
            VHhzckRhOVJhWFZoSE5XK3p4WEFXQmZKcmhNCjJBcHBudnUyWEpuMmx5T3hkNXlD
            Z2YrUzdSazRVNmVXelJscnREdGhod0UKLS0tIEJva0xXalZaWEplY0FreStBYlZo
            ZnNOWFk0YXg0YktiNk1JVEVHMEdYSlkK56/cBPUp3ObLz02F6kpyotvia0wnaUg4
            M4npKoa9kxGyybSVV6OmTv+gI8g23oO8OGK0a6U8IhXDlP9bVhprUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T21:16:30Z"
    mac: ENC[AES256_GCM,data:sXY/KUySgyD+ai7/PNpPGkWqp2MC53gEwa0TGprmsZKrjARg5hQFvoHNROtgE9HEKkX8MZGBe8p/bncd6EdNFbVim3J9+kmy6/7xJosOafWdD72w8IF2ZwSIavq93IX5Hg753qV2TSXuY454nDanz0UJEDCFPIwje4CWeh8A230=,iv:3sqj9P/qN3sP42bW8Lq7Qka4gSgAyc1i9evge/bJ5NI=,tag:zLLJWFTayNc5Y1cWhGAGLQ==,type:str]
    version: 3.13.1
