apiVersion: v1
kind: Secret
metadata:
    name: eurooffice-secret
    namespace: eurooffice
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:DY+JXfW5nB+VOlLr3Y4insAmOsi+OSUec0HyRq+X3uEOVpGc6x4Ph1v5g41/otNDyqo8pkVzyFtpjR4ItcEpTg==,iv:6wN2IEUtvK00VWlPRlC19qS/OnAwh3nRvO6JzXkH3ZU=,tag:iSD9DiTJ5P5ujcUEsFopvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINkt6VHBWWDFZY3g1emxG
            U2VnUUhwZXVTb051c3FCZ2tzSlNDejVzeDJBCnl1OU9IMUovOTlaVjc3bVp2dWF4
            R1pCYzFpTDBMcGIwNDU4UTFpQWV6Mm8KLS0tIGR3eHBWb0hqREJUUzE5N3NlMWNk
            Ym01VTIzeHNMVlAvR2Fyd1JRMHQ5OXcKDRR200oGk4lmyKZGahIqden770PueN4R
            j75XVuiUOXX+rZXp6K18ZmAi09KQH/wFEGDrUCs9FZRDPNoKBYR2Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOXdLTkwxRWVjY0pmTHpH
            eitZdzdqY3JHSVl2bW9pV3hzTXBMYnVHckNZCnB3MkZhei84cjk5RjF6U3lJeSt2
            NGYrTnZhdHV4TEJzY2ZCaHFJK1U1WVEKLS0tIEY0dGlUaGhxS0Vha0o4Q2Q1T1RE
            SDdxRlNSZ2xLRmh0dzFNRHlURXNEejQK0VCWxnZAwIRbEaleND0sKidhveUe+IAG
            ywGJxmMXGwh+dAW3mx3fQMQGCYdmZW5OAZLOkeBIhH2waqs6lnbVjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T21:16:30Z"
    mac: ENC[AES256_GCM,data:sXY/KUySgyD+ai7/PNpPGkWqp2MC53gEwa0TGprmsZKrjARg5hQFvoHNROtgE9HEKkX8MZGBe8p/bncd6EdNFbVim3J9+kmy6/7xJosOafWdD72w8IF2ZwSIavq93IX5Hg753qV2TSXuY454nDanz0UJEDCFPIwje4CWeh8A230=,iv:3sqj9P/qN3sP42bW8Lq7Qka4gSgAyc1i9evge/bJ5NI=,tag:zLLJWFTayNc5Y1cWhGAGLQ==,type:str]
    version: 3.13.1
