# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
# basic-auth secret consumed by CNPG (initdb owner) AND the app Deployment.
apiVersion: v1
kind: Secret
metadata:
    name: roundcube-db-app
    namespace: roundcube
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6eyMT+utrWFM,iv:xgygJlekA0zZruovbPA/2+z6oK32NJS3wpkVw9dpaqI=,tag:SYrxjQaAXSpIu0HzNfRh1Q==,type:str]
    password: ENC[AES256_GCM,data:0ZUcUtm97kC8PVwBoHue,iv:GwSf3oDiAJb3fxikV+a+QEvlLLL3xx4YinQb+HA8sVA=,tag:a9zTNCvN8GE0/Qi94O1gZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFpoL1AyenR4SCsyRFRE
            WmYzSDFob2RMN3hJMFRnZDNmYm1JNEo1Y1Q0CmZabzdpbVExT0lEUFZIUkFLakZV
            cE1kQ2xxVGJxNGc5dVJwV3I3Q09pRW8KLS0tIGhrWEI5b09tblYvallNaDB3SHIr
            Tkt0TTg4Wk9nbDNmdXY3SFp2TzFmTzQK2k+2Q9QCJQdG7F2G9S8W85oquSiw3q2O
            DOgbtMutXGzBS72JF2MIQq6ygUkdD8HiPEqkUyizE0XMTsQLFc94yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T15:55:39Z"
    mac: ENC[AES256_GCM,data:SFSoOurXPiyi1hYZ38w+wXA2W/UP83vOxP0hmPubcRJWedEb7U5zcLHtjkkNBXUe6NiAvwwHNuY/YfgWF87VWIMd+n+2imPawP/+mHL+FCO8Xy6KA02G2qU47/3uPeh7QqCuTRL7XBO9mKsYtZvakIMXFvWTehLOnz28UOd3wEY=,iv:g4NyOlq9cx/KUzmtM7N48O4Ftvl3cQ6Jg+9GSlqCWC0=,tag:B9hU9whvUyHOXS2A+FfAMQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: roundcube-legacy-app
    namespace: roundcube
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H1oVY/2WWAYgxe4IQHd4j5gaSpmGiLQQ9LHa8hN2Kk1vBF/LjZclmEHU0nd0zQFPEBLxuCGeLg7mWbBQnFK7pse3Qc7E+uz1mm1cMwSR7HiQeYDl,iv:IovNRpOcqCRt58Z2BmcQAg4rm5Sb48xuffHAZpC2HK8=,tag:QpZ6bPQ3yZLC2M+0yNU+2Q==,type:comment]
    des_key: ENC[AES256_GCM,data:G0TB6lW8IbV+KcFgSlXthwCIk7lNH4rl,iv:TWrrouagx1E8SWazgTMWPZXaXPedfSpC+Ne27QDtHdU=,tag:Ts7DJTr/U1yVYfnspSoXyg==,type:str]
    roundcube_mysql_dsn: ENC[AES256_GCM,data:3xY8kynHLA85xYAF/qkneMQ/bK3/UkfBKseCt9Ls9ICiYPiP6+X6km7gnLxopGpc7A2aAQXe3Of0X43Th2sc0elnG8Gw7vaDl/Y=,iv:CjpZuDE9X7Rw7TSYxGadRly/eChTwDMCBVlC84hPobg=,tag:K3TsnkxzGYTpMcioT2tksg==,type:str]
    virtuser_query_dsn: ENC[AES256_GCM,data:5JQmJrozmPILPbI3Wq1FrWAMev/fc32JdI3+FF5ZwE4VzilMkACg/hMBd+UsJFrAe+00ySdR1T1f80Y80viqLHx/vGdz3btwFhA=,iv:1r3qcQcCeKWCc8Nl+NBbedVSNpmhe9LZxrIUfkXmz04=,tag:8umqaRry/oL/aQ6JUIqiaQ==,type:str]
    password_db_dsn: ENC[AES256_GCM,data:/YcYKebs32A20Dd3VRdhIU1Si9kBjFGqchbFI6A8q4XNN4i+ZCUZyMNifMVZUkQZ5fxszzBkYLaixkYONRg/a/7J9u4=,iv:SPN45X8Ihxug8kgcb0xXD+tq6nHbQlmqrc6I6j93PfY=,tag:2EFlhUFL5JExeABFDloUuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFpoL1AyenR4SCsyRFRE
            WmYzSDFob2RMN3hJMFRnZDNmYm1JNEo1Y1Q0CmZabzdpbVExT0lEUFZIUkFLakZV
            cE1kQ2xxVGJxNGc5dVJwV3I3Q09pRW8KLS0tIGhrWEI5b09tblYvallNaDB3SHIr
            Tkt0TTg4Wk9nbDNmdXY3SFp2TzFmTzQK2k+2Q9QCJQdG7F2G9S8W85oquSiw3q2O
            DOgbtMutXGzBS72JF2MIQq6ygUkdD8HiPEqkUyizE0XMTsQLFc94yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T15:55:39Z"
    mac: ENC[AES256_GCM,data:SFSoOurXPiyi1hYZ38w+wXA2W/UP83vOxP0hmPubcRJWedEb7U5zcLHtjkkNBXUe6NiAvwwHNuY/YfgWF87VWIMd+n+2imPawP/+mHL+FCO8Xy6KA02G2qU47/3uPeh7QqCuTRL7XBO9mKsYtZvakIMXFvWTehLOnz28UOd3wEY=,iv:g4NyOlq9cx/KUzmtM7N48O4Ftvl3cQ6Jg+9GSlqCWC0=,tag:B9hU9whvUyHOXS2A+FfAMQ==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: roundcube-backup-s3
    namespace: roundcube
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1lM2z23OYwpbjA==,iv:c7eGhseRLV/UrQu4DvE+IPBJDy9J8JEIY8BSyN9flHk=,tag:kHNDgEBDKvsF5igP28Oh+Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IQWrv7GqaTuIKw==,iv:53DRgGvhE9CcdSQzUPkUFDjQm/zKaGN/eIwnXCxxVJc=,tag:TzNbo6xudzk5EJDBB8CiTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFpoL1AyenR4SCsyRFRE
            WmYzSDFob2RMN3hJMFRnZDNmYm1JNEo1Y1Q0CmZabzdpbVExT0lEUFZIUkFLakZV
            cE1kQ2xxVGJxNGc5dVJwV3I3Q09pRW8KLS0tIGhrWEI5b09tblYvallNaDB3SHIr
            Tkt0TTg4Wk9nbDNmdXY3SFp2TzFmTzQK2k+2Q9QCJQdG7F2G9S8W85oquSiw3q2O
            DOgbtMutXGzBS72JF2MIQq6ygUkdD8HiPEqkUyizE0XMTsQLFc94yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T15:55:39Z"
    mac: ENC[AES256_GCM,data:SFSoOurXPiyi1hYZ38w+wXA2W/UP83vOxP0hmPubcRJWedEb7U5zcLHtjkkNBXUe6NiAvwwHNuY/YfgWF87VWIMd+n+2imPawP/+mHL+FCO8Xy6KA02G2qU47/3uPeh7QqCuTRL7XBO9mKsYtZvakIMXFvWTehLOnz28UOd3wEY=,iv:g4NyOlq9cx/KUzmtM7N48O4Ftvl3cQ6Jg+9GSlqCWC0=,tag:B9hU9whvUyHOXS2A+FfAMQ==,type:str]
    version: 3.13.1
