apiVersion: v1
kind: Secret
metadata:
    name: roundcube-db-app
    namespace: roundcube
stringData:
    password: ENC[AES256_GCM,data:4y0xjK1DOPSA0HXmt3o0,iv:FlPj12iepaZFfg1m18g+PL8IwarFF1jXKiTbM6ruP/I=,tag:LPCANLVc+11psd5BjHA/Ig==,type:str]
    username: ENC[AES256_GCM,data:hax3tPZLzBOH,iv:Hu7YBYMWWdlIOURVvh4UiEmhA7gQK2qZdrVIq1zjwpM=,tag:HXgU3A5Jdvb/EikO7dp48Q==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3VBdDMwVy9qbDFqN0hS
            ejZWOS92T3VUdGxYSFowdjBHQ3p2bmhoSW5nCkVsaUltTlRwRDZNQjJxTzRYQW5z
            OXhiNDI5ekNjdjQraUIwNWg1Z2Q4Q2sKLS0tIGNCaG9wOHhiUWVqZ1BsWTJYQ2Qr
            Rk1JdUlhL2RhZFQ4OForU1hJR3pYelEKgGPo1q+41gIZPYCfXH3pty7jvaX6Nsbc
            advKA6+gqcd4/q6lxg7rqNeS9dUdzhKP1KXF+vsddUJxNXeL8qjpCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T15:48:35Z"
    mac: ENC[AES256_GCM,data:g1Z5Q5dXRNtRPqwsi5zxC2vZylorHwIgsOTHAcQItPpgk4p8Y4VenSz3da2v5r9+AlSw1Af5mggJde0Mw/znc1HZctcKH/PMwF8Jz3WI4orB0MudSgaoignvmC/sEMvbOILMIm3SV3j+D3vA3nUA/hgVQowklG8tvO34tcBEyHY=,iv:RIvTzs9+f49+GtR0WO4GqUp9EO7EihHrs3IhP0x7krI=,tag:KlLZI6lZ2M7HYBBVWYjugg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: roundcube-legacy-app
    namespace: roundcube
stringData:
    des_key: ENC[AES256_GCM,data:HuZoBImmPkBrblIeF/8YvOGeh+e6QyIQ,iv:2m4WMONt9l2I+3aSs7E3K5cy4j0NQS96Kt05C+SoDEo=,tag:NAAKplcRtZRBdb6xc0SntQ==,type:str]
    password_db_dsn: ENC[AES256_GCM,data:cjyzjlKjOgbvydxGIeoKnslrLCuRhFOXpEd0eLwYFgNTOwSGX5zPpWBfs/ohyEZg4OVkP0RGmI0W2ajcH0MHyo9Cu6Y=,iv:6woHZPkfNjikV4FD608T7RQhX3Rr70nSg9sIB5Zuodk=,tag:MDrdt63Xdblx88imFKuiqQ==,type:str]
    roundcube_mysql_dsn: ENC[AES256_GCM,data:cMFOEssbwWbqSpdDWS1tXw50hnaiXHD9Z3tKmpRnrzUj9ihnrTSz6c3fqBnWoRlCwzKckPVsR0pyesFghBjAlc6qM529EZ3ADyY=,iv:bi0HSdstrAQ5jc/GystcMZxiQA3jpcik0ga9SoF+4rs=,tag:hIA091Zu0IRYBFCnMe+rKA==,type:str]
    virtuser_query_dsn: ENC[AES256_GCM,data:/qRpG22RJh6A+4+lIfgQoHM44R6cKqA/zbPAprNxLsgUpwuXFsxZ+vfCYLenH13z49xTQhB0WyAlRhLvM/na2F3+asyIZZZVkbM=,iv:r9ceyPUlY2TF4l6EFeJW+0848J8XdTfDom5LNYdppZY=,tag:B2BAmcRoc1Y901ah1kdTIQ==,type:str]
    fetchmail_db_dsn: ENC[AES256_GCM,data:tbNKe6FFg6iPalObwhVSD00spvnTBGZIACYmQHYU2U39LldfqFCykpu9nfNmtVslJ74V5AQITdPCGMlY7nfuo5/GGXD/Q3k=,iv:uHDcsjyqgalU16d9G9CFGlnxLNCSb6gotEr4XlUSaKc=,tag:KhHqoA60H69IBZdjwwC7Eg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3VBdDMwVy9qbDFqN0hS
            ejZWOS92T3VUdGxYSFowdjBHQ3p2bmhoSW5nCkVsaUltTlRwRDZNQjJxTzRYQW5z
            OXhiNDI5ekNjdjQraUIwNWg1Z2Q4Q2sKLS0tIGNCaG9wOHhiUWVqZ1BsWTJYQ2Qr
            Rk1JdUlhL2RhZFQ4OForU1hJR3pYelEKgGPo1q+41gIZPYCfXH3pty7jvaX6Nsbc
            advKA6+gqcd4/q6lxg7rqNeS9dUdzhKP1KXF+vsddUJxNXeL8qjpCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T15:48:35Z"
    mac: ENC[AES256_GCM,data:g1Z5Q5dXRNtRPqwsi5zxC2vZylorHwIgsOTHAcQItPpgk4p8Y4VenSz3da2v5r9+AlSw1Af5mggJde0Mw/znc1HZctcKH/PMwF8Jz3WI4orB0MudSgaoignvmC/sEMvbOILMIm3SV3j+D3vA3nUA/hgVQowklG8tvO34tcBEyHY=,iv:RIvTzs9+f49+GtR0WO4GqUp9EO7EihHrs3IhP0x7krI=,tag:KlLZI6lZ2M7HYBBVWYjugg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: roundcube-backup-s3
    namespace: roundcube
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:nUqcujk8TaiBlmi0HZ2XrR8jiJzEsF+/3oQ=,iv:8Zgo1DDV5NZmO9WKno6GVuJknoApz+t4uAamuAUFQtk=,tag:uAxTNyBX0e8JvrcLGi1a/A==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u7uaZpq5GAgPZc0M4+qvMu+k7WRnIuaPEXEIW/zY71pTda/56ksk6eY56XDF0pp9uQx9HzqbO/HajKEgpd10rQ==,iv:Y81u2jrkGB9K3rx0UIO9VKt1RzH9/5cPtvlgajEwqWM=,tag:fFw6178/2bFVPO8ScoCNdg==,type:str]
    region: ENC[AES256_GCM,data:/zO7UistvP38i4K0FkY=,iv:qlFtwQrDJCrdqE5+cP6VCEmy1PBs4wuwjQXpxwGLOlU=,tag:AzwYNRWRW1zONFw6BHYlIw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3VBdDMwVy9qbDFqN0hS
            ejZWOS92T3VUdGxYSFowdjBHQ3p2bmhoSW5nCkVsaUltTlRwRDZNQjJxTzRYQW5z
            OXhiNDI5ekNjdjQraUIwNWg1Z2Q4Q2sKLS0tIGNCaG9wOHhiUWVqZ1BsWTJYQ2Qr
            Rk1JdUlhL2RhZFQ4OForU1hJR3pYelEKgGPo1q+41gIZPYCfXH3pty7jvaX6Nsbc
            advKA6+gqcd4/q6lxg7rqNeS9dUdzhKP1KXF+vsddUJxNXeL8qjpCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T15:48:35Z"
    mac: ENC[AES256_GCM,data:g1Z5Q5dXRNtRPqwsi5zxC2vZylorHwIgsOTHAcQItPpgk4p8Y4VenSz3da2v5r9+AlSw1Af5mggJde0Mw/znc1HZctcKH/PMwF8Jz3WI4orB0MudSgaoignvmC/sEMvbOILMIm3SV3j+D3vA3nUA/hgVQowklG8tvO34tcBEyHY=,iv:RIvTzs9+f49+GtR0WO4GqUp9EO7EihHrs3IhP0x7krI=,tag:KlLZI6lZ2M7HYBBVWYjugg==,type:str]
    version: 3.13.3
