# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kimai-secret
    namespace: kimai
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:CarBy7AWDFZ1wg==,iv:YhYuF7/kYIGMpQc5St2PLvIVkZbkc2ElpZb0HcSEX9Y=,tag:KWYxOqH440mLB6F+DdoUOA==,type:str] #ENC[AES256_GCM,data:G6Y9ZjWRw2FeNix8DrwU75zfWNUP,iv:WnHpA5uBhc/1bjjyUEmgfFED7UEGaeQOPeclKBmXJww=,tag:1wYTeRajcaVtKhSQlaknmA==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:+n7i0pLTizbz3w==,iv:cA80wQvWdUx4UqxqHSTlzOynS0SZZNNbOtL5igIJyGA=,tag:20Q943RO41p32EctN0NemQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:NSDfvxC00efRsg==,iv:9pEoe1kazEvRK3YmZ7vdXW4U1ROrNaZ9RPHUpfPIYbg=,tag:cjWrKiZDzKOY+6Fg8HjrXQ==,type:str]
    admin-mail: ENC[AES256_GCM,data:3Ek8N5fqn+VDzUZV13oupkkm,iv:MRJkJ5SU2IC+cJ/mmFzQh+2HIsaFuZUt8UKcsfn8KlA=,tag:v0Nqo2RIP0lrVxdy3GhGeg==,type:str] #ENC[AES256_GCM,data:BgiSplsIFEjbSw==,iv:/kzZDf37n+dUdHsrnG0Dn1Dtaaspqsag0T5Bn7sV790=,tag:v2Awxq4GJ+AU0ykHr25a5g==,type:comment]
    admin-pass: ENC[AES256_GCM,data:gxZ7i8Ag8NZ8ig==,iv:1G+uRIzu7ED6ocB6SkmBfe9AI+1KGIo1KiVcfaK+6SE=,tag:FtIVTU/cHBjn9w9K87qVCA==,type:str]
    #ENC[AES256_GCM,data:tUTgxXzI3k5bD2qtx7e7WGxFEvnPNjQFYJi9vslix9kNCoT1ZSMj6AtLcktVlwENLd/lJsEeUVU12WYQeKkPrOIQmiD3NMVctw==,iv:o6tEQgPUwMuuYYpls+HlDEqGPEpBjw4AsNSSTKvPqfY=,tag:JU11wcJgKYurZsud4e7AGQ==,type:comment]
    oidc-client-id: ENC[AES256_GCM,data:/w0IsvMw4de2Udtt7OTY,iv:kyRQUuLwXdl7IbJOni8Wfd4zyTC6UBT0B1H09WEVE3s=,tag:FgzDwvQQ0yUlHadXABTv1A==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:geahMGA2d9gZoQ==,iv:5kJX6mYthuGZzZHlhWMpoL+9p42pMUKxCJ0qyo0pYBo=,tag:SizNRq+5bZDq7vOMp16xQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNmxscm1SY25hM0NBWmZX
            YUdlY1FmeWFWUUg0K3dUdkthZ0UzaFowOVR3CmkwMjhWcGJjejFqSWx1djJha2Z4
            VER4enFiNWtsK1V1R213Qm16Y01ybFkKLS0tIE9CbWhwaitvZmdjQzh6VDJoeXhj
            N0xQNEVnVCtvYkNVTmppYm1pTzlDeUkKgB1aCwLuZpDxhnKRi5D8eFQAuBOTiJKL
            +5U+y3Oa6SogUmVW7ohzkfrhYGdPMFNc/Dk8YK3AUVbLMmDM/6FmZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:3c8wuVcbGKX/aASbUyFj5kWoH25D6R2AWtmKQgWI1Zj3iX0yev7Scv+f/O9pljnZQnsJv2KowsoABL6qQi6wT4ATuEFIUW9ZmHRMg0atKy2Gn5B8m1+Y2EBX7Q3TA+jFFpvrjJzKhGMk+gM5O0CO240sTZgPTPoPRlg1NFD3KnI=,iv:cyJvqbLG9wNB6h5i/2Kf/7pRaYeKhsl8uSiHNX8S+i4=,tag:R9RyDNNt++z9ZGJph3DA2g==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for mariadb-operator Backup
apiVersion: v1
kind: Secret
metadata:
    name: kimai-backup-s3
    namespace: kimai
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ymNgVr0YYClF9A==,iv:RXaVzdLx4cGDszunkSXhwJf74FC/Rs0Kyq3IFiKQOqA=,tag:SwNn3EV2+l3DC/i/Y2Qe6Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GiraxP8hBc/T2g==,iv:3ZsOuQwqZI94jwOsbcf9i5xsCJVLeMfIXSImxse3I30=,tag:mh7FZvsOUN6I0KOmLDoA0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNmxscm1SY25hM0NBWmZX
            YUdlY1FmeWFWUUg0K3dUdkthZ0UzaFowOVR3CmkwMjhWcGJjejFqSWx1djJha2Z4
            VER4enFiNWtsK1V1R213Qm16Y01ybFkKLS0tIE9CbWhwaitvZmdjQzh6VDJoeXhj
            N0xQNEVnVCtvYkNVTmppYm1pTzlDeUkKgB1aCwLuZpDxhnKRi5D8eFQAuBOTiJKL
            +5U+y3Oa6SogUmVW7ohzkfrhYGdPMFNc/Dk8YK3AUVbLMmDM/6FmZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:3c8wuVcbGKX/aASbUyFj5kWoH25D6R2AWtmKQgWI1Zj3iX0yev7Scv+f/O9pljnZQnsJv2KowsoABL6qQi6wT4ATuEFIUW9ZmHRMg0atKy2Gn5B8m1+Y2EBX7Q3TA+jFFpvrjJzKhGMk+gM5O0CO240sTZgPTPoPRlg1NFD3KnI=,iv:cyJvqbLG9wNB6h5i/2Kf/7pRaYeKhsl8uSiHNX8S+i4=,tag:R9RyDNNt++z9ZGJph3DA2g==,type:str]
    version: 3.13.1
