# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kimai-secret
    namespace: kimai
type: Opaque
stringData:
    app-secret: ENC[AES256_GCM,data:o0zophkj9oynkQ==,iv:Ec2RU4jNoukXGspjiCh1Lq5lIwRwI9wlCjoJae35Z+k=,tag:6lyGMy+rWMcGPOTTI2ftgg==,type:str] #ENC[AES256_GCM,data:GAGtBN+MWf+OKHQPLM8zRU43wVsq,iv:0CUmZ7n+t02M6fzhDGBTtqOvPtF/gc4Ow1wYokSN9IE=,tag:7aV5nRUuGFF0LXKYkFXCTw==,type:comment]
    mariadb-root-password: ENC[AES256_GCM,data:7fprhtegPm66/A==,iv:BtSrEsKDLqnEBInW1ybe3A5QfVghWyVoaN61qw8jL+E=,tag:7iTs8CUrpy0g0MGKBCUoOg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:/ZVjYQGDmihQEg==,iv:Srsy/VPo1LUSau1LnR4JQxqQE1GiBSCoTsvRaoXx0QU=,tag:rdTkBmfcX5xwqGlFMEj9pg==,type:str]
    admin-mail: ENC[AES256_GCM,data:kWqTNv3cSBCtkSQX8e3pIOS3,iv:qqzAKLZKnvv9rRCMZy1GHpgKsGedQ57YSMvP6LDq4xU=,tag:EOvHRc0do01pzfpNllA7wA==,type:str] #ENC[AES256_GCM,data:Y14GxFh7NkFmKg==,iv:IuzFvKwBHLfKxleToJl9mLhQv1v7r1V7ihWBSVv5IFs=,tag:un3YoSZSl6y3f84ASJIjfQ==,type:comment]
    admin-pass: ENC[AES256_GCM,data:/k6BXZ9NVeFZsg==,iv:Y6LXcghmhgkGuPqYdPluHevu7cnr3SD/LmnTcGF3RKw=,tag:bp66TRXkmR/OHik2eQNe8g==,type:str]
    #ENC[AES256_GCM,data:jqC9lKnfSot3wVhoQtzGBrWPwxzNo7+rtm96Y7rrP/gZYJzuUFvCwHA4u8/FCSum1owJyTgHhuC9qiTHxTWRwcRviOJ6Ea3SaQ==,iv:UtoVmNwlQBT0S2kKdcw5UNhZu+L7kDE0+x2uIrU6MPE=,tag:qhcBdfUXxguJyiO18HSOeg==,type:comment]
    oidc-client-id: ENC[AES256_GCM,data:jtYk3L6XlFOGgxpJvNLy,iv:uGqlVPmi8/1vpWKzOmws3x+bTdi98XYp4q2cX/WIJbU=,tag:k38kgDX1rWzGzcq0ew0Dmw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:Kyv/SNDMs/vowQ==,iv:J3ldRma3KE/eTl0JjNhaiuYH2tSnLTONHKCFaZcayxI=,tag:kRcyDTaAeXrO5W/zcGvf3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNGdUWDljMEhuM0dqc0hP
            VktSMTZTdXN3VmFhSEs2U284aDgxa0hUbEhNCmRQTHlTVTl3anRFWW0yeWUxT2My
            MjZGdFEzajBvZUVOaStKTFJ6VjlYVHMKLS0tIC93c21zY2NkVTczSVRLaU9GMVNk
            c1dkVHhlanVKTGFjNHQ2ZitXQWdVMVEKBD2p+f2f921hAxRvB8YkxmuCFl/dBFdU
            pCzm6UYX4IAr3+9X8sv7I8caNCELqDmzsz94gWVRyt+GedO78c5EKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:zp0M9SBMXuhFjIcIEEhzgQbN4q1CImywvdpyf91c2EtiVjb9lhkudp6qAsYEGjhDFw4uUN2dE2LZdRzk9V7p2tIC/HpbrZXKZ2VnnN+ZFMdEfon0fo6XA83Eb92jAMEF40TWtU+FbD2y8kZ852aK20gwDbSuzctitGTlZXTg5F4=,iv:No6RLCDMy6P471UhRg1+xG1L1RirWB0Sqf+Y/wr5vWQ=,tag:pMLmmV+c8DZBDx4BuW38QQ==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for mariadb-operator Backup
apiVersion: v1
kind: Secret
metadata:
    name: kimai-backup-s3
    namespace: kimai
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:0cyBbr3D7xtZMA==,iv:oUvTBYl6/YUR2mZ5sGgLw5oAto79slF692pkFuwh9RM=,tag:ux/Vtk0QQagNQmwFLD1nGA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a8ndsVESF5Fogw==,iv:radc+bouxT32e/DOMNJo3AREUVC3CCMpxVl2VrTJZik=,tag:EicYcF2pFQENlvN97X8afw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNGdUWDljMEhuM0dqc0hP
            VktSMTZTdXN3VmFhSEs2U284aDgxa0hUbEhNCmRQTHlTVTl3anRFWW0yeWUxT2My
            MjZGdFEzajBvZUVOaStKTFJ6VjlYVHMKLS0tIC93c21zY2NkVTczSVRLaU9GMVNk
            c1dkVHhlanVKTGFjNHQ2ZitXQWdVMVEKBD2p+f2f921hAxRvB8YkxmuCFl/dBFdU
            pCzm6UYX4IAr3+9X8sv7I8caNCELqDmzsz94gWVRyt+GedO78c5EKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:zp0M9SBMXuhFjIcIEEhzgQbN4q1CImywvdpyf91c2EtiVjb9lhkudp6qAsYEGjhDFw4uUN2dE2LZdRzk9V7p2tIC/HpbrZXKZ2VnnN+ZFMdEfon0fo6XA83Eb92jAMEF40TWtU+FbD2y8kZ852aK20gwDbSuzctitGTlZXTg5F4=,iv:No6RLCDMy6P471UhRg1+xG1L1RirWB0Sqf+Y/wr5vWQ=,tag:pMLmmV+c8DZBDx4BuW38QQ==,type:str]
    version: 3.13.1
