apiVersion: v1
kind: Secret
metadata:
    name: kimai-secret
    namespace: kimai
stringData:
    admin-mail: ENC[AES256_GCM,data:7YDUxvL7emDeqcnEGvY2UP3DZs4P,iv:lpYdiIHF0st3OPFC6Mf0hvLkELjYHH08QOp2hvOEnvs=,tag:Q1jVuiIaDtLSKnCHNodjZw==,type:str]
    admin-pass: ENC[AES256_GCM,data:Mn3hjljwsXvrXMXatS8s7asgjDqQAQ==,iv:gwz9/7JD30YBdG93LD137kJQ7/lZTBD9u7mJEKwMlrI=,tag:WpDtl+Dumz8RuE9tH4FGaQ==,type:str]
    app-secret: ENC[AES256_GCM,data:RMAxSCgNb5/7KBaJIhhRo4/LtyZHzLIKens5Jygq63jStSkusV+Evi42+6P5PjKJcgWX7PQK8OLiMqYkmoYuAg==,iv:Qqik9jjHPVKOIcop8rDqKMsMnWoQt082iKvhMAYUmU0=,tag:zunHklJinnrBSAatr/e/gQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:bToPKCjemfTmkULk69UvwZpVtpt8pYORq6qiNRKfkSA=,iv:ba4F5Qt6N7eSSM23QSPx9cNSonUBbel6fIJ9vB93+MM=,tag:usgTYN/U49k1KTNeWARioQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:4Ojm5Fy3yuB8vDs9V9t0WWtXjC3+eDGugVjhBDZ5100=,iv:5KwybRYOV0O5kvtUu7yiQB8OOhjra3e9MF9YcULOblQ=,tag:KqS3kKOnX3szLgXhp4sHiw==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:vEoO04pkfbTTPQINXKBq,iv:lSPcN0MbNNLHj9Xb/9LD5Y8po5mklyn9WjR62pjZ6/0=,tag:Fpeu3CYiu0F7wzb23gX1LQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:0ufYPZb9AMq6PA==,iv:aCDwKuomw35jeGhzIS+8EBl66mcQgJrIeHcovYmkZVs=,tag:81iRGSE3NDQL8MZS202cmA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbkE2OU1TdXQ3RnpIMVhJ
            dTlrN0FxUGppeTdhRXhPYUMxREgwT3RiaEdNCmRMQy94OHZCV1g3N2haT0Z5N3Zl
            WWN1cHRITHlTUnpoUm01WHNQSG9wOXcKLS0tIE1HelJaT3IzVjZuNHZ6TEprRVdB
            VDl4VXBzZFdwcnlMZmkwNFNpendKYjQKNssSISzTWZyR4x95xzFhfZuMlfvJKyjj
            Piny8yvyBWjt1yI+WNhJJJPAOIvOFGjwb6bfjfZPQXnxFuGMnLPeAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T21:26:15Z"
    mac: ENC[AES256_GCM,data:KJgCGSZyuTJ35vG9tylw2/wLYcT16oOPrgVJ/Y3EhOI+yzF9nBKuBLYo4sX+uPZm2dLkapa2x7BMwJwaq23nxJGqP+sUHCKnUBMQdPBvgHbKSyK9NM8A+qFL8qf0vPhhjq6AM+5y40lsGiM5FF/7AN/8PULjVKoVnIkmWyUgaNI=,iv:2h7zW0VoQnpKTr4hG5isS3vo+I8+3EGKkHKhZva25bk=,tag:5BziW3FSZWJroatMfQmv8g==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: kimai-backup-s3
    namespace: kimai
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:cInSvaQ2VADMNw==,iv:GHIRnAtOqgkyupYNt2ZsOmFcbA9SIkydEWnMw/mKVDA=,tag:/f+lcdAN8c6leDAV2C4pMQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uGen/xD3G708Yw==,iv:wcKqQKKN86Jwb/Lz8JSd6r11iGIIihZIwY6GmZSNz3I=,tag:THYcsWSeLMwX9KYm16l6+A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbkE2OU1TdXQ3RnpIMVhJ
            dTlrN0FxUGppeTdhRXhPYUMxREgwT3RiaEdNCmRMQy94OHZCV1g3N2haT0Z5N3Zl
            WWN1cHRITHlTUnpoUm01WHNQSG9wOXcKLS0tIE1HelJaT3IzVjZuNHZ6TEprRVdB
            VDl4VXBzZFdwcnlMZmkwNFNpendKYjQKNssSISzTWZyR4x95xzFhfZuMlfvJKyjj
            Piny8yvyBWjt1yI+WNhJJJPAOIvOFGjwb6bfjfZPQXnxFuGMnLPeAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T21:26:15Z"
    mac: ENC[AES256_GCM,data:KJgCGSZyuTJ35vG9tylw2/wLYcT16oOPrgVJ/Y3EhOI+yzF9nBKuBLYo4sX+uPZm2dLkapa2x7BMwJwaq23nxJGqP+sUHCKnUBMQdPBvgHbKSyK9NM8A+qFL8qf0vPhhjq6AM+5y40lsGiM5FF/7AN/8PULjVKoVnIkmWyUgaNI=,iv:2h7zW0VoQnpKTr4hG5isS3vo+I8+3EGKkHKhZva25bk=,tag:5BziW3FSZWJroatMfQmv8g==,type:str]
    version: 3.13.1
