apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc
    namespace: argocd
    labels:
        # Pflicht, damit argocd-server $argocd-oidc:... aus argocd-cm aufloest.
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:goRI1fQYGSQGEtkvstKl6v30w7oE5H+Wt/3rCxfM4CbusPgC42WJy1E6YF/hZRAy0xx4ClZVgVTm6fKRulxXRPQ27tmVoBkwY4x2MmI6LUJRC40O0Xk=,iv:Hk+CXsVCACRTn2zm3y6590wPqeEGw9Hh5XdSbMlJObY=,tag:Qj3tOsOie+0OtSdMQNl0EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5V2g1MmhDaUZoQWhObmZ6
            UGNDbDQ4K1kzOURLWTRweUZXWEpidlZUMERrCjhhbzhpN2lidGJod3BNakd4T0Nq
            SHVCdHM1UEYrTHdmakFIVzUrVTgxMHcKLS0tIEtmNTdBSFVCa0J6VG1Qcy9ZaHkv
            N3QrQURoZzJTaFVOZFFrWmlOeWxoZ0EKkJDT3SonqtbLKRBUWaYHB+1IdRQQLo5+
            PXo054qnIlsd6Xl+Jur+1RH/FCzdX4lmUIrkyUmmueu9CRVYuVixJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T15:35:24Z"
    mac: ENC[AES256_GCM,data:zevFjeG9qImWDkkDTKPf2rQ6hgOv68CUo1GoJna+VnhUYxu3y2hMC5aSvI5Slu1dP8zqKD3mH4fOhy3ZbTD/7sCungRX3sG/lR8fSoFK2UvZDyYQjJCR42r3X+q7srnJSRrxtdO+15UUPqs4HplZ7SblRbUxJ0yWeYl1+zI01CM=,iv:C7nF5yR2hhvlONarl9PPHbt8Yn3Vpw7BZ5S8HVUjuUY=,tag:POIJbSHtw5s3vFzO2tfi6g==,type:str]
    version: 3.13.3
