apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc
    namespace: argocd
    labels:
        # Pflicht, damit argocd-server $argocd-oidc:... aus argocd-cm aufloest.
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:1rULU0feff3sEzJ91CIiLxQipGG0Qc5K8R7106FlADlDLk3eEUdZ51slB0quTSSMf6ju8uc7Bw+kk32vHsLj/r9yrnNg/8aBL6uZshzBA395m9pm/Oc=,iv:fqbVhJBCEbkcODG3P4Zvq4JV9DOK1VeQWJ/9EdkvUEE=,tag:eQeNCoXFTN7QVP16EPVwcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbGs1VEVBcVBueVpLWnlT
            UG15WVc0VWcrM0s2dUJuVERhM2hwMTQ4YUhvCjJqdHlrdmpqOGJ6MDdvcDBNQzVj
            ekRaQ3BsVzVKZG5tMUUvWjh0eXlwOFEKLS0tIDBmWURaRXdGWTZIdHd2blRncnJK
            RzE3QStJYmlUc1lzV3N0dEVlZzdTVWMK/SKnd19b87E68yeUIGia8DY90zmX8eDB
            Cnk+SiRb/FIVJ3YZ8nTAjoBhtBTPNt/QgxfJVhOZt5M3DDdbgfxYjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT2ZYZGJ3czJValJQUjEr
            dEhEUlRuNVltYUEvTXpkeDhlcnZEM3Q3cjJJCkpZQ3VjbWNOOEp5U0RJNWNZRmlX
            Nk16TDB0ZzBVZG5FTityeUlIdUlYd3cKLS0tIDNub3lkVHJDVlNNaWxrMEg3TGs0
            K2x4enB3V1ZnZVF4aHBVcTVVODRraEEKtNQFHQBUyRoFYhDS9zBiudtcY00xOU9v
            aUEBPciQzWLmxvHJfLhXZV3EAf7EBr8OCgM1ukuDT6wQy19tVeBveA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T10:15:34Z"
    mac: ENC[AES256_GCM,data:rrApCcpuUW+fzS264yCRipao7OBVANuzKkiLkYwR6k6KWRLo5dpS8nhHbFW633NoQUaoJn9WRt+x0IGzW+rKenC5Rx9V+gjlMiIqd28iPwwc5Rsu8qBn7088WmQidXJJtzurJ1RYjZl+qjFwi9HFl5VUTsWcuf6+M8PlJ7xY9G0=,iv:VStGMUpp9ah0VgskrvY/e/9KSpgIEBF96s5jPl8gEpc=,tag:h2kNxjZCO3XtfFxwZdalUw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flurfunk-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:dK7Y,iv:PLFWKOBzjPuWq4Eqnoru1quDkVbg11PK033eDage8WI=,tag:9ezoNyQ5Lkb04fvKaxoNew==,type:str]
    url: ENC[AES256_GCM,data:lrPZAK2J0Sy6dLp7+ca6whjMl89AtVPwKY0Y2jGQmAYJgMA2SYMvTGtTu82ISNNIyNs=,iv:G59j4Hm8OhMCqLLGhOiKbVE1skUdaPTczeDctFb5Cbk=,tag:ueAge7jx5r7k79p69ZRXmg==,type:str]
    username: ENC[AES256_GCM,data:UcdDav+j6wRHF2wSErxvXtft24+8,iv:jJ/p/9siz7mYL+vUHbjuBGMrjX8pVO2K08vRAixDLOU=,tag:pFmeI20B276jrOxx5iSD9g==,type:str]
    password: ENC[AES256_GCM,data:HRF46J7cAW2U5Be6EU9rUEFVghFyxgHaJQ==,iv:UPdZAVOXSjot6dPhhFzibLVKITBJOIQ/n1n+Vq4XWNw=,tag:vsAz+NRAVFwF2uRZZNaing==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbGs1VEVBcVBueVpLWnlT
            UG15WVc0VWcrM0s2dUJuVERhM2hwMTQ4YUhvCjJqdHlrdmpqOGJ6MDdvcDBNQzVj
            ekRaQ3BsVzVKZG5tMUUvWjh0eXlwOFEKLS0tIDBmWURaRXdGWTZIdHd2blRncnJK
            RzE3QStJYmlUc1lzV3N0dEVlZzdTVWMK/SKnd19b87E68yeUIGia8DY90zmX8eDB
            Cnk+SiRb/FIVJ3YZ8nTAjoBhtBTPNt/QgxfJVhOZt5M3DDdbgfxYjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT2ZYZGJ3czJValJQUjEr
            dEhEUlRuNVltYUEvTXpkeDhlcnZEM3Q3cjJJCkpZQ3VjbWNOOEp5U0RJNWNZRmlX
            Nk16TDB0ZzBVZG5FTityeUlIdUlYd3cKLS0tIDNub3lkVHJDVlNNaWxrMEg3TGs0
            K2x4enB3V1ZnZVF4aHBVcTVVODRraEEKtNQFHQBUyRoFYhDS9zBiudtcY00xOU9v
            aUEBPciQzWLmxvHJfLhXZV3EAf7EBr8OCgM1ukuDT6wQy19tVeBveA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T10:15:34Z"
    mac: ENC[AES256_GCM,data:rrApCcpuUW+fzS264yCRipao7OBVANuzKkiLkYwR6k6KWRLo5dpS8nhHbFW633NoQUaoJn9WRt+x0IGzW+rKenC5Rx9V+gjlMiIqd28iPwwc5Rsu8qBn7088WmQidXJJtzurJ1RYjZl+qjFwi9HFl5VUTsWcuf6+M8PlJ7xY9G0=,iv:VStGMUpp9ah0VgskrvY/e/9KSpgIEBF96s5jPl8gEpc=,tag:h2kNxjZCO3XtfFxwZdalUw==,type:str]
    version: 3.13.3
