apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc
    namespace: argocd
    labels:
        # Pflicht, damit argocd-server $argocd-oidc:... aus argocd-cm aufloest.
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:qWqNm4pNjkOsdbLHDnQR5N6Ztm95JSKu6wnoe6tMDHM8MUDLaYE6YK0/1aCLqH4NXsTrkC+Q4a+meJMJ4a8NN4y2JWFT5Q2PYe3C9ivYDeewItRMoq4=,iv:Ka0wxwth4QNmYeThaAcXPa8JaTTYisjOp7Yp78kP/Jw=,tag:2p5f3hyyx38PZq0Vm7R4IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdThYd3NGR0pHSTBCSUtT
            N3YvU3RSUExRVDdjR204ZGhMMlVEeWtTcEZ3CkJ3T1lMazZ5MVhKalhFeU1KM1N5
            WXYrTHlRa3E1bU1SYkRGR0FTTWJVNTAKLS0tIEVmQjZNTVBna0E5TlNBZkhHai9F
            c2xXRUFhSVNCOGpYR3JZdXhWU0lvMWMKBKdfEt0VFehemMMi40P3rlqn+tWcrevF
            2oT0HQxJDRdzojyZcIAz4f//p54CHrrp6tbJY7fwRG1BROTsETpG3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHJxZ3ROWTBRZDk0UEQ4
            eXEydWF4a1pkbkJQN29SR3l5d1FESUJKcEVZCmMyS3BKVTdOUXpUUDB2UStvQ210
            RGZ1WUZIaXVDck1HMTlQblpEL2YvRXMKLS0tIDhjTDFtY3ZieFFHaW4zY3dFYVRw
            VU5lanBtbytWSEgxTXl3cmVhODdQa2cKUUl/tlSveUdOQR4AfK2zXENTT6lG8KAA
            Lp6LZUZMrI/9vYxEY8dupFI/HKbtk3nJbp8qGhR448ri02WmR4GkFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:10Z"
    mac: ENC[AES256_GCM,data:OvghRPUjffOsrNinyYEhXRxAwKehvkKg2vuASeD1e99r1mu6dd+6hA4l9m2VFqwD/lWNoP7q+62yyS2QLagYkB492Ixaapotlju2W+MQLiDxooQ7LJSqlh4V6MrOnUk35Zjkbesp9wqlEl7t6aW6uKCnS10SksjPWzev6WhcRSo=,iv:Rqgx5I8r8cnxJZQVDHy55u+0cGOD7U007I4u+jZkkjQ=,tag:+Of6/AjSQEsj+xNTSmQRgg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flurfunk-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:ckAn,iv:AOdvgt+N4yqoBuaKyShlpOWtgMtZ4WrYVg8SJAiqkwM=,tag:8inFyrlsPvei521jGTwhjA==,type:str]
    url: ENC[AES256_GCM,data:0ueZ8U0V5bTj01e95PPKZc2cJFMs+PvVz5Lk0h0Ec8bTyEb1q2C/beQneQLYibWX/Ps=,iv:ItVks8HkgDWkx/jWHrHbIb8HXd2+BTvU4sC+IHktxEg=,tag:UPcK7rwgIbPNWUoljnpGaQ==,type:str]
    username: ENC[AES256_GCM,data:b+0MhWHi6GtypUis9qsMifMevB0L,iv:LU11vYWobWba5gUdW2kRWnS7huE/JuJci4xpPtzrQVo=,tag:CzocPc4JwZUlfKTfiTVNbw==,type:str]
    password: ENC[AES256_GCM,data:OYGWEWO3ZtVx7pZ0Ecyr4o1/oIvwejm7jA==,iv:2kbckSyYyjo53YBWW81uAYN6R8qhh7RDrJyzSXUZTSE=,tag:hKURWZvXazOEBQ4/neROHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdThYd3NGR0pHSTBCSUtT
            N3YvU3RSUExRVDdjR204ZGhMMlVEeWtTcEZ3CkJ3T1lMazZ5MVhKalhFeU1KM1N5
            WXYrTHlRa3E1bU1SYkRGR0FTTWJVNTAKLS0tIEVmQjZNTVBna0E5TlNBZkhHai9F
            c2xXRUFhSVNCOGpYR3JZdXhWU0lvMWMKBKdfEt0VFehemMMi40P3rlqn+tWcrevF
            2oT0HQxJDRdzojyZcIAz4f//p54CHrrp6tbJY7fwRG1BROTsETpG3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHJxZ3ROWTBRZDk0UEQ4
            eXEydWF4a1pkbkJQN29SR3l5d1FESUJKcEVZCmMyS3BKVTdOUXpUUDB2UStvQ210
            RGZ1WUZIaXVDck1HMTlQblpEL2YvRXMKLS0tIDhjTDFtY3ZieFFHaW4zY3dFYVRw
            VU5lanBtbytWSEgxTXl3cmVhODdQa2cKUUl/tlSveUdOQR4AfK2zXENTT6lG8KAA
            Lp6LZUZMrI/9vYxEY8dupFI/HKbtk3nJbp8qGhR448ri02WmR4GkFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:10Z"
    mac: ENC[AES256_GCM,data:OvghRPUjffOsrNinyYEhXRxAwKehvkKg2vuASeD1e99r1mu6dd+6hA4l9m2VFqwD/lWNoP7q+62yyS2QLagYkB492Ixaapotlju2W+MQLiDxooQ7LJSqlh4V6MrOnUk35Zjkbesp9wqlEl7t6aW6uKCnS10SksjPWzev6WhcRSo=,iv:Rqgx5I8r8cnxJZQVDHy55u+0cGOD7U007I4u+jZkkjQ=,tag:+Of6/AjSQEsj+xNTSmQRgg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: tonu-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:saQp,iv:k4Db9jxxnPPjYZEC6qTRFiAPhCp4oeSgkE0ThqE/HwI=,tag:WwKXg+Jnk7bi1B5G332mAQ==,type:str]
    url: ENC[AES256_GCM,data:7LfIaG75Uy7Cq/Fxuhu2mR7MAh3N+pPdCbjM0BVxYbCUIhvypLEvYhFV1SsWTg==,iv:g+IzAMbnpZln2yYLPEbNxBX9MZDgPyO4qrUNzJOkrdQ=,tag:uJ7AtF1IesOcwKFzFTpIHw==,type:str]
    username: ENC[AES256_GCM,data:L/4tnubE+tBDWAYCMq5WW3SXU6Gs,iv:jdRhEuF3uGjvl2iXAD4f+G5zD25pVPVs1aBrZR3Rgzw=,tag:pajZyJeBtdWxqMnQIG/Nrg==,type:str]
    password: ENC[AES256_GCM,data:83AFImo55nLfvieT8oaJexZTFA6wY7mceA==,iv:XqOwQUgU7yEY/bID9Cy9n56cxL1g/7om8UCk8KLA3go=,tag:wG/IPIjydnTukPXO3y+tLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdThYd3NGR0pHSTBCSUtT
            N3YvU3RSUExRVDdjR204ZGhMMlVEeWtTcEZ3CkJ3T1lMazZ5MVhKalhFeU1KM1N5
            WXYrTHlRa3E1bU1SYkRGR0FTTWJVNTAKLS0tIEVmQjZNTVBna0E5TlNBZkhHai9F
            c2xXRUFhSVNCOGpYR3JZdXhWU0lvMWMKBKdfEt0VFehemMMi40P3rlqn+tWcrevF
            2oT0HQxJDRdzojyZcIAz4f//p54CHrrp6tbJY7fwRG1BROTsETpG3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHJxZ3ROWTBRZDk0UEQ4
            eXEydWF4a1pkbkJQN29SR3l5d1FESUJKcEVZCmMyS3BKVTdOUXpUUDB2UStvQ210
            RGZ1WUZIaXVDck1HMTlQblpEL2YvRXMKLS0tIDhjTDFtY3ZieFFHaW4zY3dFYVRw
            VU5lanBtbytWSEgxTXl3cmVhODdQa2cKUUl/tlSveUdOQR4AfK2zXENTT6lG8KAA
            Lp6LZUZMrI/9vYxEY8dupFI/HKbtk3nJbp8qGhR448ri02WmR4GkFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T19:19:10Z"
    mac: ENC[AES256_GCM,data:OvghRPUjffOsrNinyYEhXRxAwKehvkKg2vuASeD1e99r1mu6dd+6hA4l9m2VFqwD/lWNoP7q+62yyS2QLagYkB492Ixaapotlju2W+MQLiDxooQ7LJSqlh4V6MrOnUk35Zjkbesp9wqlEl7t6aW6uKCnS10SksjPWzev6WhcRSo=,iv:Rqgx5I8r8cnxJZQVDHy55u+0cGOD7U007I4u+jZkkjQ=,tag:+Of6/AjSQEsj+xNTSmQRgg==,type:str]
    version: 3.13.3
