apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
spec:
  rootPasswordSecretKeyRef: # CRD-Feldname: *SecretKeyRef, nicht *SecretRef
    name: wordpress-db
    key: mariadb-root-password
  username: wordpress
  passwordSecretKeyRef:
    name: wordpress-db
    key: mariadb-password
  database: wordpress
  storage:
    size: 5Gi
    storageClassName: ceph-rbd # CHANGE ME
  replicas: 1
  metrics:
    enabled: true
