apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
stringData:
    db-password: ENC[AES256_GCM,data:YY0SPuxAG7nBx+sxwAZQwxUM4ZZVg+LXcdeSFIO1uOk=,iv:I2cD+I9t+EL4CnFAnCwFXGp6xuJgGAOMAaS/nLvK5f4=,tag:hz3Mr04FzIlhQGtf3N8pVA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:i7wMNK0ihfHqdoP0NvDkna6ChAAfUqRm+Crue8M5cr8=,iv:H1kCsSvJ0ulZ+vUfCLWLocUG/lc2FGWFWE/vQDkLF0o=,tag:quD2Qk1qps/8e1U4A/6YQA==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:tDt7ar5Bftnj0v2qDGSdEFTV62TRJVj1mm8SgCGmXi8=,iv:8jPE+FR8Ml5goltXhZFIanKPvoNxM1yKEBLLir8Kavw=,tag:uUSHGbZ2iUQQ793bzJ1nRQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YlR6ZzROUHNQdDFwTlBC
            MGx3Ky9WNG1RYmprYVlZN0VjRHUvR0s1OFc0CkdvN3FHbmJyZ1VFQzl2Mm03SnFi
            NVRPekQzTk9hTkZwZ3RXNGNXM2tXT2sKLS0tIGxaTVhZV3I2RjUxTmJHbFRtemN1
            SHduS2hUSWh5VGgwbGp0TzlaRm5QclUKpC6XvliVezGLqNtmAh+qpwFp5BIDVwG/
            vAiXIoIfz8YN37YLDPf4WHlDmH/CKY/EXkrNtnlBIPpsYJpZ3YPmGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:14:26Z"
    mac: ENC[AES256_GCM,data:Yu0WrithTBGktcGLDyFhZ5n9sN+Dx8gYHcLu6lTlhEmkWS6zBGrshL9FNT4brWqsik1ty71/eesUa+Yz9PvpZk222vZcqTLEc2jDdw2Eazi0ohSCh1m1GpNtcNxInMVN/D+Q9QZrMGwhMQF6nKBygEUOevtIwxD+dioW0rzLSp4=,iv:isxq1P5xHLnlidTSFU7CyxELWF1QwXzvuXBVFtp5zhc=,tag:NL7qtkmRyNCVs6SoY90ifQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-admin
stringData:
    wordpress-password: ENC[AES256_GCM,data:14RZZ3VpHKX6zNcWwmGdZv7/xdv5Hg==,iv:Gegw3O/wZzieLbV0b8c4qX5fsEFC7upyC6eWqRhXvQ4=,tag:myrwnNmI7T/Pss6nqUhNoA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YlR6ZzROUHNQdDFwTlBC
            MGx3Ky9WNG1RYmprYVlZN0VjRHUvR0s1OFc0CkdvN3FHbmJyZ1VFQzl2Mm03SnFi
            NVRPekQzTk9hTkZwZ3RXNGNXM2tXT2sKLS0tIGxaTVhZV3I2RjUxTmJHbFRtemN1
            SHduS2hUSWh5VGgwbGp0TzlaRm5QclUKpC6XvliVezGLqNtmAh+qpwFp5BIDVwG/
            vAiXIoIfz8YN37YLDPf4WHlDmH/CKY/EXkrNtnlBIPpsYJpZ3YPmGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:14:26Z"
    mac: ENC[AES256_GCM,data:Yu0WrithTBGktcGLDyFhZ5n9sN+Dx8gYHcLu6lTlhEmkWS6zBGrshL9FNT4brWqsik1ty71/eesUa+Yz9PvpZk222vZcqTLEc2jDdw2Eazi0ohSCh1m1GpNtcNxInMVN/D+Q9QZrMGwhMQF6nKBygEUOevtIwxD+dioW0rzLSp4=,iv:isxq1P5xHLnlidTSFU7CyxELWF1QwXzvuXBVFtp5zhc=,tag:NL7qtkmRyNCVs6SoY90ifQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-backup-s3
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:sngDjy4Pal/mLA==,iv:XfNCQbpQ31DtQVPdIXSIOfbr8bdf3F5PZNyNTGwyKs8=,tag:NnwrznYoP53SepZc+HJjqA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tOwQAtMzeuKXRQ==,iv:fIItvjZWN51NvbwuyBzxCoFsvKLCUkWwMLGtbi67LcM=,tag:HkJG18/zYqIC+hVpzvdnMA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YlR6ZzROUHNQdDFwTlBC
            MGx3Ky9WNG1RYmprYVlZN0VjRHUvR0s1OFc0CkdvN3FHbmJyZ1VFQzl2Mm03SnFi
            NVRPekQzTk9hTkZwZ3RXNGNXM2tXT2sKLS0tIGxaTVhZV3I2RjUxTmJHbFRtemN1
            SHduS2hUSWh5VGgwbGp0TzlaRm5QclUKpC6XvliVezGLqNtmAh+qpwFp5BIDVwG/
            vAiXIoIfz8YN37YLDPf4WHlDmH/CKY/EXkrNtnlBIPpsYJpZ3YPmGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:14:26Z"
    mac: ENC[AES256_GCM,data:Yu0WrithTBGktcGLDyFhZ5n9sN+Dx8gYHcLu6lTlhEmkWS6zBGrshL9FNT4brWqsik1ty71/eesUa+Yz9PvpZk222vZcqTLEc2jDdw2Eazi0ohSCh1m1GpNtcNxInMVN/D+Q9QZrMGwhMQF6nKBygEUOevtIwxD+dioW0rzLSp4=,iv:isxq1P5xHLnlidTSFU7CyxELWF1QwXzvuXBVFtp5zhc=,tag:NL7qtkmRyNCVs6SoY90ifQ==,type:str]
    version: 3.13.1
