apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
stringData:
    userID: ENC[AES256_GCM,data:4/ad6p4VdyDoYg==,iv:wozyA6nnaFWTkRLPU9iGBwxd2YaZg2l+oPaR6uss/Nw=,tag:qZ8dKb6rqxXv7LKQzm/QCg==,type:str]
    userKey: ENC[AES256_GCM,data:eH5DURrk0NdR4nwsIx4De5Cc4cG9KHef8y917/Py13072fECj6ZfsA==,iv:9r6G5Mq8jXR941h2TyTRMJzoIaXsaaRiww4NFvV7MiA=,tag:tpr4SwHx4wq395ZStu4tdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzejNKYUhhcTJSRXBsYm54
            Y1gycUQ0bzVCWUVXKzVkSWZxSmQ1TXdMZG5NCjZIbUpqWFIxcGdMZk5wUVo4cHh6
            TjFRekNCREE4TEZrbGJPRXRuNitGbzQKLS0tIFBKRGRFNzRIazZKcllFRFp4bThD
            cmRUZjNmSlVWbWtEN3Y2b0o2VXdoV1UK4urKK1nTYUwsmibz4zsQZZxJPnv5wxkv
            VcU9BEi8/4MfM/UrPzqD05jsR1k+dyUYJ6g5NQB50457nyboXgvpTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T09:04:00Z"
    mac: ENC[AES256_GCM,data:5A1o+ovCLLk6poUk34llEHOoF0kjCvAY4XRQ+UgdVO4r/P8SU6PL3pYb8FSEN64iBg6BWpnfHk+RT5Ylk2Rh99f1qdhcVPD8cvCTG6SXSzqOUnjOTUUuNtzv9sxmgExD4kPnOPeGhIVBNuTTnNvocz6dwk8h0vBiT9fjUSq8uLs=,iv:E6WZBX8YM69BqVJ2eophV1459JrAzi+h5EoJgYeQwb8=,tag:bmZQRh82/BsbjhUpICbFDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:vaUEJd31r4eTCV+fwGvRTEY=,iv:0LXixpRvEGwidDoDnyMbVjaq3ngkBycR6d1PUInJIQU=,tag:aV/xcgjNEKVZQiric9Duug==,type:str]
    userKey: ENC[AES256_GCM,data:g8JE7erMBVMyanS3jDUs1qZeZSzgtNVjCRakl18IiwG1jLvRqztPjA==,iv:y8pmmqLBB5pOte9+iTm3/YdsFTeBwMgyIaK1SZqNqKs=,tag:uJMRBnTOxs8kEd2b5GLx0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzejNKYUhhcTJSRXBsYm54
            Y1gycUQ0bzVCWUVXKzVkSWZxSmQ1TXdMZG5NCjZIbUpqWFIxcGdMZk5wUVo4cHh6
            TjFRekNCREE4TEZrbGJPRXRuNitGbzQKLS0tIFBKRGRFNzRIazZKcllFRFp4bThD
            cmRUZjNmSlVWbWtEN3Y2b0o2VXdoV1UK4urKK1nTYUwsmibz4zsQZZxJPnv5wxkv
            VcU9BEi8/4MfM/UrPzqD05jsR1k+dyUYJ6g5NQB50457nyboXgvpTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T09:04:00Z"
    mac: ENC[AES256_GCM,data:5A1o+ovCLLk6poUk34llEHOoF0kjCvAY4XRQ+UgdVO4r/P8SU6PL3pYb8FSEN64iBg6BWpnfHk+RT5Ylk2Rh99f1qdhcVPD8cvCTG6SXSzqOUnjOTUUuNtzv9sxmgExD4kPnOPeGhIVBNuTTnNvocz6dwk8h0vBiT9fjUSq8uLs=,iv:E6WZBX8YM69BqVJ2eophV1459JrAzi+h5EoJgYeQwb8=,tag:bmZQRh82/BsbjhUpICbFDw==,type:str]
    version: 3.13.3
