# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
# Ceph-Client für ceph-csi-rbd (client.kubernetes am PVE-Ceph).
apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
stringData:
    userID: ENC[AES256_GCM,data:1rtOBolrPtWy3A==,iv:is39Ns+5r8KBQAKP6EMJ9zSXrZ3NMdNuWCTdhcanBQE=,tag:xGVfS8kTGcC4OhtouKZCRQ==,type:str]
    userKey: ENC[AES256_GCM,data:/tA1aZi/9EQTMuMgRucYtZtCM476j7BgrXupJrL3xDo8FP6xxSY3kQ==,iv:EH4P27YwwNvCmyrh40pke3Rd5iHnFVs2TY4ozVyTe1s=,tag:PLWZUN+gbMPaZnBQUVufbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YldzSTg0aHRUb2ZHYnNP
            ME5GUExCbUcrN2xlK1U3Z3IwcndyaHVFd0JJCk1KVmVUcEI4cUZTMU1aTFlXZE9z
            aEJOYnhZa2FLeUxrQkYyOW9HazlCMkkKLS0tIFBzTGJsOEhSTTFyQnowR2h4eVBm
            YnhjQ0RPR2xCeUtTbVVFRW10ejJpMDAK40omMCA6HR5dC+v/9UX8UGAZEuqU5i6/
            vm9Hm1secpYRMThlbdI2xSRRDSdWse++Ni7dcyUXEEHbZdPacwfvsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T14:09:43Z"
    mac: ENC[AES256_GCM,data:jsq9MxZpZRWnSfgi1kVvhYNL1sK2gEGIAmQMHv57M0OvAfeIQzaj6hu6+FgyOrejpk6KEhjtxCZ2tEUUQXrJLTmuTEzba1dEDu4/ZxcvW0E34lKqRrfIus+1JdxskrZ6HiOXz3JGzCFNePlzY2VwTPsnmCVijGOUwlj8c6FOlTU=,iv:ikfUSg9HPt0hwnRzLgnrtkjFmtmwknpgv3F/93pvs74=,tag:Bar38JwLRusubG8oAnge6w==,type:str]
    version: 3.13.1
