apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
stringData:
    userID: ENC[AES256_GCM,data:4/ad6p4VdyDoYg==,iv:wozyA6nnaFWTkRLPU9iGBwxd2YaZg2l+oPaR6uss/Nw=,tag:qZ8dKb6rqxXv7LKQzm/QCg==,type:str]
    userKey: ENC[AES256_GCM,data:eH5DURrk0NdR4nwsIx4De5Cc4cG9KHef8y917/Py13072fECj6ZfsA==,iv:9r6G5Mq8jXR941h2TyTRMJzoIaXsaaRiww4NFvV7MiA=,tag:tpr4SwHx4wq395ZStu4tdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQndGK1FrWkZ4KzFZQVFx
            N3QrSWtOOHVjcXJXQTkweHJoMUlsSjRjdWtJClJhdXNNTGtCSlZxbVJxc3dPbURz
            d2RVYXhhOVBmaEhYNUc5aUFWMjI5ckEKLS0tIGVOK1NGeFBwcnppZmVKc3hZVnI5
            b1hzQytVTWhoQ1lNVzJsQXFEbU54Tk0KeCqaMlfz9HusrCO774TTAU28x9fIJbdR
            zMlRw2+HQrm5T4GYrrw7Ue5nYhfb0BUSpOapmOobsespUJEZOX3bjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXREFMUGNDUkFNODVqKzll
            MVZlU1JkRUM3NVc1M0RIUFIwZlMrTENMNEJRCjJFYXhpTGdFL0hVOUdKUmJoaTF1
            K0JoYkJzdmhVaUFUWnp3NEMzdVhVL1EKLS0tIDdLcnUvQmVoYjhjNS9aVHZSNito
            U3dGaEk2RUY4M1hrNHVSOVp0eUtoeWMKCPXt/iRT/DA3N+DO50TWwEL3hs9oSjO4
            Zauwarmok8dLZYaEaIfVcaibn2HzXDyiRa2UaylNB4eIwcX7Ndtd1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T09:04:00Z"
    mac: ENC[AES256_GCM,data:5A1o+ovCLLk6poUk34llEHOoF0kjCvAY4XRQ+UgdVO4r/P8SU6PL3pYb8FSEN64iBg6BWpnfHk+RT5Ylk2Rh99f1qdhcVPD8cvCTG6SXSzqOUnjOTUUuNtzv9sxmgExD4kPnOPeGhIVBNuTTnNvocz6dwk8h0vBiT9fjUSq8uLs=,iv:E6WZBX8YM69BqVJ2eophV1459JrAzi+h5EoJgYeQwb8=,tag:bmZQRh82/BsbjhUpICbFDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:vaUEJd31r4eTCV+fwGvRTEY=,iv:0LXixpRvEGwidDoDnyMbVjaq3ngkBycR6d1PUInJIQU=,tag:aV/xcgjNEKVZQiric9Duug==,type:str]
    userKey: ENC[AES256_GCM,data:g8JE7erMBVMyanS3jDUs1qZeZSzgtNVjCRakl18IiwG1jLvRqztPjA==,iv:y8pmmqLBB5pOte9+iTm3/YdsFTeBwMgyIaK1SZqNqKs=,tag:uJMRBnTOxs8kEd2b5GLx0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQndGK1FrWkZ4KzFZQVFx
            N3QrSWtOOHVjcXJXQTkweHJoMUlsSjRjdWtJClJhdXNNTGtCSlZxbVJxc3dPbURz
            d2RVYXhhOVBmaEhYNUc5aUFWMjI5ckEKLS0tIGVOK1NGeFBwcnppZmVKc3hZVnI5
            b1hzQytVTWhoQ1lNVzJsQXFEbU54Tk0KeCqaMlfz9HusrCO774TTAU28x9fIJbdR
            zMlRw2+HQrm5T4GYrrw7Ue5nYhfb0BUSpOapmOobsespUJEZOX3bjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXREFMUGNDUkFNODVqKzll
            MVZlU1JkRUM3NVc1M0RIUFIwZlMrTENMNEJRCjJFYXhpTGdFL0hVOUdKUmJoaTF1
            K0JoYkJzdmhVaUFUWnp3NEMzdVhVL1EKLS0tIDdLcnUvQmVoYjhjNS9aVHZSNito
            U3dGaEk2RUY4M1hrNHVSOVp0eUtoeWMKCPXt/iRT/DA3N+DO50TWwEL3hs9oSjO4
            Zauwarmok8dLZYaEaIfVcaibn2HzXDyiRa2UaylNB4eIwcX7Ndtd1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T09:04:00Z"
    mac: ENC[AES256_GCM,data:5A1o+ovCLLk6poUk34llEHOoF0kjCvAY4XRQ+UgdVO4r/P8SU6PL3pYb8FSEN64iBg6BWpnfHk+RT5Ylk2Rh99f1qdhcVPD8cvCTG6SXSzqOUnjOTUUuNtzv9sxmgExD4kPnOPeGhIVBNuTTnNvocz6dwk8h0vBiT9fjUSq8uLs=,iv:E6WZBX8YM69BqVJ2eophV1459JrAzi+h5EoJgYeQwb8=,tag:bmZQRh82/BsbjhUpICbFDw==,type:str]
    version: 3.13.3
