apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud-yealink-phonebook
resources:
  - namespace.yaml
  - workload.yaml
  - ingress.yaml

configMapGenerator:
  - name: nextcloud-yealink-phonebook-code
    files:
      - app.py

generators:
  - ./secret-generator.yaml
