apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-yealink-phonebook
    namespace: nextcloud-yealink-phonebook
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:PqOYehHowl/uf7EXZEfpGsHn/B15,iv:oEp5FGE/3rWE/LakLkVkm47kaLxgMozJP0NRt7wj0Yc=,tag:OZq7s21XVVdKZVHNAXETvQ==,type:str]
    nextcloud-app-password: ENC[AES256_GCM,data:xN0dPIY6yDHQhGBqQ+jY9Ce9g/I163UBEvRFB46W/2tGVAceAHG5/hI0lVs4lHx9/HT+PLO+abVAVAtjoqh79AO4n2Rxp7qe,iv:w9jqDz50vafQjyNDUUxa9xEV+dmqMPxwNbF9PVyH9u8=,tag:px7a5yNs6ElfUjnS1kRTww==,type:str]
    phonebook-token: ENC[AES256_GCM,data:gEz3tWOzXHc5qTPG2E4E6UPee2U5e2ep2PjF1R1Z/CkWPbuY3we4rFAAaUT32YnGCNMzsWKw8FZdBNlYPAGA1w==,iv:FBWHv9AbnWRO6pD+a5mb6xepljLcHh0AnyjUkaQRGQ0=,tag:08SNn0e0qKPiwwHnkktbxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ1NPSnBMQld2SUZFZkN5
            b0NHYWFQaHRhY3h1aU81M3c0eVlrenMrK3pVCm5pRkZrU3BxUy96b0lGS0QyNk1w
            RjhKQjBYOCtHcU1vSk5mZjZTVWt0NzAKLS0tIFYyL2Y4MlVqSDRkWGZzdndsdHBL
            anBpazFNaWNVbXNCangwWHRjSlpIMTAK9nVJmcHQ2FVvbg6QfbqhVHBZ2etz8N0f
            3rI6A/vUDl3b9kaYZmNyEpD2WWpbpa501wvHPh628nAbeaasP/Xopg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T13:12:05Z"
    mac: ENC[AES256_GCM,data:3bI4Lh7HokQTBNYlOAE9Vq6chhmX2BnLnTYwtc7PC36dnPeyNxM1T2SBKKDgQV4qoAuZvite4wr0xQc/X/IqrAOMg+QM7CFeCkJkf07dLGCrXMQ0cnZK2WHZf10FRsLlNKolr0ErWt7uap3HgN6Y9Ck0JO5Be/tR5WeDFsPzxkQ=,iv:/HYRNPFVgzcUsPzpaWXDLd7+78wG/kJO1Gt9dvPUBjE=,tag:oxj04BnXeAqi2HS8AQ5XvA==,type:str]
    version: 3.13.3
