apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-yealink-phonebook
    namespace: nextcloud-yealink-phonebook
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:PqOYehHowl/uf7EXZEfpGsHn/B15,iv:oEp5FGE/3rWE/LakLkVkm47kaLxgMozJP0NRt7wj0Yc=,tag:OZq7s21XVVdKZVHNAXETvQ==,type:str]
    nextcloud-app-password: ENC[AES256_GCM,data:3ILO5kdmp5EO8KZps59/ZI5QxAVBDh+84+loEVY=,iv:OtcjLYZUOIXQlDnGKyUFgtQY9kaJ2bYU9aJJZU/myRI=,tag:uHZwJMufp85kFprZpubcVQ==,type:str]
    phonebook-token: ENC[AES256_GCM,data:gEz3tWOzXHc5qTPG2E4E6UPee2U5e2ep2PjF1R1Z/CkWPbuY3we4rFAAaUT32YnGCNMzsWKw8FZdBNlYPAGA1w==,iv:FBWHv9AbnWRO6pD+a5mb6xepljLcHh0AnyjUkaQRGQ0=,tag:08SNn0e0qKPiwwHnkktbxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ1NPSnBMQld2SUZFZkN5
            b0NHYWFQaHRhY3h1aU81M3c0eVlrenMrK3pVCm5pRkZrU3BxUy96b0lGS0QyNk1w
            RjhKQjBYOCtHcU1vSk5mZjZTVWt0NzAKLS0tIFYyL2Y4MlVqSDRkWGZzdndsdHBL
            anBpazFNaWNVbXNCangwWHRjSlpIMTAK9nVJmcHQ2FVvbg6QfbqhVHBZ2etz8N0f
            3rI6A/vUDl3b9kaYZmNyEpD2WWpbpa501wvHPh628nAbeaasP/Xopg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T05:54:51Z"
    mac: ENC[AES256_GCM,data:Ml4BdakrjNfmvGLQf4Z7jCBv/diEOAi03AuHNdFAIhTZs0TEoGdr7gd7cICAe6GxK8nkVJW0DYFW/a1RI2/Fy9KtPNPzcUsSSeOwu0Owmqrkv5YDY6j7MVvYRu2kEjXLL8y3lQCNg0Th4iWwt1CLZz8MOOxqfNZ/uVBjKc/ke1U=,iv:+822fR6swd6RY/skpPnokXNGTZIBxChFXMLkn4cPSuk=,tag:popXVApsxSP0fh95RKBm6A==,type:str]
    version: 3.13.3
