apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-yealink-phonebook
    namespace: nextcloud-yealink-phonebook
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:PqOYehHowl/uf7EXZEfpGsHn/B15,iv:oEp5FGE/3rWE/LakLkVkm47kaLxgMozJP0NRt7wj0Yc=,tag:OZq7s21XVVdKZVHNAXETvQ==,type:str]
    nextcloud-app-password: ENC[AES256_GCM,data:3ILO5kdmp5EO8KZps59/ZI5QxAVBDh+84+loEVY=,iv:OtcjLYZUOIXQlDnGKyUFgtQY9kaJ2bYU9aJJZU/myRI=,tag:uHZwJMufp85kFprZpubcVQ==,type:str]
    phonebook-token: ENC[AES256_GCM,data:gEz3tWOzXHc5qTPG2E4E6UPee2U5e2ep2PjF1R1Z/CkWPbuY3we4rFAAaUT32YnGCNMzsWKw8FZdBNlYPAGA1w==,iv:FBWHv9AbnWRO6pD+a5mb6xepljLcHh0AnyjUkaQRGQ0=,tag:08SNn0e0qKPiwwHnkktbxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NnlZT2V6Y2NOYW1WRU1P
            UVlHWDRCeXVTb0Zab2thSTBWQ0NaRURVM25RCkszNnhyS1M3aHZyL2wvdDc5WVhi
            VHU5S1F3OS8ySWk0cjA5VlZGay9CaXMKLS0tIFFBek9ZK1dWOE13dVZmbUFDelJK
            U3JGRkRCL0ZNSE41UEVDUzZWaGRISGcKLgiPmS8ZPlet6F4WRfffOOxGV/2S4e50
            FQtE3+DxgomE7kCCz+/wLF/wtqLfoL2qNU9FqNrtOZafHabc7IuadQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ1IwRGNoRWh4Zm93ZjB5
            V3VMQTUzaXBpTEdqK2MxeFF6RVlTV3Rid0JJCkZzMldhbW9SSktCNGYrRi83MTMz
            ME5kR2lpaVRKWjR0VFFFSnU2akVqNHMKLS0tIDZjQ3ZKNXBWblRkVlk1WDNmK2Vt
            eE5VRGpNajRHK2kvYWFFVUZqWXg2RkEKLzjXDApV3UgzhjhdRiD5BTXePc94PDnY
            bi4GCHRvejsfdMUVqH7mGW1F88a/s8QCi+IYwWxxCZ5R87q27elERQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T05:54:51Z"
    mac: ENC[AES256_GCM,data:Ml4BdakrjNfmvGLQf4Z7jCBv/diEOAi03AuHNdFAIhTZs0TEoGdr7gd7cICAe6GxK8nkVJW0DYFW/a1RI2/Fy9KtPNPzcUsSSeOwu0Owmqrkv5YDY6j7MVvYRu2kEjXLL8y3lQCNg0Th4iWwt1CLZz8MOOxqfNZ/uVBjKc/ke1U=,iv:+822fR6swd6RY/skpPnokXNGTZIBxChFXMLkn4cPSuk=,tag:popXVApsxSP0fh95RKBm6A==,type:str]
    version: 3.13.3
