apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: matomo-secret
    namespace: matomo
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:qySV0qRx6ad1XUO247kMBhHfJIG4TzoT6t8Dzxd2osc=,iv:vUR2gQG2ul3CExpZzbuYYGEUsK6iUPU04ZK9oQ76ThQ=,tag:IMF6grSYrEci65RYq12zOA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:K/LC9uU4gFtBQNPmyxD+gH5/CJSVNYYti/77tp0gg6U=,iv:P2102w5JRMkIolwNxhSVGa8D2XxEJ8yWoO5AuvZh0wY=,tag:nrT2lN5IhOgWQlwwfEfg2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR216RFZTUjB0bmtUdDNC
            QWphZS8wZTQ0K0pCaG9ORnpXZUZkMXVOWURrCmRWOTlRK2YyV0M0OFZtN1kvcmU3
            QnBoNGJOSFFKdkwxa2JDUm9IUmhwTjQKLS0tIGlIaEJWdzlFWWgrQ3B6ZHA0ZUNi
            MmR5SlVLaTY0VUt6Ui9PN096TW5GUWsKLVqBMQnas4L8TChVUgXI6jOrAKpvG6Sz
            oBvu7kDFGWTldSKpil+/49X3sX0l6JelOFjCuY62Ui0wTEXAmfuBvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T07:44:07Z"
    mac: ENC[AES256_GCM,data:OXX/A+z1MKJ3IODA1zo9GmhHFs9AgMWaFivH9TFYVVP8bRtUKzC+iyRLeL8FP9ZvhZ5x4VKjHgAfSMZF6sqj5OU6Nw8B/Ju9e3313zaCO7rSE4KWstD4Upopz/F8t/0OXxAMsKeipVRalMTn7IJ201uHkF3qL+iWAfsNiz2THgI=,iv:AWcZ58fWbtIXxmCsfIzYM2j86Xs8N90Bq/jVc4KKHMk=,tag:/tNodG2i3gmjjl3RCLWfaA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: matomo-backup-s3
    namespace: matomo
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:XXxlnextMy9nl/JLHXySFM2K6lfOaN87rdQ=,iv:CUBjzZArOqsidOrthsl9eHy6fiCc9Oi4dDugonhves4=,tag:eJDm8y8gG7J1SMsXVC5sDw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FnXBtf7LDJZjA2nzYj6ZTDXfDJGMmAMRP7kwBIWfbRbSeGWU05AJCJ92Qe4AGmNKIeHsldrEbpjf3DhOD+uXCg==,iv:TiHSSaBu+O3bWFD9FHqd8eHdO0SsTmXyqooIKnNOMsQ=,tag:YDB7NHtymqu1kaTst2pPaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR216RFZTUjB0bmtUdDNC
            QWphZS8wZTQ0K0pCaG9ORnpXZUZkMXVOWURrCmRWOTlRK2YyV0M0OFZtN1kvcmU3
            QnBoNGJOSFFKdkwxa2JDUm9IUmhwTjQKLS0tIGlIaEJWdzlFWWgrQ3B6ZHA0ZUNi
            MmR5SlVLaTY0VUt6Ui9PN096TW5GUWsKLVqBMQnas4L8TChVUgXI6jOrAKpvG6Sz
            oBvu7kDFGWTldSKpil+/49X3sX0l6JelOFjCuY62Ui0wTEXAmfuBvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T07:44:07Z"
    mac: ENC[AES256_GCM,data:OXX/A+z1MKJ3IODA1zo9GmhHFs9AgMWaFivH9TFYVVP8bRtUKzC+iyRLeL8FP9ZvhZ5x4VKjHgAfSMZF6sqj5OU6Nw8B/Ju9e3313zaCO7rSE4KWstD4Upopz/F8t/0OXxAMsKeipVRalMTn7IJ201uHkF3qL+iWAfsNiz2THgI=,iv:AWcZ58fWbtIXxmCsfIzYM2j86Xs8N90Bq/jVc4KKHMk=,tag:/tNodG2i3gmjjl3RCLWfaA==,type:str]
    version: 3.13.3
