apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com
    version: 0.24.1 # renovate: helm
    releaseName: paperless
    namespace: paperless-ngx
    valuesFile: values.yaml
resources:
  - database.yaml
  - cache.yaml
  - backup.yaml

generators:
  - ./secret-generator.yaml
