apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-app
    namespace: paperless-ngx
stringData:
    password: ENC[AES256_GCM,data:JZUWwZ2ubXvvM81Wh5C3H/Cm4eueJhHqn8Re3rn58Ik=,iv:n9Fwr7VVPQcdp8uMNrQgWK/GlsFRn7CnZ9VXwEACwPI=,tag:iV/bmupquw+uHJ+JThbUQw==,type:str]
    username: ENC[AES256_GCM,data:CA9heyO2MEY5,iv:UCl3cb1QjjIdya/5ZwUpImoU0Dm4dQrslJr9bHiXjEA=,tag:Hc+cAzQx4xFayD+pA6FjTw==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT09mZ0RwdVowM3F1Wngw
            S2NyQnE3QzBhS2FHOEpKb1VzcU5QNkZGeGxBCm5yeVdLbUEyaVBnQ1hNV2Q5Smk2
            cGMyMERFdlgrYXBJV1Bqc0Y4MHRYckEKLS0tIEZQczRhR0owV0xOcm9hSFc1WDNZ
            dXJZR1BtTjFJSm5QY29RMmtwb2dkbGMKWqQFSOobMAs2E3Yosn2uK/E1Uw1BuRQH
            rOBq2Pja7zYhlW4KwkBHmXmHGYNt/2zSDHSU6lkEJBFb8qMA9B7yBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:25:49Z"
    mac: ENC[AES256_GCM,data:uTcD8Kvs40UNgA1ZUMvKSWrERNA0TaUFJgrTqNCCIg4OF7ukeoOc1pUWrLCbMDPaxLOjP4rooHeBRk1VvT4PgMep47+wj1zBVRswGm4EDsNJkoNk8UTCtfRP6zqt1dlUc+xT3ECAZwD+FqA2gYWjsNdKz5F2cJqMWEyBQFB5ds8=,iv:XRLIQjGYPrEWS2sAjTDq+WBPBNR2whnBhtiN+pFFtRg=,tag:Cr5HhBfsJAzfIPid1v5VsA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless-ngx
stringData:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:NAXgiZutZi6HVXT+7eMT2E5ezn8upg==,iv:dCskaqMIUJDdR7eozLABjZR5KdcohDKLLtKQiYx7r84=,tag:CSmt/HoAebmYcaBv2S5vOQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:iEIpp6A=,iv:tTWdYvp21HwgX83uRxMeGH5y/od6yJhBMCM/tajMGos=,tag:IxM4p7kyA+REGVkDGbgCPA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:II3FvvZYls4P9jv+w/DcPncK3jGmYB6feb7nevvC+Lw=,iv:jKThdTVau+AO4bNKoChtfF3lplffYl1fIw74t1Y4X9w=,tag:7W+DEP9SW+CtimC7h4r+Lg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:kcuSrZBPZ5arXzlLTCj746JCytc/LUaGBn6QZHKfAYoaS6HRpg+5I9ACoXOqHUbvcG0=,iv:TRG+xLT6dXKVD9Vi78//osK5EiyhJIvahuGzYgXgZQk=,tag:zNvM0O41MI7r8lPbv+KUcQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:VA==,iv:6hHQvyr2lA/+U2IsoZGYzla2mKSMyPonBvabkkPtj2I=,tag:RgzaEMfNJUwg+D3X+yT6Bg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT09mZ0RwdVowM3F1Wngw
            S2NyQnE3QzBhS2FHOEpKb1VzcU5QNkZGeGxBCm5yeVdLbUEyaVBnQ1hNV2Q5Smk2
            cGMyMERFdlgrYXBJV1Bqc0Y4MHRYckEKLS0tIEZQczRhR0owV0xOcm9hSFc1WDNZ
            dXJZR1BtTjFJSm5QY29RMmtwb2dkbGMKWqQFSOobMAs2E3Yosn2uK/E1Uw1BuRQH
            rOBq2Pja7zYhlW4KwkBHmXmHGYNt/2zSDHSU6lkEJBFb8qMA9B7yBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:25:49Z"
    mac: ENC[AES256_GCM,data:uTcD8Kvs40UNgA1ZUMvKSWrERNA0TaUFJgrTqNCCIg4OF7ukeoOc1pUWrLCbMDPaxLOjP4rooHeBRk1VvT4PgMep47+wj1zBVRswGm4EDsNJkoNk8UTCtfRP6zqt1dlUc+xT3ECAZwD+FqA2gYWjsNdKz5F2cJqMWEyBQFB5ds8=,iv:XRLIQjGYPrEWS2sAjTDq+WBPBNR2whnBhtiN+pFFtRg=,tag:Cr5HhBfsJAzfIPid1v5VsA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-backup-s3
    namespace: paperless-ngx
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:PjF7eSrxMVWlDw==,iv:5SspXhn9cEfZOCsxTWQV4vHnicizfA7wNdTNMQl9nr0=,tag:Gnayerzwr7dpSWUuAxg+eg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EDq1fuLIO4BLBA==,iv:YbwLjVY+zV0hNW0ttwmywIX44uj4BEfId6KgobCVHmY=,tag:LRbO3g5xcrn6xAZ6VDJt+Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT09mZ0RwdVowM3F1Wngw
            S2NyQnE3QzBhS2FHOEpKb1VzcU5QNkZGeGxBCm5yeVdLbUEyaVBnQ1hNV2Q5Smk2
            cGMyMERFdlgrYXBJV1Bqc0Y4MHRYckEKLS0tIEZQczRhR0owV0xOcm9hSFc1WDNZ
            dXJZR1BtTjFJSm5QY29RMmtwb2dkbGMKWqQFSOobMAs2E3Yosn2uK/E1Uw1BuRQH
            rOBq2Pja7zYhlW4KwkBHmXmHGYNt/2zSDHSU6lkEJBFb8qMA9B7yBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:25:49Z"
    mac: ENC[AES256_GCM,data:uTcD8Kvs40UNgA1ZUMvKSWrERNA0TaUFJgrTqNCCIg4OF7ukeoOc1pUWrLCbMDPaxLOjP4rooHeBRk1VvT4PgMep47+wj1zBVRswGm4EDsNJkoNk8UTCtfRP6zqt1dlUc+xT3ECAZwD+FqA2gYWjsNdKz5F2cJqMWEyBQFB5ds8=,iv:XRLIQjGYPrEWS2sAjTDq+WBPBNR2whnBhtiN+pFFtRg=,tag:Cr5HhBfsJAzfIPid1v5VsA==,type:str]
    version: 3.13.1
