apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-app
    namespace: paperless-ngx
stringData:
    password: ENC[AES256_GCM,data:jVuL5DcfUYZjJo2UBJJcfGtJcGuGa/iiztTJTkphgaI=,iv:OHAA3mQSQX70WLV2RbbNn0OCRR4clWFtsmgugtpMs7E=,tag:4bq+BdCf0uHK9+aepgNrmA==,type:str]
    username: ENC[AES256_GCM,data:k/INRr7L/oMa,iv:wMVnQDVAeRnKvoW46hS8q7MQgdTC352R07GCsOsZArk=,tag:PJhCW9GADc3pfsrcgp2SNA==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlNzSkdDQzQ5dWJuNFA5
            RTJHdy9KNWxtUDg1Tmk5bDZSU2E0WjRFTXpnCllRVmFVaS9ubmJVYjFyc0FOMWZD
            TVZzQmtsQXc5SkRMUThxWEwwNy9ldHMKLS0tIDZUc0RVOUVQRE1nT01nU0YzZUdW
            TVBtdmorNzF5MTQzTVVLaHZ4SkgxTlEKXrNsfhcXAm05Z+fxS03A+qgrLhtZGDj1
            /diUwl36hQ/kz5ItlFGMoSIs70+/frGYnv5j6bvuZoPQz2MTNdTNOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:44:55Z"
    mac: ENC[AES256_GCM,data:MorFm9BcrYIpvnopeT7X3ASA45gtkjnQu81ZVAZOw2bP5p64CP3FAypnCHfQFrrn3E3UmJi/pOR54vrH5MDmEJTk2YNDCvxRBdJ7jdpwRejsO+0QzjQxPH5IPalOMXiU71WiZdbYkBj9d1tFYw//B9J6+eQ7lIHYlugdaU7DyNA=,iv:FdcbJ7ZUikGvKP1TkUDNBbfMQAIcb2CSW6dzjYvMAYc=,tag:iC+nwhZwbU0ZgfxDkwHz4Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless-ngx
stringData:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:zR3rq2FQRAuGFJVl2dC3KBi1DvWQkw==,iv:+NmzMa3pDhibWXpAlbR9Q9fydWg+CVQH9fMSIYrBkgc=,tag:b3t4yp26Pwib3uEcc9HcRQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:KCaLeuA=,iv:FeZVgAcQbkrUq1ZuNugH4CQU3C8IoTRenPkR1VxA/vs=,tag:WzNn/cbM7H10ccr55CWntg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:qHUIOpDqOYelNXbTatH3CeT5DPI4KmOwfjzP60Nm9Gk=,iv:KhzODM/dDPS4eQ1EThGCDG1MNqnbOl9a3S8/b3Ao2Tk=,tag:GOlt04n8gvhjnB2nLOisTA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:xrgHCuULsENRztaFFOMWlCtO1HOzYsG3V7sPe3rnY67TkduQlmnpTL+1rAfGaD+q2Jw=,iv:GRGjeK29XUJypLE5TAguK+dvSEF9YA6A9RDiL4IFcMM=,tag:+z4eVOhA5w9nJ42A8sOLyg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:dikRsaqEC74VoW+HwM96sTHpPe2uAIEjVe6MZPcTznYVssSBuwihoPZdylTJF9NxH297dgIJpNe4+J7jzy9xSKTGBU6yIvV9M0ZZAmWvK/Q9CNWpgK50rtMSpubER5nD70ciyh7IrekZZU/HQdba3NzuIsIK0nKsGXUcB+yEk2VemttJ5OC1JiQrmHBc0NgSu0F6kNffCEvcUpljwCgs3qKFCE4PgCq1tyz+sN563A3x1ORsjPkdj446WtMiHmBd6SwJ+iSVKqGYxEf90XVHOvAwRc5lkQ31A/Nic3b7B38ENd7DagzJ0pNjGGnf5/Ow7uYz0sNf,iv:8npr6YO8aZzXaqvvPO3xk965ST+EESD5D9ncnVPkd18=,tag:e2Xjd1x8ROzeF1H6Kbhrhg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlNzSkdDQzQ5dWJuNFA5
            RTJHdy9KNWxtUDg1Tmk5bDZSU2E0WjRFTXpnCllRVmFVaS9ubmJVYjFyc0FOMWZD
            TVZzQmtsQXc5SkRMUThxWEwwNy9ldHMKLS0tIDZUc0RVOUVQRE1nT01nU0YzZUdW
            TVBtdmorNzF5MTQzTVVLaHZ4SkgxTlEKXrNsfhcXAm05Z+fxS03A+qgrLhtZGDj1
            /diUwl36hQ/kz5ItlFGMoSIs70+/frGYnv5j6bvuZoPQz2MTNdTNOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:44:55Z"
    mac: ENC[AES256_GCM,data:MorFm9BcrYIpvnopeT7X3ASA45gtkjnQu81ZVAZOw2bP5p64CP3FAypnCHfQFrrn3E3UmJi/pOR54vrH5MDmEJTk2YNDCvxRBdJ7jdpwRejsO+0QzjQxPH5IPalOMXiU71WiZdbYkBj9d1tFYw//B9J6+eQ7lIHYlugdaU7DyNA=,iv:FdcbJ7ZUikGvKP1TkUDNBbfMQAIcb2CSW6dzjYvMAYc=,tag:iC+nwhZwbU0ZgfxDkwHz4Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-backup-s3
    namespace: paperless-ngx
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Z1MBxElzB+e/eN9iL+QcdPXaOl0rl3+BtGw=,iv:f6MlmFR8ubo80mvP78TdKqxRtHkL+V1HjfZ4pUolnbA=,tag:W6KF5Ql4NJQuwihbUMQJUQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:42g1ou0nnDPYuyxeGDByAW5cFyVTETY75LK+OvD4fVLluTqEKZFI9hy6mIGJzREzwhscTSN+C+B2ynQ1Y2m1aQ==,iv:S+OqJHDXoOrIOouSIs+JmKrwsEQGsQlMyqYyL+SKdrY=,tag:7xy/AeaG97NSlf047O3BsA==,type:str]
    region: ENC[AES256_GCM,data:du1S9iK17bS1CvZh3Ps=,iv:qrzSaBdX+5XZYMdTEIGmGepB9PJLTZutiIL9023ZA/o=,tag:kqesvyTeG5x3Xj54LZR4Jg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlNzSkdDQzQ5dWJuNFA5
            RTJHdy9KNWxtUDg1Tmk5bDZSU2E0WjRFTXpnCllRVmFVaS9ubmJVYjFyc0FOMWZD
            TVZzQmtsQXc5SkRMUThxWEwwNy9ldHMKLS0tIDZUc0RVOUVQRE1nT01nU0YzZUdW
            TVBtdmorNzF5MTQzTVVLaHZ4SkgxTlEKXrNsfhcXAm05Z+fxS03A+qgrLhtZGDj1
            /diUwl36hQ/kz5ItlFGMoSIs70+/frGYnv5j6bvuZoPQz2MTNdTNOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:44:55Z"
    mac: ENC[AES256_GCM,data:MorFm9BcrYIpvnopeT7X3ASA45gtkjnQu81ZVAZOw2bP5p64CP3FAypnCHfQFrrn3E3UmJi/pOR54vrH5MDmEJTk2YNDCvxRBdJ7jdpwRejsO+0QzjQxPH5IPalOMXiU71WiZdbYkBj9d1tFYw//B9J6+eQ7lIHYlugdaU7DyNA=,iv:FdcbJ7ZUikGvKP1TkUDNBbfMQAIcb2CSW6dzjYvMAYc=,tag:iC+nwhZwbU0ZgfxDkwHz4Q==,type:str]
    version: 3.13.1
