apiVersion: v1
kind: Secret
metadata:
    name: paperless-watchdog
    namespace: paperless-ngx
type: Opaque
stringData:
    WATCHDOG_TOKEN: ENC[AES256_GCM,data:+CTvFDCEs2C5PGsFhY1EYm0nas1CuQ3rCPXyax47SEoqNWCKGX89Xm4/SA==,iv:h185JHS8e7kkyUsJ1/IfJhQ3ti3sbqyoJoBB+TsUVFM=,tag:5xb8vKdGHMDhOIktKYoEzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERWFjc0h3YnJPRmY2TFph
            ak4raWpDK0NBZEZZOWNrMW1ZancrdkMwYzFvCjlLUFJNLzdaSmxHMXFOZnFMNytm
            cHBRSGlVdDhDc0p6OHRPTE9FRjJMRzgKLS0tIGUrUlNTbGl1aDd6VnJtcHdHblFm
            dDB1dFJ0NDZTYkl4Z2ZtOGR2bllqY28KL/dlQf9dc+u3ViR+yaBYYJA4YDfZSQxC
            SlmG/F9WlsOWYznMsU7Te7TaKCD0yFG3CKVpipEatUk7BlS7ABxXHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T19:57:13Z"
    mac: ENC[AES256_GCM,data:6qqi7tdog+Trt2x2/UpoO0p4M0ZtnUHVs5ggtpA2Z282u5G3TFoI+sDWTC5by9xvxjOGVzbG5tVBpJGB8N0OcCBLmiFtDU4yD4xNzwMzYRNiRt//jk0m2KMuMvAaiFMM/bTvNJlYOLIobLoZU1dS2Hz1ldu3X0k8k0LrupKNTwE=,iv:2p09KGrZQDYigi8gqfiwI0K8IEBl/bNdmt759fCxsXM=,tag:zSwWHIO0+XfwznP4kPkPtg==,type:str]
    version: 3.13.3
