apiVersion: v1
kind: Secret
metadata:
    name: paperless-watchdog
    namespace: paperless-ngx
type: Opaque
stringData:
    WATCHDOG_TOKEN: ENC[AES256_GCM,data:+CTvFDCEs2C5PGsFhY1EYm0nas1CuQ3rCPXyax47SEoqNWCKGX89Xm4/SA==,iv:h185JHS8e7kkyUsJ1/IfJhQ3ti3sbqyoJoBB+TsUVFM=,tag:5xb8vKdGHMDhOIktKYoEzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSE02YnVvRENTNEhEUy9U
            Ym54SmdoR2tDd1VXSlBvL2JtaG1uN25aUGtvCmx6RDNwUUFvMExwNmVIZmhIZC94
            dDZ0NzRTRWh4UnplRjdtUzBPbG9IbmsKLS0tIEY4K0gySHlYN1M4YlFkSkVyN1BH
            cldWN1Mxb3Z5d2ZiSWZjUmlIQkh0Q00KqWWZzso0p0W9faHnZZbar32k8WHqKsgS
            ZaxtWG+kRXQBtwS4I1XgEk767+8bczc8lRYWWwaQtlaGAuPmnBS+qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaWoyK1JIckdOYnJXOVNF
            cE54cEMzd2NmSVRITlVJek82d0krZTJNN21NCmhtenJPM1F1ZUNjZFZmR1NNQlc3
            bnl3R3VySmp4MTVVNFdmbWF4SnErTkUKLS0tIHVValJUR3NQeDJncGEyeXdlYlh1
            cjM3dExvM1lSUm1jMzJOd1pUdUdsMTAKZBCVnmkfYRXhOk2wkBdKZerTFT/EilcW
            jsqSi2g+EqtsvC3rofl3AGlKvF2JbDqNpz0mEP8iPujAHAExqellzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T19:57:13Z"
    mac: ENC[AES256_GCM,data:6qqi7tdog+Trt2x2/UpoO0p4M0ZtnUHVs5ggtpA2Z282u5G3TFoI+sDWTC5by9xvxjOGVzbG5tVBpJGB8N0OcCBLmiFtDU4yD4xNzwMzYRNiRt//jk0m2KMuMvAaiFMM/bTvNJlYOLIobLoZU1dS2Hz1ldu3X0k8k0LrupKNTwE=,iv:2p09KGrZQDYigi8gqfiwI0K8IEBl/bNdmt759fCxsXM=,tag:zSwWHIO0+XfwznP4kPkPtg==,type:str]
    version: 3.13.3
