apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-2
resources:
  - ../../../base/wordpress
patches:
  - target: { kind: Ingress }
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: site2.jit.services
      - op: replace
        path: /spec/tls/0/hosts/0
        value: site2.jit.services
