apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roundcube-jitmail
  namespace: roundcube
  annotations:
    nginx.org/ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
    nginx.org/client-max-body-size: "25m"
spec:
  ingressClassName: nginx
  rules:
    - host: roundcube.savar.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
    - host: mail.steinba.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
    - host: webmail01.jit-creatives.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
    - host: jitmail.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
    - host: webmail.daec-berlin.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
    - host: www.jitmail.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 80
