apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roundcube
resources:
  - ../../../base/roundcube
  - jitmail-ingress.yaml

# ⚠️ TEMPORAER bis nach dem docker15-Cutover, siehe preload-cert.sops.yaml.
generators:
  - ./secret-generator.yaml
