apiVersion: v1
kind: Secret
metadata:
    name: cloudns-credentials
    namespace: cert-manager
stringData:
    auth_id: ENC[AES256_GCM,data:gppc0ZY=,iv:fV7tOOMR7mYtXQ/eSjR0hI9L5/yGfw0ICcGcSP/Ur6c=,tag:cdyvXiFr6XKLVYq4Le2ArQ==,type:str]
    auth_password: ENC[AES256_GCM,data:+VrSEfJaJVIHDNuM,iv:+L9t9VscyTHEx/ivLbdO6qrbEZjyvPr3TO5IP6J03o0=,tag:r3+MrPhuMsM7lOUCg2bk1Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUVNHTTVOUlJQWWk3MldH
            TTdpQW9OcGtPS0FzZ3RKWmdOYlBXanlOQUZ3CmZtQ2t2cVVHTjVoWW5COTY4aThy
            RWdoQ1FSSS9JZk1ES0ZSdnpxdUZJaXcKLS0tIGdNRTFGVnlqQlZsVnY2OTZ2SEp0
            TnpjVHVaU0l2MFltZWJvWXVaTUtnNm8KvasA/Iehz5ill0TKvdGFfNBM9Ntigrk/
            wZO1gxpI8R47IzfhTD3Ztpzg5VS7zfpn44FFoi3vNt/iIYrvHkYZbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T12:43:20Z"
    mac: ENC[AES256_GCM,data:E4K4ymdt5HoWZgQT65nnVqSVth7z7KbHJ6eKdmB0mjI4QjEIt6qXEuyjbQK9o47lXZ2wa1PyuJQlLRrEzPjNLaXsdYGonirnT1pwIYXYdLAffPf0H9Nl+GuAqPR3+uHwPR4HZrKtqf+G1wHXtAkCRP1cuqpIa7fBMfbORGHKHeA=,iv:OZTp7X32Ph4NtFyBFNmBLjvsL7q8Bh6RXtDpeH3EhoQ=,tag:vSYl12dl0eWmerP9FtR3yA==,type:str]
    version: 3.13.3
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        email: admin@jit.services
        privateKeySecretRef:
            name: letsencrypt-prod-account
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                webhook:
                    groupName: acme.jit.services
                    solverName: cloudns
              selector:
                dnsZones:
                    - jit.services
            - dns01:
                rfc2136:
                    nameserver: dns01.jit-creatives.de:53
                    tsigAlgorithm: HMACSHA256
                    tsigKeyName: cert-manager.
                    tsigSecretSecretRef:
                        name: rfc2136-tsig
                        key: secret
              selector:
                dnsZones:
                    - savar.de
                    - jit-creatives.de
                    - jitcreatives.de
                    - jitmail.de
                    - gemeinsam-fuer-halbe.de
                    - jugendbeauftragter-halbe.de
                    - aios.tools
                    - jit.cloud
                    - daec-berlin.de
            - dns01:
                cloudflare:
                    email: info@binaergewitter.de
                    apiKeySecretRef:
                        name: cloudflare-api-key
                        key: api-key
              selector:
                dnsZones:
                    - binaergewitter.de
            - dns01:
                cnameStrategy: Follow
                rfc2136:
                    nameserver: dns01.jit-creatives.de:53
                    tsigAlgorithm: HMACSHA256
                    tsigKeyName: cert-manager.
                    tsigSecretSecretRef:
                        name: rfc2136-tsig
                        key: secret
              selector:
                dnsZones:
                    - horads.de
                    - imcor.de
                    - jonaks.com
                    - naturkindergarten-moehringen.de
                    - steinba.ch
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUVNHTTVOUlJQWWk3MldH
            TTdpQW9OcGtPS0FzZ3RKWmdOYlBXanlOQUZ3CmZtQ2t2cVVHTjVoWW5COTY4aThy
            RWdoQ1FSSS9JZk1ES0ZSdnpxdUZJaXcKLS0tIGdNRTFGVnlqQlZsVnY2OTZ2SEp0
            TnpjVHVaU0l2MFltZWJvWXVaTUtnNm8KvasA/Iehz5ill0TKvdGFfNBM9Ntigrk/
            wZO1gxpI8R47IzfhTD3Ztpzg5VS7zfpn44FFoi3vNt/iIYrvHkYZbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T12:43:20Z"
    mac: ENC[AES256_GCM,data:E4K4ymdt5HoWZgQT65nnVqSVth7z7KbHJ6eKdmB0mjI4QjEIt6qXEuyjbQK9o47lXZ2wa1PyuJQlLRrEzPjNLaXsdYGonirnT1pwIYXYdLAffPf0H9Nl+GuAqPR3+uHwPR4HZrKtqf+G1wHXtAkCRP1cuqpIa7fBMfbORGHKHeA=,iv:OZTp7X32Ph4NtFyBFNmBLjvsL7q8Bh6RXtDpeH3EhoQ=,tag:vSYl12dl0eWmerP9FtR3yA==,type:str]
    version: 3.13.3
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        email: admin@jit.services
        privateKeySecretRef:
            name: letsencrypt-staging-account
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                webhook:
                    groupName: acme.jit.services
                    solverName: cloudns
              selector:
                dnsZones:
                    - jit.services
            - dns01:
                rfc2136:
                    nameserver: dns01.jit-creatives.de:53
                    tsigAlgorithm: HMACSHA256
                    tsigKeyName: cert-manager.
                    tsigSecretSecretRef:
                        name: rfc2136-tsig
                        key: secret
              selector:
                dnsZones:
                    - savar.de
                    - jit-creatives.de
                    - jitcreatives.de
                    - jitmail.de
                    - gemeinsam-fuer-halbe.de
                    - jugendbeauftragter-halbe.de
                    - aios.tools
                    - jit.cloud
                    - daec-berlin.de
            - dns01:
                cloudflare:
                    email: info@binaergewitter.de
                    apiKeySecretRef:
                        name: cloudflare-api-key
                        key: api-key
              selector:
                dnsZones:
                    - binaergewitter.de
            - dns01:
                cnameStrategy: Follow
                rfc2136:
                    nameserver: dns01.jit-creatives.de:53
                    tsigAlgorithm: HMACSHA256
                    tsigKeyName: cert-manager.
                    tsigSecretSecretRef:
                        name: rfc2136-tsig
                        key: secret
              selector:
                dnsZones:
                    - horads.de
                    - imcor.de
                    - jonaks.com
                    - naturkindergarten-moehringen.de
                    - steinba.ch
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUVNHTTVOUlJQWWk3MldH
            TTdpQW9OcGtPS0FzZ3RKWmdOYlBXanlOQUZ3CmZtQ2t2cVVHTjVoWW5COTY4aThy
            RWdoQ1FSSS9JZk1ES0ZSdnpxdUZJaXcKLS0tIGdNRTFGVnlqQlZsVnY2OTZ2SEp0
            TnpjVHVaU0l2MFltZWJvWXVaTUtnNm8KvasA/Iehz5ill0TKvdGFfNBM9Ntigrk/
            wZO1gxpI8R47IzfhTD3Ztpzg5VS7zfpn44FFoi3vNt/iIYrvHkYZbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T12:43:20Z"
    mac: ENC[AES256_GCM,data:E4K4ymdt5HoWZgQT65nnVqSVth7z7KbHJ6eKdmB0mjI4QjEIt6qXEuyjbQK9o47lXZ2wa1PyuJQlLRrEzPjNLaXsdYGonirnT1pwIYXYdLAffPf0H9Nl+GuAqPR3+uHwPR4HZrKtqf+G1wHXtAkCRP1cuqpIa7fBMfbORGHKHeA=,iv:OZTp7X32Ph4NtFyBFNmBLjvsL7q8Bh6RXtDpeH3EhoQ=,tag:vSYl12dl0eWmerP9FtR3yA==,type:str]
    version: 3.13.3
