apiVersion: v1
kind: Secret
metadata:
    name: cloudns-credentials
    namespace: cert-manager
stringData:
    auth_id: ENC[AES256_GCM,data:zyfN2IA=,iv:vAw9N7CfpfFTCi9w9L6u5Tl6fg81fymPO7yHLR66YqE=,tag:NXakkKFeCXIj62SfFqWIJw==,type:str]
    auth_password: ENC[AES256_GCM,data:zs/91DqZHOStzMvb,iv:PxKvMR9AQBMNTYG/RF4fb1MbwqDAhHw4LQpQ8WKmVSU=,tag:9wRDCx3uHafHy8yr4z2vNg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEw2NURpMER4ZVlWRjFy
            TWhQNnRMTkkvYmhZVWJ6aERuTWNTWm5VeHprCkNkV2RFZ2x4cHdRaDhSaitudWJ4
            M1BqOW5DSFk4ZWJrL05DbFlhcFpkUnMKLS0tIE1zc0VkclMzM1lWUDN5MUZDNGRy
            YVM5bmluSEVmZlNhY2EvdUtOWTlqL00K2H+8PuEjuW+eDVWM4z/x14kie+/R/Zyi
            AjUmRglnlWKC3WKpa4ZAY76zJ9f+f/2EzrCblFtNckBoeRkk2d5tUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:14:26Z"
    mac: ENC[AES256_GCM,data:HfC0Z7ZK+fqah3utsUcTMmIy6pmAJ+iRZ1GOvuf9N2o6F19+7hB81dbVzrftlzkXeOodPodlkzpYr+rMXkkZputRJaDQnj/zkYfcsNy6JOupGKJ/TZM4m/ZPd0jGhVxh6Q01Fw4uu2agq9Qbd+RBiCTRXce2tE2wLABbUsljicw=,iv:Lx7hI4F0/EBx752DSMMduoxSh3el/N3viW0KCvU1sFE=,tag:XbOWvF1AoXiPFx35mt4m3w==,type:str]
    version: 3.13.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        email: admin@jit.services
        privateKeySecretRef:
            name: letsencrypt-prod-account
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                webhook:
                    groupName: acme.jit.services
                    solverName: cloudns
              selector:
                dnsZones:
                    - jit.services
            - http01:
                ingress:
                    ingressClassName: nginx
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEw2NURpMER4ZVlWRjFy
            TWhQNnRMTkkvYmhZVWJ6aERuTWNTWm5VeHprCkNkV2RFZ2x4cHdRaDhSaitudWJ4
            M1BqOW5DSFk4ZWJrL05DbFlhcFpkUnMKLS0tIE1zc0VkclMzM1lWUDN5MUZDNGRy
            YVM5bmluSEVmZlNhY2EvdUtOWTlqL00K2H+8PuEjuW+eDVWM4z/x14kie+/R/Zyi
            AjUmRglnlWKC3WKpa4ZAY76zJ9f+f/2EzrCblFtNckBoeRkk2d5tUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:14:26Z"
    mac: ENC[AES256_GCM,data:HfC0Z7ZK+fqah3utsUcTMmIy6pmAJ+iRZ1GOvuf9N2o6F19+7hB81dbVzrftlzkXeOodPodlkzpYr+rMXkkZputRJaDQnj/zkYfcsNy6JOupGKJ/TZM4m/ZPd0jGhVxh6Q01Fw4uu2agq9Qbd+RBiCTRXce2tE2wLABbUsljicw=,iv:Lx7hI4F0/EBx752DSMMduoxSh3el/N3viW0KCvU1sFE=,tag:XbOWvF1AoXiPFx35mt4m3w==,type:str]
    version: 3.13.1
