apiVersion: v1
kind: Secret
metadata:
    name: rfc2136-tsig
    namespace: cert-manager
stringData:
    secret: ENC[AES256_GCM,data:hBYzL2ieRU3lSjZeOnOIUyoGyVe3o2B5R0+jupubvghFr7iqM+3B0AMxkiw=,iv:0mrHE3sbE5XpzFYnWiwCrzSldhYGTVBa/2hKs6ON9r0=,tag:C6//Shx6jqq2yWni0KUhZg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dmQzZE9QRFovcVdHZEpk
            T1plUzR5YnRWbkhiR3BoSm1mN2xpdUlHRUZFCjZ3UlR5ZEtWTkdmQVJzcUpacU03
            eEF1Tk5TRlFyd2NTTlM2NWFyTkNheGcKLS0tIC9tamNZZGtLM255czduOWVWWVcr
            cDVjbWo4bG4wYzd3M1ZxWVpZdi96SWsKiG5AoFTUYnPvOQ/qrCsIk3fTF5ke14ZU
            SR7jxDOVk5FcrsW/2IQlAi2EVmws/KEhhP2zhfdGAASWGDwh1+5plw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRFRGOEIrbVBaRURXTThH
            Nm5tc0tuVkd0NEFrM0loSWJld2JqZU5DZlRRCjJma2RFNVlrYUV0Kzh2YkpFdkxI
            cjliSUo1aWwrSHRWWTRRNkJXaGhzWFEKLS0tIDlCb0IzS2UwWVRmU05wc3hsVnJM
            L1NuWWpXSE5SeGZRZmtyNDQwU2lEVGMKtgIcTVkxqZCB6VCB9SWxWVSxj5XaYd6J
            f1yx25kxbIVMGFlVxdl0uvJFA1LFr/6sig7v9dtsOhOiODPamcprMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T04:50:50Z"
    mac: ENC[AES256_GCM,data:U/cmnQww+xYjRLES8XpCK5tKtWZ4QDhib0jcddVqnWbOtK+hyUHFl9VEV2+yNyCB9tmAWn6bZteLLxWsbpEl32nhN1arsNJzHsaL4ymFgOAxpIzRMAfP1O30f9+XisVkIE6tptGrwhskNkajOwIuMLg9TKdSNC64Uoot620ZZmU=,iv:/u/RWnnM5Y3z5+9CdQmy5c1nsdSO5IWPplv7UkS2aPM=,tag:notcHpjl4TmOAMadjGifGw==,type:str]
    version: 3.13.1
