apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secret
    namespace: mastodon
stringData:
    secret-key-base: ENC[AES256_GCM,data:xrnmXm/ieWoc6zhUO6pB8vh9L9XM7bCoAJ66yjGmvGcqSwgrH2AWg/QRzM0FGHKkhcf//hcCKwNuu62dsE05tFB4ROCeUDI4qURhdcncTv6190AfpnhIANQ3incB7SNBejfC3DxZ9G+2eWOfaHvVIoC2q0Wr9i16XWYiSrItRcI=,iv:m877av2XCtMhL7kciKAmjkdXK/RqjCSEaxmIYFJATRE=,tag:hUn+bUr5hOPPvwdKylQ3XQ==,type:str]
    otp-secret: ENC[AES256_GCM,data:qkvg22jaxmzhThljU5p3EAa2wXrlNEewz0lsynfOICUHg8QWoYdja06KYqj8YToeWbgaHnJJNs5KE54nxpn7KM2yP3SRvLlBhTAbQST1s0W6kIOAZVJqoGfCOnuuh/fpUCVncq7zsPLpRUk6XuVVG1C3Jm+RHAUbIw7V3eNTKKs=,iv:776KWuYJS208jwvJOQbgan/ii5Xfnk8t1JnyUThQi2g=,tag:kJuX4JOeAgCg022ngBbwow==,type:str]
    vapid-private-key: ENC[AES256_GCM,data:ZfcQ2fzyJKzUX8gBmjcfUvvlL5kOKV+vwm8L7f0NP3QfktOvgoOuGXWSLjs=,iv:y8Jvi4DUAspMc/E7lOYx6obMGeIHdfnIiArLLr3S0vs=,tag:ayBp4W60ynMjEO0zXj1FLw==,type:str]
    vapid-public-key: ENC[AES256_GCM,data:EK0jp5TE/eKNvIQ0ndjAtalRuTlOSY84fqI5ujBw9s4wuTskhE0fgt7MsIg/BcwoO36GL6GR/RcFhgpl/GacMmYRMoKF2GbSakiseZBQ/ntCPcbjG+sYVA==,iv:a9+GieUx6OPINSDmwc0tFlG1BmGB7mMM1GWMifs/Iyw=,tag:ZX1m9YP8/h9DurggKikt7A==,type:str]
    are-primary-key: ENC[AES256_GCM,data:y1YpBY5YNquNeQvIxTIkQ3Lm6PlOYLmHHE7Kw638CVA=,iv:dmnXS/lhmPay7X3UsxlOaoZvFmVL66oSit6PoRHfftE=,tag:TfPgpI1fpr/P8BnD+TpiLg==,type:str]
    are-deterministic-key: ENC[AES256_GCM,data:GfDPd2Lu9sCxuBj4biULNU2maTDiIe3VcWMlJAGNyCM=,iv:VZEZj2SomTKE5sy/7kR1y94SWtETgOxcrTpEWzUimlE=,tag:E/HFXGmet4isx+K0ClxITQ==,type:str]
    are-derivation-salt: ENC[AES256_GCM,data:v/VDaJCCSL42QDspcILTQBL6NylvX5YF0FaLYjJUYzY=,iv:4ujSrFrjF0MP6IVS9UBysc30uKW7RIo9Y92m7UYjwHw=,tag:OEHeOB9VCH2Y8B3pv3wLvQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGZQSTZ0UC92RFkvdStk
            Vm5FeFhXa0dhQUIzYXhEV0d3SWFDZmtKbkhVCmI0NlI0S1lKbFBudWlsWm5NZkly
            d1dIT1pFRi9RQzVlV3BXK0c0ZUZDY2sKLS0tIERycTVpNzY1c1RSbXJwZnFwamt2
            b0k3dzR4dEU0bHVqeU9hdVRieC9SclEKJeQoR/ZnQFiRlDpXm+BkTcnY+kJFdIC2
            UPXSOvWkCDQovYXYI0M+8Qu7IWGWRBLuYqzE79M2KzTZlJkUY4n7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1VRUHlNRWY1UFp6MVl1
            TU8rZWdOSmN5WFZmODkrS2xaVUNWbkd4TldFCjhodnR4cWozTUxSMXFhSUZ6NWRz
            WW4yb21tOGhLL2UyVUpVV0xGdUZqYzgKLS0tIDM0c2Y1bmFwR0tXY1VjR0pQMk1m
            YU5HUmVKUS9RV2pNeVVFTGU1L1JFU2sKaAOVhQF6aItD5IXxUCPbBc5oU7vPN116
            BS9Zvm7eZxdUrG9qrYkPzSOniIA1+raRpXAR1w8Vv6orVAdJ5Hunvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:15:31Z"
    mac: ENC[AES256_GCM,data:KYpvpFn/wAprTryOsOelw1LCCCrWis5M6VuFexUo0WDiV3P0bX6v6ssyAz2O9twMsoSRU5WQA92XamD9vJ47Y/4yus/xMlf52+v5k3++hN4gBEAsbPmuBv5HzAyu3A6G1XWW45tWN2hRnSStQOG4Ke8VIMzwkYlWYVFnOvwBlYQ=,iv:Y6ZX6nmcChvrBiKsz4w+CUPje+hPohLSzipQiAM85R8=,tag:M7neg232AQvKukHYpqlM8g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mastodon-db-app
    namespace: mastodon
stringData:
    username: ENC[AES256_GCM,data:r/B0AxsNJvM=,iv:BeIOjwJa6FbpMPX5LniWde1IxSjcKs1P5hndMsD7mAs=,tag:+pGY5IvqnfF+W2+CJtz1vw==,type:str]
    password: ENC[AES256_GCM,data:lAO5sHWDFoP/x/pQvbn6ecNPJbbzsz51HYfS6BJiylKb7hNtIyOg0DB724Hy9cFDxYHWfnubvwT2DDKRrw1RIA==,iv:psmgmEbsY3lIS+Xx00tmIzsB0GBNs53qrgw2HFyDMwI=,tag:9IHMHRzezHAAEqDf7vdCRA==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGZQSTZ0UC92RFkvdStk
            Vm5FeFhXa0dhQUIzYXhEV0d3SWFDZmtKbkhVCmI0NlI0S1lKbFBudWlsWm5NZkly
            d1dIT1pFRi9RQzVlV3BXK0c0ZUZDY2sKLS0tIERycTVpNzY1c1RSbXJwZnFwamt2
            b0k3dzR4dEU0bHVqeU9hdVRieC9SclEKJeQoR/ZnQFiRlDpXm+BkTcnY+kJFdIC2
            UPXSOvWkCDQovYXYI0M+8Qu7IWGWRBLuYqzE79M2KzTZlJkUY4n7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1VRUHlNRWY1UFp6MVl1
            TU8rZWdOSmN5WFZmODkrS2xaVUNWbkd4TldFCjhodnR4cWozTUxSMXFhSUZ6NWRz
            WW4yb21tOGhLL2UyVUpVV0xGdUZqYzgKLS0tIDM0c2Y1bmFwR0tXY1VjR0pQMk1m
            YU5HUmVKUS9RV2pNeVVFTGU1L1JFU2sKaAOVhQF6aItD5IXxUCPbBc5oU7vPN116
            BS9Zvm7eZxdUrG9qrYkPzSOniIA1+raRpXAR1w8Vv6orVAdJ5Hunvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:15:31Z"
    mac: ENC[AES256_GCM,data:KYpvpFn/wAprTryOsOelw1LCCCrWis5M6VuFexUo0WDiV3P0bX6v6ssyAz2O9twMsoSRU5WQA92XamD9vJ47Y/4yus/xMlf52+v5k3++hN4gBEAsbPmuBv5HzAyu3A6G1XWW45tWN2hRnSStQOG4Ke8VIMzwkYlWYVFnOvwBlYQ=,iv:Y6ZX6nmcChvrBiKsz4w+CUPje+hPohLSzipQiAM85R8=,tag:M7neg232AQvKukHYpqlM8g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mastodon-smtp
    namespace: mastodon
stringData:
    username: ENC[AES256_GCM,data:pSU33ANdpAMV/mhMgroL49IFCxCDejyy,iv:A3nPg/DmJdrY3ATRocR6rKKNArUxrVjj1Ma+Ux7v/KI=,tag:gsN7sfInfAZWZwDXfqejnA==,type:str]
    password: ENC[AES256_GCM,data:8ki5uZHukMdrOQ==,iv:sXUwMbD7Vpyq+fVDnF3E+hPwYcR7D9CGczUSENIHUTU=,tag:d6+KKgIO2U/slz9cpdkwag==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGZQSTZ0UC92RFkvdStk
            Vm5FeFhXa0dhQUIzYXhEV0d3SWFDZmtKbkhVCmI0NlI0S1lKbFBudWlsWm5NZkly
            d1dIT1pFRi9RQzVlV3BXK0c0ZUZDY2sKLS0tIERycTVpNzY1c1RSbXJwZnFwamt2
            b0k3dzR4dEU0bHVqeU9hdVRieC9SclEKJeQoR/ZnQFiRlDpXm+BkTcnY+kJFdIC2
            UPXSOvWkCDQovYXYI0M+8Qu7IWGWRBLuYqzE79M2KzTZlJkUY4n7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1VRUHlNRWY1UFp6MVl1
            TU8rZWdOSmN5WFZmODkrS2xaVUNWbkd4TldFCjhodnR4cWozTUxSMXFhSUZ6NWRz
            WW4yb21tOGhLL2UyVUpVV0xGdUZqYzgKLS0tIDM0c2Y1bmFwR0tXY1VjR0pQMk1m
            YU5HUmVKUS9RV2pNeVVFTGU1L1JFU2sKaAOVhQF6aItD5IXxUCPbBc5oU7vPN116
            BS9Zvm7eZxdUrG9qrYkPzSOniIA1+raRpXAR1w8Vv6orVAdJ5Hunvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:15:31Z"
    mac: ENC[AES256_GCM,data:KYpvpFn/wAprTryOsOelw1LCCCrWis5M6VuFexUo0WDiV3P0bX6v6ssyAz2O9twMsoSRU5WQA92XamD9vJ47Y/4yus/xMlf52+v5k3++hN4gBEAsbPmuBv5HzAyu3A6G1XWW45tWN2hRnSStQOG4Ke8VIMzwkYlWYVFnOvwBlYQ=,iv:Y6ZX6nmcChvrBiKsz4w+CUPje+hPohLSzipQiAM85R8=,tag:M7neg232AQvKukHYpqlM8g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mastodon-redis
    namespace: mastodon
stringData:
    password: ENC[AES256_GCM,data:QnGyJWnBXH5JTAW1+rFpoRPoDVrWQSzy106fLih+QYFieQB77p73yhwLqYFYWtD5YE9ZT3wx1IGpcyRqSxpEgg==,iv:gC1Ddqp7eoAbJhk5UhlsCHMVaL5BhEFDh79i96D1KQ0=,tag:H3PqwmQi3iMU18XCaDXnig==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGZQSTZ0UC92RFkvdStk
            Vm5FeFhXa0dhQUIzYXhEV0d3SWFDZmtKbkhVCmI0NlI0S1lKbFBudWlsWm5NZkly
            d1dIT1pFRi9RQzVlV3BXK0c0ZUZDY2sKLS0tIERycTVpNzY1c1RSbXJwZnFwamt2
            b0k3dzR4dEU0bHVqeU9hdVRieC9SclEKJeQoR/ZnQFiRlDpXm+BkTcnY+kJFdIC2
            UPXSOvWkCDQovYXYI0M+8Qu7IWGWRBLuYqzE79M2KzTZlJkUY4n7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1VRUHlNRWY1UFp6MVl1
            TU8rZWdOSmN5WFZmODkrS2xaVUNWbkd4TldFCjhodnR4cWozTUxSMXFhSUZ6NWRz
            WW4yb21tOGhLL2UyVUpVV0xGdUZqYzgKLS0tIDM0c2Y1bmFwR0tXY1VjR0pQMk1m
            YU5HUmVKUS9RV2pNeVVFTGU1L1JFU2sKaAOVhQF6aItD5IXxUCPbBc5oU7vPN116
            BS9Zvm7eZxdUrG9qrYkPzSOniIA1+raRpXAR1w8Vv6orVAdJ5Hunvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:15:31Z"
    mac: ENC[AES256_GCM,data:KYpvpFn/wAprTryOsOelw1LCCCrWis5M6VuFexUo0WDiV3P0bX6v6ssyAz2O9twMsoSRU5WQA92XamD9vJ47Y/4yus/xMlf52+v5k3++hN4gBEAsbPmuBv5HzAyu3A6G1XWW45tWN2hRnSStQOG4Ke8VIMzwkYlWYVFnOvwBlYQ=,iv:Y6ZX6nmcChvrBiKsz4w+CUPje+hPohLSzipQiAM85R8=,tag:M7neg232AQvKukHYpqlM8g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mastodon-s3
    namespace: mastodon
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IXezokW7R04Yyj/27p9cZsxqahCk2i6mz6NFijed3H4=,iv:hGSQLkATzz3C+JAEpjnb9eHCSYnHps92SF0raG2COjo=,tag:FbWBe0LcH24nS9iF605Xtg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CaTD/fndiCMdffHwv17P4hy3yJ5vD9BhnaWgklYVVT1BAE/8zFLuJsggj2Qk3MdOLVBhTT9YHspdmqLN01Qr0A==,iv:kFMDMY4EqvlJWMpqHoz2J/p7WpA5D7BoyoXFHEjZgqE=,tag:ALYCKvJ2GwOwu4OHnGH1Sw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGZQSTZ0UC92RFkvdStk
            Vm5FeFhXa0dhQUIzYXhEV0d3SWFDZmtKbkhVCmI0NlI0S1lKbFBudWlsWm5NZkly
            d1dIT1pFRi9RQzVlV3BXK0c0ZUZDY2sKLS0tIERycTVpNzY1c1RSbXJwZnFwamt2
            b0k3dzR4dEU0bHVqeU9hdVRieC9SclEKJeQoR/ZnQFiRlDpXm+BkTcnY+kJFdIC2
            UPXSOvWkCDQovYXYI0M+8Qu7IWGWRBLuYqzE79M2KzTZlJkUY4n7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1VRUHlNRWY1UFp6MVl1
            TU8rZWdOSmN5WFZmODkrS2xaVUNWbkd4TldFCjhodnR4cWozTUxSMXFhSUZ6NWRz
            WW4yb21tOGhLL2UyVUpVV0xGdUZqYzgKLS0tIDM0c2Y1bmFwR0tXY1VjR0pQMk1m
            YU5HUmVKUS9RV2pNeVVFTGU1L1JFU2sKaAOVhQF6aItD5IXxUCPbBc5oU7vPN116
            BS9Zvm7eZxdUrG9qrYkPzSOniIA1+raRpXAR1w8Vv6orVAdJ5Hunvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:15:31Z"
    mac: ENC[AES256_GCM,data:KYpvpFn/wAprTryOsOelw1LCCCrWis5M6VuFexUo0WDiV3P0bX6v6ssyAz2O9twMsoSRU5WQA92XamD9vJ47Y/4yus/xMlf52+v5k3++hN4gBEAsbPmuBv5HzAyu3A6G1XWW45tWN2hRnSStQOG4Ke8VIMzwkYlWYVFnOvwBlYQ=,iv:Y6ZX6nmcChvrBiKsz4w+CUPje+hPohLSzipQiAM85R8=,tag:M7neg232AQvKukHYpqlM8g==,type:str]
    version: 3.13.3
