# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kite
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CTfdzs14hyp8TWIaLtdA1sgrRCu98lJaPj3u6CgwPTsVYs73KJl+I/gHlcxf0g==,iv:TtLhcXfILcKTGC4DDa8tJcfVaBOo7HrH4d1C2WYUPqY=,tag:FCGi7Sq8O6N1zf+KlRm0Gw==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:7NQE/LSHCXc+dQ==,iv:4Yf//h+N0eCGzrl+9j8wzWLV8+DHoXV3TAnaSjOy/f8=,tag:K0m91KUDKaYepb9lFrNGlg==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:5NWYZIStnr28OQ==,iv:VVxR8AfYJUuyGkbn3H+aFbNkCHnxO7gZ0xuWnzjdTWo=,tag:f2CzwkL7svm4yzKpWYEDkA==,type:str]
    #ENC[AES256_GCM,data:IG9Ni+mvmn92z8l8nogAJJwHdkVip+ZP5nsaRYfLyGGaPisPd/g/LfS45+TzpsuEI9rH30bv3qE7I1J81vw9G/ejor2xcYwH6sqnncleb342vg==,iv:yoM3Mjs1e3+z5xu0pR2pAW2ebvrPtCI6zEGVtguiFzE=,tag:qFS2L88a5lDviK4e30rF5Q==,type:comment]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:DZUXbpjtmXg0+g==,iv:MhLmwlh/Ma36VAeKwBP8NcLrgL58zTv5cMtuUuZFsUU=,tag:VL2VwHXSDHY7QE7uuSQgIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RExlN2UxK0NxeUxaY0c0
            UVpCdXpvRkt4OXY3SitYdnZqZGlMVHVaRkUwCnJ5MjE1M2lRbXpoU25JclJpZ0Zn
            VHRyUGMxVFhBcnc2WDByU2dqaDhtcXcKLS0tIFdPYkFwL2tZc2dsbFJ2dmdaejRl
            TlFWNjJoemVsRkM5OVFUK2hzTXJFOVkKh81y668cbKGzmWNP+hbDZzKwBOF9e4qN
            aT3edLuwaHZWmnlO3sKt+UteNJGxS+I1RBrgnZn70Agmap1xtWy70w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:j2EXezzWQVZwZd+qBOtsU3Vpada5ECM6C1b/a0UIOS9MUAU9to0K3GnpDrkFF6uJeE+yGSnHrTopbRkT7rrwPiEJr/j4zq7pq7AW73lCn/pPOxdbBhTHOsToe3dcbVxseJDU434aTBq4FqqEXRAKEsI0Z+ig2Vly3KtqBgIFyDk=,iv:HFMPdXnP/kg+5K3ea8r0hqEP1sYROuPMX3hhH0jXbGk=,tag:10MVajYpD4E34probdoxUQ==,type:str]
    version: 3.13.1
