# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kite
type: Opaque
stringData:
    #ENC[AES256_GCM,data:f1MQZOL6T7SnWOsdgSSyfyEJ8hAwwa7zjEEj+vE/kKvNKTdjx1cZztWHnWQo7w==,iv:oSgT4q+gH72SwOo6n0pjyj32xXAvvBtBuKV62/Bscbs=,tag:Cj5C/630pq+GJqkcOwci9w==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:136ErbvqcPeJ+A==,iv:Z1PTaLJ1CspnunHVhmAngItUJhAA4BsjZURbgwzqN8Y=,tag:fnpEdYnJwdFKTy0FPmHgUg==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:GBmFmUHQLqTxoA==,iv:hHIJ1t6/WCJBMt9uZ0nN/mwizwxlai3SQi44qN1QPKo=,tag:Dm5wzwfnQN+2iaGMZ8WjFQ==,type:str]
    #ENC[AES256_GCM,data:uyO4FxwbBt4hNMmIO7+HftOygBIaCoFcRavnQ0PYJLJaS5SNVJTkg+zTnpJRm9GY4qwH4k6pBSD4SwQtImIm8CH6IY5jD7a3RyURwpb46ad5tQ==,iv:vRwi8tUCraIinudGQNDCeJkuam1Rb5BMGzUiWuHdlPk=,tag:Qgw4l4dkhKiRolrrRQQMFw==,type:comment]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fOfSHcrbYuaISA==,iv:9tK4JF6vwCnjuX9QAm0AD5KAbPoPatWJ1Q4HrAnPbsg=,tag:7ahdz1o8nuS+dOpedmH5uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmallFSkVtWFYvVUVlOEhi
            ZTlWK1ZmMDMvVVY3YWF2aWU5UGttMEwvNWdvCkVVT0ZnbDErOFRMWERsUUZwWDBE
            d3pXemg5VWxSWVc2TkdYd0dPQWMvWE0KLS0tIGNIc0ErYkVXZHRxRGRtUndjSDkz
            bWFTS1dWQ3Q3V2hpMjV2RkNVNXRnU28KH0ZKa/AFBOCP68dISqP+q7ag43Gyr+v3
            EqX8s+GnTXbMtwZaCibZ5PFx3SmSrl+LKK1lednG7k4Hpv5U0axUpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:LG/9DPYlQtXQ89A76yNlK2SpT1RCSXkzuMpMJIpofPnB1QlKC5/30KLuT1U6IlIFySxjl1p9n2HjMRDwkFnFY4WIqv2veXozVNrLWcFs7CX2wBRPjiEfetfdFjCX0wOJJAUdugbV6ozgVfuIth/yYNSOoLbH2J4b/QmqFfM8c2Y=,iv:qyiEK/f8xDAMaNJmTXjGQYgWr47juKMUcctrjJJFRjc=,tag:fZnHJEBwkfUrP86Ik3ieGQ==,type:str]
    version: 3.13.1
