# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gatus-oidc
    namespace: gatus
type: Opaque
stringData:
    #ENC[AES256_GCM,data:EH54Q7n3ffr20d3Ye6HwcCuPmiddd0nZr8zLJI1yvDVqIfuGtoHe9RMSz5JId2STgqe/ElPKl6zihahbaItJxBBapBoyHJsozMA5RjpZe9fP1w==,iv:pX/kCJCLeZjHP8LWf/6iyqGZnOK63blZCGXcZFwvjko=,tag:NKy9RyBC8TBwr5v+oIw7bA==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0eFsSWMMEbjRjA==,iv:zNGcM6RFX7J3dzovZD5qjxuCHfHk6+VWMJEHqPCfSkk=,tag:Yk4huaPLVX8qovmBZb55AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2ZtYThmVk1CdHIwL3pJ
            ZElsVldkRjFkbU1xc2JOQmd6VlUyK0J3NWtZCmdTelRaSlA0Tk9pWlRFdzhEVGxt
            REhubEFuSnJhQWI2T2xBOXlIV2N1WWcKLS0tIERkV3g1K3lob05xR05acjRzK0lo
            VkhrRGwwMnN0NDB4di9TQmRjOEc1YmMK6FbVdIoYESPkkCQDO0eexmo8CIqKui/g
            4PxXfE0umIrBP4u3Eiz/XHhE+azwkEKkMCzzRyrYmHNJ0aGhp0J3yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:NA+1R2YKvjxiBb71XsoG2WgIZgzYj6Y58cwmqRupGM+bKQx+K9l9WeIGnuYXH8865QCheVr1GvFWvvl27sBZkOLf6rHUDGZxH+KJ8mfPGo2X4bC9GIvJ5siN1SZ3mgrHPbCAyDLRRV/uYCAxwUZnAedr8L2gANn/GFL2D0kBaD4=,iv:3X3gBBLtEXiMqs9d6NLcKAbkx/H5N+UjzF2utkcMWzw=,tag:t/EHHG7icYd2qc3s+wcKnQ==,type:str]
    version: 3.13.1
