# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gatus-oidc
    namespace: gatus
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KtmnxwgFszXieToURyxlcZg31Pbx8yhkrlWp+C3zKF4MnVSTZGtK1TjTeo0cB0nb/CuhT+2UmE/wBPbqzwSA9dPc/YUqnbV8zNwD3qBlh/6iNg==,iv:2j08uQHcMX6rzOWR4Ni+ElVxGT7ZIL9k7wLx/a/qnMg=,tag:JFNhBvHlrq0+hBHaeBaYVw==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:z7FRByNsHlZ3CA==,iv:VXQmZhCYsfy3fj/dlp2Y/UvAESKv+haCsjbnkPGnxkw=,tag:r1AH0+tW6VinVx3qeXmvaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOHZkSUs1N2ZjazhNOUdW
            bGJXK0lzSVp0N2VEOCs1QUtSKy9wNklqYUdnCk5hQTZPQnREUTZJYUtBUitLZ3VP
            QVFSd25vNnNKUGkvd3gvY01rN1diOFEKLS0tIDZrcWgvTkk0THExY1RnM2tmMzYy
            UDJ3c0lQK3RMRkFqcWdpQVBSL1VodmMK8aDZFdLM/Na8OcrNrtFNY+W2zHI8hMFp
            Q+8SXbpsYHAY+rvJHQYGlfef9x2N+tknS5tznz1gJ0+gz1kP9tL26Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:KxWLhEu4VSqWQ8uLFLmpmm21fPn4iw+a3Lt27I9mIr9sW6cT+MvbBW8OkiOHdnJCT4vVXcZIjk7oNOafdt9NEKZ9Y6vgJy2wHLo/nmU/I0xuKjX3/XSwClQl7LN+Pihy6jUhCb+dJIPigzjU/mF81Umva++lB7UWmZTxkjCZb6Y=,iv:CRFvGQhcIxTpo3Mmo4LA1zNYhak+3ApkRxrlM3yWQ1U=,tag:QMIIbPDTLpw4ZzA8ttp9gw==,type:str]
    version: 3.13.1
