# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gatus-oidc
    namespace: gatus
type: Opaque
stringData:
    #ENC[AES256_GCM,data:EH54Q7n3ffr20d3Ye6HwcCuPmiddd0nZr8zLJI1yvDVqIfuGtoHe9RMSz5JId2STgqe/ElPKl6zihahbaItJxBBapBoyHJsozMA5RjpZe9fP1w==,iv:pX/kCJCLeZjHP8LWf/6iyqGZnOK63blZCGXcZFwvjko=,tag:NKy9RyBC8TBwr5v+oIw7bA==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0eFsSWMMEbjRjA==,iv:zNGcM6RFX7J3dzovZD5qjxuCHfHk6+VWMJEHqPCfSkk=,tag:Yk4huaPLVX8qovmBZb55AQ==,type:str]
    WATCHDOG_TOKEN: ENC[AES256_GCM,data:ESFSZAJpYltgCmR3QqLrMLWgctK+OPMP7b/aQim3EvAYq0xSaByg7xMo8g==,iv:GAO3+XHzhAi7gDGtceNz6d8drea3qPv/ErVbo7yAcA4=,tag:sQ2xEc+KXaaKFvbxQuRtfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2ZtYThmVk1CdHIwL3pJ
            ZElsVldkRjFkbU1xc2JOQmd6VlUyK0J3NWtZCmdTelRaSlA0Tk9pWlRFdzhEVGxt
            REhubEFuSnJhQWI2T2xBOXlIV2N1WWcKLS0tIERkV3g1K3lob05xR05acjRzK0lo
            VkhrRGwwMnN0NDB4di9TQmRjOEc1YmMK6FbVdIoYESPkkCQDO0eexmo8CIqKui/g
            4PxXfE0umIrBP4u3Eiz/XHhE+azwkEKkMCzzRyrYmHNJ0aGhp0J3yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T19:57:03Z"
    mac: ENC[AES256_GCM,data:iVhbrjRVnooSkiTgqNerT2COZQk+IqfKkjNpW3jZIoY9W/Bh04eOnFtUJVD6MV/UVLhSudPzZAZo2R2Jum5r9G0ypGG6vOms8M/R+0Fxs10xxDDscuAmALcZhRRtGFDYA1zUjfXWhrXWM7e+1aT9+I/bhcwGo2+MH5Jy4oXq8L4=,iv:Uh46T1HvyFLxgZjbHwTf+fsK6mEN/hcwZWD7P+VS2lE=,tag:SFEaarEnRVnISv3dDkjyDA==,type:str]
    version: 3.13.1
