apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/ssl-redirect: "false"
    nginx.org/redirect-to-https: "true"
    nginx.org/client-max-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [auth.jit.services] # CHANGE ME
      secretName: authentik-tls
  rules:
    - host: auth.jit.services # CHANGE ME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
