# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: REPLACE_WITH_50_CHAR_RANDOM # openssl rand -base64 60
  AUTHENTIK_POSTGRESQL__PASSWORD: REPLACE_ME
  AUTHENTIK_BOOTSTRAP_PASSWORD: REPLACE_ME
  AUTHENTIK_BOOTSTRAP_TOKEN: REPLACE_ME
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
  name: authentik-backup-s3
  namespace: authentik
type: Opaque
stringData:
  ACCESS_KEY_ID: REPLACE_ME
  SECRET_ACCESS_KEY: REPLACE_ME
