# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:xZGrw2c/rjqjTBswhH9V1BPljn2SrRS/H2Gu,iv:5BYXC9j0ndaUOsEd5TC953HHg6Sdu/r9C9EASy+Lv9U=,tag:kg6DjWXUeRWI2lKG0shTQg==,type:str] #ENC[AES256_GCM,data:F8qoX5PxXgPI6kL4nuQkHWav4QnSNizX,iv:qv7EpaSCvItSntviNgnd6WF//vQfDoBTUo+9yxWEeOI=,tag:a1cBAC/wihxPe2yTsFhFhQ==,type:comment]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:fwC9oMfEEDtoUA==,iv:EEorvU2SVpGUakorPbTJHO2/btb3HaMglsm24spCLJM=,tag:OEMFFkQIJx7Woog9P/SocA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:X6nb0m+XJJUCXQ==,iv:J4pWH2vBsm/PjGaZPNaagbxDB1gaWFksJ9RpmGptonM=,tag:1F3X0ypPQ9qsyYJzqqpU8Q==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:7928CqxQXxAR3g==,iv:J6eATMvfnYclNvGWUMwXpP37MyRRrampTQgodyhP1PM=,tag:7F/ofkZUeDj04VtEETSHrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRkpJUTc1NlgvRURxdUkr
            cE5kZXdwZ1Q0cjVIaXJlWkE5NEV2Z1YxaDNvCnhXSUpUTDQ2UFJZSkJiM0ZRZEoz
            SHNhZUJDRzJSVThYeWdhd0ZJMnV4YzAKLS0tIHo1SjNKdzVsWXF3Q0UvdVA4b2Qv
            bHVZTXIrWjJaV2pyTXJBNVdESkQxamsK8ekXUuG2vkPRfbuJFetL78CWAEo8YcW+
            fqXJU8UJH056BYIA5lFUTzbmm0MazBqxMCvIcXBuZNSfkFoKICgI2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:sWRyENuJ//P5IGgfG+rHukEhelKJHPeuDFe4YVDCeTjS7WYYGlZH1dCcLXmN9Mxx0pyQwJzo9hC6iABxMucsN9VM45+9YcLlePFnEV/+W9FsfkX438IYaMHdRX48yxENDDhErBX23toXUFKdVAMGB4Abm9U4y3U4Sdx7Pkn2hDM=,iv:/v429pfFbP6vsvEhZxY5ZVav3qu1ocicFgKJGo1uO+c=,tag:KC3DA1PFRpM1BD427MItrw==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: authentik-backup-s3
    namespace: authentik
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:IubzWFVE1C5ZoA==,iv:u/ON0tZxw+dJL3TDwAHcl9pzJeglXAWzKH7avn1MsFM=,tag:TYes/KcY3a/nNqTJ5GEmcg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vybKQXm4aHGdnQ==,iv:GDd1kyCGCUjuF3/tl87wG3q5Iz1/zKRPyEnf5CDyZhY=,tag:2Y4UL32Vddr7OS5upG3jLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRkpJUTc1NlgvRURxdUkr
            cE5kZXdwZ1Q0cjVIaXJlWkE5NEV2Z1YxaDNvCnhXSUpUTDQ2UFJZSkJiM0ZRZEoz
            SHNhZUJDRzJSVThYeWdhd0ZJMnV4YzAKLS0tIHo1SjNKdzVsWXF3Q0UvdVA4b2Qv
            bHVZTXIrWjJaV2pyTXJBNVdESkQxamsK8ekXUuG2vkPRfbuJFetL78CWAEo8YcW+
            fqXJU8UJH056BYIA5lFUTzbmm0MazBqxMCvIcXBuZNSfkFoKICgI2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:sWRyENuJ//P5IGgfG+rHukEhelKJHPeuDFe4YVDCeTjS7WYYGlZH1dCcLXmN9Mxx0pyQwJzo9hC6iABxMucsN9VM45+9YcLlePFnEV/+W9FsfkX438IYaMHdRX48yxENDDhErBX23toXUFKdVAMGB4Abm9U4y3U4Sdx7Pkn2hDM=,iv:/v429pfFbP6vsvEhZxY5ZVav3qu1ocicFgKJGo1uO+c=,tag:KC3DA1PFRpM1BD427MItrw==,type:str]
    version: 3.13.1
