# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:jpID4AF9n4Ke+z2E4mY6/grXA6dQYQBjTT6e,iv:/+7lLeR2BUhZntGIIShX8sv2s/Np+WyK2VUbrs9aTGc=,tag:P9DLzvb2erdj2RuE3PAgQQ==,type:str] #ENC[AES256_GCM,data:ad2dV2RM0DmKphRzV99O4VcBH5VKBxWb,iv:ZocVUzoe12P7MzlMkNNzXR+2UptDkkPxKxHRukdimng=,tag:nusBFJxNnl8fAWiQ+unclA==,type:comment]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:vEataQoIGfJmiw==,iv:fc5Q76u0YDwoqwLae3ZkwbQT+05W4IwXIXo+S9mZACY=,tag:hExyd5ZP1DqgqGhkTBfvUQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:LSN9VlzmGMeNaQ==,iv:fTqn5ziyXByaMsGN1gLBxR0NY87aPnDQ01+yknZKNoU=,tag:C/hJ0T+lPzjGNU2JFaPSRw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:U92tTCPEFakaRA==,iv:pT1U1gavAyS/JEVrcZRI9wfyLbhMfi245rmlxzQ9TsA=,tag:EgD4JEz1PQm9oIKd0hsGbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VHZ5VFh0MGxEYjVIajBV
            b1pIV3dYaTgrMWRxdk54TkQ3MDdkQUdKZGc4CnJhbFhuazlUZGoxbzJCdG5Ma3Az
            YVBUZFZUK3BTT2owYmp6UmNsMU5oU0kKLS0tIEVDeFhHRmI2ZDRVUWE3a1pQY01J
            SEFJZVpiL3dMRC9OOGNUY1pidGtxQ0UKxg4hvV6XOD2Nj712MTKXYioIOmUpfrD8
            /e9IMVetF8VCl6xpiepCZqU4bXbaGksTY/97QRWXW5MnNFiPX+zJog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:02Z"
    mac: ENC[AES256_GCM,data:XzZt9Wepm+seXPK0nYn6/CccM6I9xPcDgzeCeeX1c0fOS1CjS76JAjtY9/5UY6FYLuDH3k7vosgH2PCFrYDEnU2tZwRWGutg4lU5Pis084EUViOhRRWfi8qhP7PupbUbFzK0jfBpXAkQb78giIm2kjlpCk8ECcszLlPWUkTL3pk=,iv:NPTn0o0ImwavwLP7v91DSGXpjboOTOwFp1rX7IbonG8=,tag:+/RbvP5PNNofoEbW4DIfHA==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: authentik-backup-s3
    namespace: authentik
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:px4gCuRTyic+mA==,iv:y1pLGc+S7sdIzhoYsnHVYC6R26PU+b3rQjFOXKC45Es=,tag:8ADebNeO4oQKH2LrXteXPA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:z/MdU5s8fb6AaA==,iv:eGP7TQNsMDIoOBqvbsCL/mLMTNf+bQ8TyEn/0+2tuuo=,tag:c3fLgvhx7BDAkW6CPPkakg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VHZ5VFh0MGxEYjVIajBV
            b1pIV3dYaTgrMWRxdk54TkQ3MDdkQUdKZGc4CnJhbFhuazlUZGoxbzJCdG5Ma3Az
            YVBUZFZUK3BTT2owYmp6UmNsMU5oU0kKLS0tIEVDeFhHRmI2ZDRVUWE3a1pQY01J
            SEFJZVpiL3dMRC9OOGNUY1pidGtxQ0UKxg4hvV6XOD2Nj712MTKXYioIOmUpfrD8
            /e9IMVetF8VCl6xpiepCZqU4bXbaGksTY/97QRWXW5MnNFiPX+zJog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:02Z"
    mac: ENC[AES256_GCM,data:XzZt9Wepm+seXPK0nYn6/CccM6I9xPcDgzeCeeX1c0fOS1CjS76JAjtY9/5UY6FYLuDH3k7vosgH2PCFrYDEnU2tZwRWGutg4lU5Pis084EUViOhRRWfi8qhP7PupbUbFzK0jfBpXAkQb78giIm2kjlpCk8ECcszLlPWUkTL3pk=,iv:NPTn0o0ImwavwLP7v91DSGXpjboOTOwFp1rX7IbonG8=,tag:+/RbvP5PNNofoEbW4DIfHA==,type:str]
    version: 3.13.1
