# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:jBU2PJqYUx4jUw==,iv:CCkON5XKRLEycpOcaft8WZE9nG31wOFRNfbN5qyiizE=,tag:ZlcfmFl+L2y5uyMxEJopEQ==,type:str] #ENC[AES256_GCM,data:5HE9yeWER7B0zHKpDBThFLDUVkBV7vPXAveuuaexTxkimMfImYcSzkNM7osC3KGIsYa3L4kzG6h1p1+B,iv:JCZSjvjQVb5tePv3QUhfJ8LiSQcxgXb3/n4MGxeIbX4=,tag:ttyfGRqkJdbsvtGJuq3iLA==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cWVmY1R2QWkwOXNGQ2lD
            d1BCZEJWUm9icWptandJS1l6RGYzbENpem5FCjhLbmRSbXpZS3o0ejdsLzVwa0hI
            N0VhZUJmaXlVQnFQdWRtNUt1VE1EKzQKLS0tIDFtUUtPMExNSCtLZkUyRDVPV3Ar
            by9WWGdvUjRMa3RJdFBsbkFKSUdnNXMKmv3AcOvBu6Gy9MoXX9QTnLc8cIlUn7v/
            LFxpErvMiOQ7yV65aBlW+zhzS8B7tIHXUcf0kO8pZhtSqtQts0TO8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:zKbmWgXWAMUaOdmn4b0jPJCovgQR+H/fQqujcZVa4L1JzsdxG+a2aSX+l78WVqNkfO/E32QALXYRE0FBfWlPNsBgas37pDzpVy4a4qe7PCWkyPA38J4yMZJx7alkCQfanIcsh3WyCiylGaOqczcwSJPfkd3KaZWjh+rTKKO/ErI=,iv:kFuBVIVJyXDM203Hl2rzjIHWVyjOIUlI+7ulC/BMpv4=,tag:x9TV0SWs6yLH+cvgVjYb2Q==,type:str]
    version: 3.13.1
