# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:JAr4hLKbQQijAg==,iv:EkzYnE4i7hQJYye5upWaBDOuzJqvGQNSZ5sP+wJ8tvE=,tag:Q+TkiS2cj/PIRSkh9Sz0hg==,type:str] #ENC[AES256_GCM,data:rfynxqYjo+wGmgbLh3u6WnQCpIthoZ9XBd+PUeacz4USgOdzNo2NxwjDHvR1C0QZiA2NLVmcFlcc5Lte,iv:qbYo3mU1OfY01lygZNc8mFX2iyA7VoydHm8dFuEGQsQ=,tag:Hh0CZMfSmwu8/023SWYx6g==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VGlXMUVyemhXcjJReGNC
            Q0FzNmhsRXI2RXBhdHppd2dZU0RtbHBKdm04CjhKb2JHcWpwc3RIWFNGQk5wTGhu
            N1NlS0tNcGtqdUk2bEpMNWh2TGJ3R1EKLS0tIHV4bUs1VUgycFg1bVFTaVVsQUR5
            TnljUHlrQ1FPTStGM0hlS0ZsTEt5QlUK2jYjFWpAA6ziWLshXggfoe5ND5nYAdlK
            +FY4RIjQi1dljDwY5qC2nKPAECtciaNW/HyTGnXRBfrVUZ4hvuWYTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:vJsHvr/40BWhuayxoii4toQDfNa/0p+XWU/YWmWo4TBuDG8h4cEyJJ4AniPj4b7BS8khXjp/Rprroy/nCG2qagkNTtu6oVMLSxNeYkjFtMwWgoe0hUKtfgNU3/ZS7tPGvrWVkcYTGFlFh4cnFeTlHW3yR9iewgRgkmmmsTP2aJk=,iv:1bU06spYo0nQYDpCeN4+WeMmfPzFnGu6EB14mAt2Sd8=,tag:3PJX41ltqIS82XeHyXwr6w==,type:str]
    version: 3.13.1
