apiVersion: v1
kind: Secret
metadata:
    name: expense-db-app
    namespace: expense-tracker
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:W+0XhkOsImc=,iv:2P3RwQH8gWjGOMRtNrCkVl4vDgCy24eqFsOjsWSuA1g=,tag:/kK6SRAC5Y7sc1QUQ6xNGA==,type:str]
    password: ENC[AES256_GCM,data:+iW+OjkjBrGTEePS/P1KOIfVY8xQ1Bge2l1YPv+LLTe2s3YmiR+452suRgc=,iv:Dla+clyjhRk2cCTd8vQVGkexPAWDg6ap5oMxSbfEh2I=,tag:XaflLz+gzlWHEReUf1K2BA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ai9tZkY2cWl2ajlBOUtm
            RE5WQ01nemgyV1RqN21EL09BVzFiN2lDa1ZrCmxaMWNvUytxYUZSakowRlE5d2pO
            NVNVVitpVURyaFkzdDUrRzhKQjl4dmcKLS0tIGVNWE1DOWhEUStST0M3MkdvNWpq
            Um1TbjJWUXZqc1NhQ3JYUzFJWnp5YzQK3K8Q/rUGJ4tdzu9uYJN4gBAVS1SZADIh
            CbyWkVtUQknLjTT6DOCAtFPv91dxzDR1o+WqGry4MnccH/S9EShyfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:39:08Z"
    mac: ENC[AES256_GCM,data:zTIwvsdD8yKhweMWTUAx3eRwU80fBjdSBh71Dq9FfAPnx9F8iu65rAb5Vhk1ukdYq926uUWKJE/Mbij2qwudbfO2AW8Cb66qpjukAH2Y5xdd5mOBMXUMJe1qF0CAIWhIEYH2dVOriZwluRf9+ZtNkCa+lSjcqjQ00OHYQrdoPo4=,iv:2IpjNkvTHIC0a+1XUXsq06W8+0fvtUZaL3tnvSst6h0=,tag:tAESrOZRHeYZuRIFoilI7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: expense-tracker-secrets
    namespace: expense-tracker
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:fSzN8C6UveDU46nutJpboHY4P1jtArpmfRWAFoJLfd2FuRMWOqsDyKCQr6eq1HhlI1TilFKUbjeM6DgVtFeFkQ==,iv:wookMzzPe8oR8QoGm5YfSEp3HRXa78n4YFimNjO2NDU=,tag:+VXsr6rsgU8za8ph37t/gA==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:GnTffBqC15DqsxX4Uc549dM+IDNMIPykRyPeb+XMQE63nkffBYxX4Eybsav0oq+1BgtqdxbeOTOgkhbXf5skLTNrsIXSb5/gGa2GjfhwpGZbK1ENrO4=,iv:WUq1Sq/93eo4apCumCDlqKpoL0HbOecmaa5LRmDh94k=,tag:HfA4uTkNrHgkQTVS4aIAoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ai9tZkY2cWl2ajlBOUtm
            RE5WQ01nemgyV1RqN21EL09BVzFiN2lDa1ZrCmxaMWNvUytxYUZSakowRlE5d2pO
            NVNVVitpVURyaFkzdDUrRzhKQjl4dmcKLS0tIGVNWE1DOWhEUStST0M3MkdvNWpq
            Um1TbjJWUXZqc1NhQ3JYUzFJWnp5YzQK3K8Q/rUGJ4tdzu9uYJN4gBAVS1SZADIh
            CbyWkVtUQknLjTT6DOCAtFPv91dxzDR1o+WqGry4MnccH/S9EShyfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:39:08Z"
    mac: ENC[AES256_GCM,data:zTIwvsdD8yKhweMWTUAx3eRwU80fBjdSBh71Dq9FfAPnx9F8iu65rAb5Vhk1ukdYq926uUWKJE/Mbij2qwudbfO2AW8Cb66qpjukAH2Y5xdd5mOBMXUMJe1qF0CAIWhIEYH2dVOriZwluRf9+ZtNkCa+lSjcqjQ00OHYQrdoPo4=,iv:2IpjNkvTHIC0a+1XUXsq06W8+0fvtUZaL3tnvSst6h0=,tag:tAESrOZRHeYZuRIFoilI7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry
    namespace: expense-tracker
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:j3EWDRMmmi3x3CqfolOzJ6JWNlrYW4pZnxgg5K4tQeXyJK1lc0ve3Wy1F9SxLzfz74GG3JqqzmldmW4ivWm/+hdZg7+pQOzvVKiO9kIRfXzPxlIlFhzWY6HQRzQapQfg7dEB08xq0K0ysnxiFRwAS/tEoGM9ij5anTkjZukYVrUbekrk+0UsNL4PythropjJUMYL2gQxfX6hsviZ/Ls+xGMlGJG0bm0PAg==,iv:cXNy8ONvIUfAHoaDMr3pl2c0pnNueGg3K2IgZnnoon0=,tag:W3SnHSjwPi+Lul2Njq1lgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ai9tZkY2cWl2ajlBOUtm
            RE5WQ01nemgyV1RqN21EL09BVzFiN2lDa1ZrCmxaMWNvUytxYUZSakowRlE5d2pO
            NVNVVitpVURyaFkzdDUrRzhKQjl4dmcKLS0tIGVNWE1DOWhEUStST0M3MkdvNWpq
            Um1TbjJWUXZqc1NhQ3JYUzFJWnp5YzQK3K8Q/rUGJ4tdzu9uYJN4gBAVS1SZADIh
            CbyWkVtUQknLjTT6DOCAtFPv91dxzDR1o+WqGry4MnccH/S9EShyfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:39:08Z"
    mac: ENC[AES256_GCM,data:zTIwvsdD8yKhweMWTUAx3eRwU80fBjdSBh71Dq9FfAPnx9F8iu65rAb5Vhk1ukdYq926uUWKJE/Mbij2qwudbfO2AW8Cb66qpjukAH2Y5xdd5mOBMXUMJe1qF0CAIWhIEYH2dVOriZwluRf9+ZtNkCa+lSjcqjQ00OHYQrdoPo4=,iv:2IpjNkvTHIC0a+1XUXsq06W8+0fvtUZaL3tnvSst6h0=,tag:tAESrOZRHeYZuRIFoilI7Q==,type:str]
    version: 3.13.3
