apiVersion: v1
kind: Secret
metadata:
    name: expense-db-app
    namespace: expense-tracker
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:iET2v2w8umA=,iv:6bLNVZ5FjawW+mNpr8uf3G3CPz86xRr2TZS0BLgW2iQ=,tag:D5K3c1hBwySfSlrO5qn7XQ==,type:str]
    password: ENC[AES256_GCM,data:FOTToegD9if5XlrvaBrKUk0+HOYrZz8pWs9u2CgqYb/BBM68zrBe6tlC2qs=,iv:WiMVHdIjRomo1EjK7CuZEmwbawL/c6JXeXEMGHYJ/PE=,tag:tSf9Ks/4wxfPOiAV+Hjj+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRG5vYWlOVkdmek5oR2Jm
            VFRoOHZYZFhGSDNHaUlxWEQvbnpSVXNBMkQwCm5LakFobjJHWUZ3Z2p2L2g3Mlhq
            SW1aeXpFVzdnTUNkb01mRW9tM3ZEZ0UKLS0tIDZSUVN2dkxvL3FhY1lHaTRTb0s5
            QVVIdUZQNkYvWnF6aWxsenhDYlhlM3MKPVT6e5QKP/9UtQGWn1GPUBN3OG3TwzD4
            kkNnSCnz0jcNexhBnIpXdI91dJX4YKcjpUvacn+tglmIIT1Wuq+jEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T09:51:58Z"
    mac: ENC[AES256_GCM,data:ESWYRDTQ1m3OeCtOmYKcef8VO8l44fzI2pKO4Y8rIxhf857d5KyPdsjqNiMjFRozlAJO9z28eEA1y6AII99gnyX9Z6uu9kUViBMWE8KS6d+uFhw/Z5bmXp++4MB1T3vJPLpRT5x8MnSEWGqbRtBsP4V90MuBZjWgwvsoQlp4J7k=,iv:HbZPaleDyffEjtYvDjWEaHESdO//aiYZSfF8NrrnjWY=,tag:Seed0tbqdKl2ZZt377isFg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: expense-tracker-secrets
    namespace: expense-tracker
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:89aQt/+KdqYI5BfaCzzrlFGjkt1sOg47t/BQmwAEzoRoyz6J1nOtulXWtwRhuID3D92aCjGbfU5LBImEo5GHBw==,iv:ADNvdd+ZThTD5gbw4kPUQeigPhD8yyOJnPG8Xf9HPkg=,tag:kjPUKvilXPGWMdtHB3xEMw==,type:str]
    #ENC[AES256_GCM,data:Wwv3r472Uq9i7zUxGRUTXS4siHZNh43Ql2JtJ4mQ5vntZlTRRjSiQ+3ZXXOxSWqgUxfOcgobc1zoLmXNWEV+hg==,iv:sV0BVigww0eO0e1MTm/deua//AT821xQFU+P/LvDQJA=,tag:bPxeURxHWu280eR32Mmm3A==,type:comment]
    #ENC[AES256_GCM,data:zs9l610em79XL+BqMrCiGSp/o76rJoXhYclNKle37f2/XkZCZjS6h8IUsDLsuJrBCTST326Mi9jPcgzQExQ=,iv:vd3BRF4jtiSZ0PbpEeSJNdooKIORa4vsTBMWQSnH4Go=,tag:WtYLUNX5XzubqB06DR9kuw==,type:comment]
    #ENC[AES256_GCM,data:nkwws59xVQVmafjJW8G5blSToqrG35ur7A==,iv:NLyjs6espLv4/lafz+dk4UwvCMie8NuUZKmDvdBawp8=,tag:gESaX9Sw06loJgJGGly2Ag==,type:comment]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:mhrvdhEUE0t08LdlEPsh2Gdu6ksOR28OoZOUtIoyar+c3w==,iv:00+9SNmc6zfaNC+TtiNGuKrbsLaMMzuf1n85PtUPpxk=,tag:NS7lDSIpZDkmU4Tjn7YSiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRG5vYWlOVkdmek5oR2Jm
            VFRoOHZYZFhGSDNHaUlxWEQvbnpSVXNBMkQwCm5LakFobjJHWUZ3Z2p2L2g3Mlhq
            SW1aeXpFVzdnTUNkb01mRW9tM3ZEZ0UKLS0tIDZSUVN2dkxvL3FhY1lHaTRTb0s5
            QVVIdUZQNkYvWnF6aWxsenhDYlhlM3MKPVT6e5QKP/9UtQGWn1GPUBN3OG3TwzD4
            kkNnSCnz0jcNexhBnIpXdI91dJX4YKcjpUvacn+tglmIIT1Wuq+jEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T09:51:58Z"
    mac: ENC[AES256_GCM,data:ESWYRDTQ1m3OeCtOmYKcef8VO8l44fzI2pKO4Y8rIxhf857d5KyPdsjqNiMjFRozlAJO9z28eEA1y6AII99gnyX9Z6uu9kUViBMWE8KS6d+uFhw/Z5bmXp++4MB1T3vJPLpRT5x8MnSEWGqbRtBsP4V90MuBZjWgwvsoQlp4J7k=,iv:HbZPaleDyffEjtYvDjWEaHESdO//aiYZSfF8NrrnjWY=,tag:Seed0tbqdKl2ZZt377isFg==,type:str]
    version: 3.13.3
