apiVersion: v1
kind: Secret
metadata:
    name: expense-db-app
    namespace: expense-tracker
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dH6MnKFCTNU=,iv:A0uA13FDiVZp8mPWAPS4QvJHs1QH+E6OXd+nrEWnVnc=,tag:BtEwM6NzFhVXHj+LXA3RWQ==,type:str]
    password: ENC[AES256_GCM,data:v5gF2L81QYOw4FNmRAZovN04DF5mvtaFS2k7VHOcsGoAQBkOhIzMrSbGbbw=,iv:YgKvJzZUo9RseM3rVdReu2/h3ujLUg6zWaE0GSSPh8w=,tag:mvMep8DZ2t+Wgb5CTfAAQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dU1JY2hMdXlueVRSLzdh
            TWdLN0x4bGlqaCsvQmhIek15ZEpsSkJrc0FjCnVXZ2psUnlUOFBXTzQ5ZzNyaUZT
            Rytlbms4WnRlYVlvRlZVUUpxQnAzZkkKLS0tIFp1b0syVXFmMmNRRTNhU1QvcGc1
            cTdjbXcvUC9LdW5HQkJkdkZ1cnlGdk0KvMre/KEmSy9CK39UT8m0oT2qtZLC6cF6
            cSDkvFhH6fcuEtQdxv7c8btmXIpgvGdJaAK9f7jH8ml2tuNZUarMtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:25:57Z"
    mac: ENC[AES256_GCM,data:lmsT9h4DTmN0GKiqLflp5pSbCiu8DBpUcReiIPLy8J63/ZrKuCxPJ9ldukkvWMNRtB/Uz4xy1qXl83fR37IxAlsS89T1bCaG9TIg3pzuvLh3OVobg2ebVg6s9Plr/QIC0P7DpWxuTH35xdtDtXsKvW2DV3yLorED9zHViTZXqk4=,iv:fMF+azk/mfXRXXXd8X+cU9xjToQyDyZxe9Nf5KWtSa8=,tag:WoflT+xdsvj0lPiUpNd3ug==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: expense-tracker-secrets
    namespace: expense-tracker
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:cYz7C3tMvCocIO11bgau5penQUWjW8lgQVo3/qvDlhB1/R67eY2Zx+3uRRuJQ5Xp428oVt6Xys2AZoWC2cuvFA==,iv:rMDYjsSI3glDCAbU/G2kOQ63k0+b5qB7BJWWdS4zKyU=,tag:BoXBh+YxpxoQtKfk/2wnqw==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:k2o/XAQwT8LU6khNWSh+046qwA0DsAbBvfO3FlpxkRtw+35E/XYuiuxgUAn7zBb0uAu8uWMEa4d0SBWBoGW/fPK21cJA6O+uqrWy29KRPCMUDzgwVG0=,iv:VnhXsfYPgHraTxySWIS3dZZJC+lqa7OoBp0uAK1BnSw=,tag:J6nSj6AXDHSPamnUaoGpGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dU1JY2hMdXlueVRSLzdh
            TWdLN0x4bGlqaCsvQmhIek15ZEpsSkJrc0FjCnVXZ2psUnlUOFBXTzQ5ZzNyaUZT
            Rytlbms4WnRlYVlvRlZVUUpxQnAzZkkKLS0tIFp1b0syVXFmMmNRRTNhU1QvcGc1
            cTdjbXcvUC9LdW5HQkJkdkZ1cnlGdk0KvMre/KEmSy9CK39UT8m0oT2qtZLC6cF6
            cSDkvFhH6fcuEtQdxv7c8btmXIpgvGdJaAK9f7jH8ml2tuNZUarMtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:25:57Z"
    mac: ENC[AES256_GCM,data:lmsT9h4DTmN0GKiqLflp5pSbCiu8DBpUcReiIPLy8J63/ZrKuCxPJ9ldukkvWMNRtB/Uz4xy1qXl83fR37IxAlsS89T1bCaG9TIg3pzuvLh3OVobg2ebVg6s9Plr/QIC0P7DpWxuTH35xdtDtXsKvW2DV3yLorED9zHViTZXqk4=,iv:fMF+azk/mfXRXXXd8X+cU9xjToQyDyZxe9Nf5KWtSa8=,tag:WoflT+xdsvj0lPiUpNd3ug==,type:str]
    version: 3.13.3
