apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - ../../../base/paperless-ngx
  - pre-22015-recovery-points.yaml
patches:
  - target: { kind: Ingress, name: paperless-paperless-ngx }
    patch: |
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
      - op: replace
        path: /metadata/annotations/nginx.org~1redirect-to-https
        value: "false"
      - op: remove
        path: /spec/tls
      - op: replace
        path: /spec/rules/0/host
        value: paperless.savar.de
  - target: { kind: Deployment, name: paperless-paperless-ngx }
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: paperless-paperless-ngx
      spec:
        template:
          spec:
            containers:
              - name: paperless-paperless-ngx
                env:
                  - name: PAPERLESS_URL
                    value: https://paperless.savar.de
