apiVersion: v1
kind: Secret
metadata:
    name: cloudns-config
    namespace: external-dns
stringData:
    CLOUDNS_AUTH_ID: ENC[AES256_GCM,data:MYW4kLU=,iv:/RX0/ykCKDgIhzfmpFG1dZzVlrFAJgEnAJgoBYSJanY=,tag:0hUO2RVoZ7dGPXDWAxyqEA==,type:str]
    CLOUDNS_AUTH_ID_TYPE: ENC[AES256_GCM,data:xGWJ/lPTlnqucxs=,iv:OVD8G6hY1gkj4RCH1m2WVJc0n0BfjK40oFlDUY04d+s=,tag:LHChEdnvxLbElvcBdp/rbg==,type:str]
    CLOUDNS_AUTH_PASSWORD: ENC[AES256_GCM,data:zcYrGfIYagCoYW9X,iv:+Nso3UxvZMvowbYUV/tlivNKntjyt4H1d2KS1MqL2Jw=,tag:6pGpGvgRSmjhkfLtX6eWlg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOVkxcitid3IxK2VGckRu
            VFdDTEUwbFJzWkZhMVBLMVZ2TXRwTFZPZnd3CjQxWmJPSVdVTHVYNC9qSjA1VHZx
            K0hlbWNWTis0L3Q2Z3F1bGM5b0REVmsKLS0tIGEyNFB1dHF4UGErRXdSVWRETXpR
            WC9wVnRNNVBRYmtJOEMxNm83OEVhSjgKxcMkcDuB5mTt1xQq5q+tw05i84NI3iw0
            DXQwVxgQRnxJpv7cOkb8fcVSAJEr3I1FdXmxxEM2WqKlWMyJ0WbNvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T13:12:24Z"
    mac: ENC[AES256_GCM,data:cPR6vc8xW9q+1sJwPhDWeon1GUZyJ5iNSP5jlhSC+Ro2QgmPFaY907FLkppTe7YjLT3/ITqQtiC9oxrzDG+/uAn+tvJU4ADY+/K0EXpztKo18P/gjpLaYiw7RJsJQPdJDYr4VbZi0bcUbOBcIcr0hXMsuGpkLZ5q8sGU6RFYyjY=,iv:SYbLPeM0zAvrAn508/QaNjoCn6iE/MNr/G0YKb2ah7o=,tag:34UAgBqcERfpfheDx5qiWQ==,type:str]
    version: 3.13.1
