apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:f5keZTFk1u7S6J7eTMrY8zwNx1THKNzxbtQm6DW/Y3OTlDfV6/QhEQ==,iv:0jO7WIVP2Ybl64pXCE5EpXX60nZWPTOXsvu6NJbO/+M=,tag:f4GTA/RHLnGwrKZh1PV2Sg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDQ2NW9lRVpMNHlCWldL
            TTZBQTdFWjdTUjVJTVByM0VNcXY1UldkeEVJCjBHNjdiZVBpY3N0ckgrY01XaVNF
            U3ZwQmt5MHlpUGpRSWpIS1hVaWs4SWMKLS0tIExleHBlNzEveXRjK0lkL0hnZitl
            UmF1ME1kdHFBbmY3Uks5QmhlaSt4cDgKgjECGwU1UY/SE+UE+pjIHAOKa/BEHfw1
            YfNruBC/QfXlj6gGLcOHcFt7QaVEppM0v1v3NuMlnvVJfHM8VHjYOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T19:12:13Z"
    mac: ENC[AES256_GCM,data:JemkJDv6+HXSrgFevqgXHGF5Kh8hruMW4GHntudYMj0phnXlNymXQ0qErvExJUn0YacOEsTfj/NjVFNUS9aCtdoO/a4CvFcpiymqDoHGSg164AozxH3tfYfI1g1hNql4WquoTYvNPCQdaJChXemhjo1RBjR7rg2+JNMvP3D0AHA=,iv:4UjjDZQIfEUALLEViKl74PVqkTpbcvDH9y6vcREwxAQ=,tag:EfhLd17T73qNQ9p6ks8Pgg==,type:str]
    version: 3.13.1
