apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup
    namespace: netbird
stringData:
    setup-key: ENC[AES256_GCM,data:kTxrWHJ83KnOVBdcBt5lMJA5OApez9Z/+poOFWCvOXuXdPSO,iv:a6CtPt6qtBchow31riLahEdsuo4z0AGMsrk3yKEY7QQ=,tag:UL9ypD6nfiiwuMlaNqgxEw==,type:str]
    admin-group: ENC[AES256_GCM,data:ai//VOTU0p1l,iv:/8jf2hHslggX2dBrQbriUl6qbLugzjXOqj8btzZSEm8=,tag:/5ckQruip9TUQM0Y0aN/mg==,type:str]
    readonly-group: ENC[AES256_GCM,data:gBHp0zIHwW/XEdFT,iv:+zuKanjQxYK8DBHMZORhqPMh28VDiSPNcsaLM75/4+k=,tag:GSys80bBv8SFsxhkGDth2g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeis4WkdaUmg3Ym40MDlV
            YkxSMXpuTTZOSUNmU1ZHYnZKSC8xR0huZ1dZCm13OE96R2JkSlZzTElTRlQrK3k0
            c1RWOHIzS0owN3RjZlM4eHV2N3dOWncKLS0tIGM4aUl0SkwwWm5CeWJ3eFdNd1k5
            YWxCRmU0dVp4ODBLNFZaeS9NKzNlZXMKnDSLBv7YBKWXyUL5BR6zhXcvMe8HV0sf
            VVYH+VCHzV379I28zNf6uhodu6zNXT+THjKXDSFBq7RqI76IM6Dm6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T18:31:33Z"
    mac: ENC[AES256_GCM,data:eEqHUFxkrY4mNvb9GFE5sQFT/jvIcJbXJ+2Jre1DU1pIf94P6/PW8oy8LfrAKsfVCT/dSBrG8J7ciyWDy5fuIDrJna4tEDrnIWMIoxU8fkw1buhhsHJtDIpi/FO7ptSjlcNvo+ImB/QJpiZATdYN+ZJnRwJEJi62521NHZBl8zk=,iv:VRlJkaPfu5vUZf5kljyfgzOaPyoUk1iz+fu37druM0Q=,tag:rE4oSYppdeuYEHTlkhh0MQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:YIb/CDMD3a/PHQ==,iv:QeLOzQ4+ssswsdK/ChrxQVRZXNnTbsU9S+vlov3kOp8=,tag:dkHwkSuIoa8LGZ0RNss/iA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeis4WkdaUmg3Ym40MDlV
            YkxSMXpuTTZOSUNmU1ZHYnZKSC8xR0huZ1dZCm13OE96R2JkSlZzTElTRlQrK3k0
            c1RWOHIzS0owN3RjZlM4eHV2N3dOWncKLS0tIGM4aUl0SkwwWm5CeWJ3eFdNd1k5
            YWxCRmU0dVp4ODBLNFZaeS9NKzNlZXMKnDSLBv7YBKWXyUL5BR6zhXcvMe8HV0sf
            VVYH+VCHzV379I28zNf6uhodu6zNXT+THjKXDSFBq7RqI76IM6Dm6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T18:31:33Z"
    mac: ENC[AES256_GCM,data:eEqHUFxkrY4mNvb9GFE5sQFT/jvIcJbXJ+2Jre1DU1pIf94P6/PW8oy8LfrAKsfVCT/dSBrG8J7ciyWDy5fuIDrJna4tEDrnIWMIoxU8fkw1buhhsHJtDIpi/FO7ptSjlcNvo+ImB/QJpiZATdYN+ZJnRwJEJi62521NHZBl8zk=,iv:VRlJkaPfu5vUZf5kljyfgzOaPyoUk1iz+fu37druM0Q=,tag:rE4oSYppdeuYEHTlkhh0MQ==,type:str]
    version: 3.13.1
