apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:4DQxmXDmT0eJmcl2F1bnGO2KREEe1G/c7Vji+vZBRFZrxsqwuK5BPA==,iv:mq0TVk5+7A+4oPRxLjgj7L4CEpYZIK+2MpfCGvnrFmM=,tag:ayV0KwqOkaglY0lwBsggQw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVHk0dHZOZkNqcXBhZUsy
            dGIxazVVMGRUd1g5emhsMTI1ZXZleEdGVHpVCjNBWTgyejV0UThTd3ZBWDNtYUV0
            RG9KMXJqd1cyUG9zTW1iaWxxcmVTaDgKLS0tIDU5SnRMbVZoWDhCbFhsZ3RBdEl5
            TktKaUdvWUszZ0dKVDY5bWNhUUdwWlUKvdcuWEb9I6zcjRTU3+aRd2agZNNS677Z
            BM+/drb7Ff6w/wdvhcdrQHSPsurtKuROwKjwYD3ycb+oRyznfNY/Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUTY1SDhBWnoyMkFxbVpu
            S2lsMERrVWdGejBhT2cyaThJMnUxZDBCSG5ZCnZNcjhVekZ4RVZqNy9KT215Z1Ax
            ZmJMazk0SHRaaWdpOTZTZktSMk4wdlUKLS0tIHVJd0g1dkFTRlRKQ0pVTTd1TXRE
            NithcUNGTWtJR1pvN0dFTllncVJBOGcKZ+iQzIP8SfqSAL5r7VYdffHK2bn3Aszd
            fWR5/+eE/SQAWuQATZrg5UqnEzTfmdS3xcoBBepa0nME3ARf0MQFdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T21:33:24Z"
    mac: ENC[AES256_GCM,data:w5appQfqWJurern+GPbC8obEH4TlbEw3dU8CI+yVKDNDaGrDURLq7fTvjDvok+XfV/KcDM/NcB4DFiCKXfbkq7YoHTsaQM4YclP+w35Xm7S8zH1YQ1Aawgcuvz1HXayE7qUqPCXJQMO8C70EUYasSM8T2NPkAojOxO6FFkutVic=,iv:vAYfOJ4cFm89Q0vPgDTOSmzRN4YgQjJcFbQh5FAadT8=,tag:YyooRRX/FtY//kXawd3TWA==,type:str]
    version: 3.13.3
