apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kimai
resources:
  - ../../../base/kimai
patches:
  - target: { kind: Ingress, name: kimai }
    patch: |
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
      - op: replace
        path: /metadata/annotations/nginx.org~1redirect-to-https
        value: "false"
      - op: remove
        path: /spec/tls
      - op: replace
        path: /spec/rules/0/host
        value: kimai.savar.de
  - target: { kind: Deployment, name: kimai }
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: kimai.savar.de|kimai.jit.services|localhost|127.0.0.1|kimai|nginx|traefik
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders/0/value
        value: kimai.savar.de
