# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-app
  namespace: forgejo
type: kubernetes.io/basic-auth
stringData:
  username: forgejo
  password: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-admin
  namespace: forgejo
type: Opaque
stringData:
  username: forgejo_admin
  password: REPLACE_ME
  email: admin@jit.services # CHANGE ME
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-backup-s3
  namespace: forgejo
type: Opaque
stringData:
  ACCESS_KEY_ID: REPLACE_ME
  SECRET_ACCESS_KEY: REPLACE_ME
