# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-app
    namespace: forgejo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LYGxlu86Zw==,iv:OCtqAUaWp19kwd7yQBPjqmTPxlpClASAbtnT4BO9vv0=,tag:hDubMniT2CpYldf5huF3fA==,type:str]
    password: ENC[AES256_GCM,data:KWFS9T0+2IhlJw==,iv:6oeSWqufpYTj8EyHOBt1FgZZ7yHXozGmVB5w6T0GDcw=,tag:0s0HMu9KvChOVvxLaDyWaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlJlWE16dmUwbitPYllj
            Z2pTbWpkY3BIU0NyRFF2QnBEV1ZqOEh0R1FVCkpBOWxML2VhSzhtSldHWEVLZXVv
            eUJDcGcwZ21lVlgvYitESFZJNnJvSnMKLS0tIEJTbmNPZ3JobW9KMm9JdHlibFFJ
            SjNZOEpYN1lrQUhoaW8rNnNDOUx4TE0K1P4hPYsXUIGSnAxhQX99lvzAvMFXU9Tz
            r8c+TOOlkNL5ydpOXk26s/FJeoVTLIi8z2z8YXV18jsaFGY2JvuA5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:2waIwITswe/1AHnk3yN7BOVd9WXYOrd++guoYu9ggoUomukmaqh8hOHUDhwWL/j/JTi6Zg1rSjq5p2nX11I2u5mWTYw6kjNMSolay2eYdzM+Ye1QZDR2BdQYldpMgCUwEmTv1W1I+nGssEFQUnEMiUDYoUhR6yZloIX0aD84lds=,iv:72VyPariPcNN0K85kAVPvqe/zuYpW9YVUobHC1dc4m4=,tag:qUcB0iSUR3XHEP5rR0uCjg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SFdMv7KcWD9nCfuzyA==,iv:FOOFIDNVK1M9XEjbRuE5so77N/sttSUA7nZ0ZYrJ4lI=,tag:fLOUkqOX20EM6ecd8vkZDg==,type:str]
    password: ENC[AES256_GCM,data:mBe/fioTsT0oLw==,iv:0mQBwMIwiKZCLyAf6xCeSipl3W7cnpP8NvWsX8WBHIk=,tag:W40+D1bZNXjTaPK7WH0A6A==,type:str]
    email: ENC[AES256_GCM,data:6UEpvqCENpxsOrq8E4J33jbk,iv:jiqowPKMv6jSqQsbiaF7AT/7ekJQ0XBAMmDszFbO5U0=,tag:INL+Nkd1X6pB2yIaAal0aQ==,type:str] #ENC[AES256_GCM,data:RZmbkN7xzow8mQ==,iv:qjeRz2Xe6wA/WlKSluA6yrBBsfJnjHz4E1MW6t0j8jw=,tag:PRiDHReSTybcgB1LSvNIeA==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlJlWE16dmUwbitPYllj
            Z2pTbWpkY3BIU0NyRFF2QnBEV1ZqOEh0R1FVCkpBOWxML2VhSzhtSldHWEVLZXVv
            eUJDcGcwZ21lVlgvYitESFZJNnJvSnMKLS0tIEJTbmNPZ3JobW9KMm9JdHlibFFJ
            SjNZOEpYN1lrQUhoaW8rNnNDOUx4TE0K1P4hPYsXUIGSnAxhQX99lvzAvMFXU9Tz
            r8c+TOOlkNL5ydpOXk26s/FJeoVTLIi8z2z8YXV18jsaFGY2JvuA5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:2waIwITswe/1AHnk3yN7BOVd9WXYOrd++guoYu9ggoUomukmaqh8hOHUDhwWL/j/JTi6Zg1rSjq5p2nX11I2u5mWTYw6kjNMSolay2eYdzM+Ye1QZDR2BdQYldpMgCUwEmTv1W1I+nGssEFQUnEMiUDYoUhR6yZloIX0aD84lds=,iv:72VyPariPcNN0K85kAVPvqe/zuYpW9YVUobHC1dc4m4=,tag:qUcB0iSUR3XHEP5rR0uCjg==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-backup-s3
    namespace: forgejo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:7FQT8KtFYy9L5w==,iv:oajGEQXxPSop2UQ7cYGI30zYZlbudIydWnH+XBjH3/A=,tag:BB2/SS+ss/3i4vndCgHOvw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iaat/diPReZbCg==,iv:x0DSpWS5DWiXZACrLFwMKw1WeKEkrL5a6qOnqnMm1B0=,tag:8kNjXVjsVMPgHDqFry1aog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlJlWE16dmUwbitPYllj
            Z2pTbWpkY3BIU0NyRFF2QnBEV1ZqOEh0R1FVCkpBOWxML2VhSzhtSldHWEVLZXVv
            eUJDcGcwZ21lVlgvYitESFZJNnJvSnMKLS0tIEJTbmNPZ3JobW9KMm9JdHlibFFJ
            SjNZOEpYN1lrQUhoaW8rNnNDOUx4TE0K1P4hPYsXUIGSnAxhQX99lvzAvMFXU9Tz
            r8c+TOOlkNL5ydpOXk26s/FJeoVTLIi8z2z8YXV18jsaFGY2JvuA5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T08:59:01Z"
    mac: ENC[AES256_GCM,data:2waIwITswe/1AHnk3yN7BOVd9WXYOrd++guoYu9ggoUomukmaqh8hOHUDhwWL/j/JTi6Zg1rSjq5p2nX11I2u5mWTYw6kjNMSolay2eYdzM+Ye1QZDR2BdQYldpMgCUwEmTv1W1I+nGssEFQUnEMiUDYoUhR6yZloIX0aD84lds=,iv:72VyPariPcNN0K85kAVPvqe/zuYpW9YVUobHC1dc4m4=,tag:qUcB0iSUR3XHEP5rR0uCjg==,type:str]
    version: 3.13.1
