# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-app
    namespace: forgejo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PWwXVP8/Bg==,iv:nSeNbxq5iwSDdwifz1qq+gtt7xmOxdSnTyBxVy7/JZ8=,tag:QEgUzHyoVGATB+08NWfDbQ==,type:str]
    password: ENC[AES256_GCM,data:JiWuyF9euRiJJg==,iv:ip4OvMO4oqnFtmzYxqXdqAFsJQq1Ct71TI8S0K7BAQk=,tag:PYyqgS83EeYh6fS6SonaeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT05BbU5sTTl2L1RpQ1h1
            MW1jQ2hIU3ppSk1odXhaa0FVK0xiTkE2TmpBClBuWUFwVW1kWlBLN21zRmZ2OWQ1
            SnpCY0NZbGJCUVVkVkJoNWpaNHh1QXMKLS0tIFRwRnowWWNJM3V0V2J3U3dPSGFI
            QjZsWHl2TG5ZaGR3SVA2MTAwaDEvekkKQ1DK/aX2wRIcAIWNUjx8vZUP2+F848xy
            SySA6vkHJvuR6K4Jf4dBGYTKmcoRDS5cQhNBcaBjYfyvHhmKaGv7cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:XoF0AoQ0SraqXCxh5VC1+ENHX4IZI7Vb241/GOin6sr/7R+kLMq0pjDMwLdhvaOR0DB5339y5g6q0WWIIw+aOzBLcqR4NQn/S/OyAiRQNItUEL226ZfZFpxv6FV/RtqV0u+HF2igt1hGwLtULBhYM9JoSslNIixwOTzqZdYlKKs=,iv:f2MVzZ9kxrWBiV6rHF0IhtovYhlt9KgSSoSj/k1w3Ms=,tag:gT0Xg7qE3d3Te2FkplOMWA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:kkM2vqXb09wN7iFNYg==,iv:sboGoSTtvhDc4XGXjAL4hcEqnNyLD+VMJ06YT6tLB2M=,tag:STAGYrhJdNe0L+/ugL64nQ==,type:str]
    password: ENC[AES256_GCM,data:XqXLfSLyX9iiaQ==,iv:x8wVEog8Dv03VcSotUIfs1VEzCEyzQpH5/cG0NiXRIc=,tag:OJs7GUJyWuI1yITyvfPbmw==,type:str]
    email: ENC[AES256_GCM,data:IjX4iVg6UCDQJ8mZuhEfqlow,iv:y/kRl9wWb9/2sJD9CeVP8nZ3wbLfvEkjSgH6ytp0L54=,tag:RJ3Jb8OcdJikddd6iwoeAg==,type:str] #ENC[AES256_GCM,data:x0/EeJB+xfqiug==,iv:LQuE661Yd8YotETQ+f8POq5GAzZ/ldHeZO72YVuBRKA=,tag:2OqMkd9Uc352/OZOWTdz1w==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT05BbU5sTTl2L1RpQ1h1
            MW1jQ2hIU3ppSk1odXhaa0FVK0xiTkE2TmpBClBuWUFwVW1kWlBLN21zRmZ2OWQ1
            SnpCY0NZbGJCUVVkVkJoNWpaNHh1QXMKLS0tIFRwRnowWWNJM3V0V2J3U3dPSGFI
            QjZsWHl2TG5ZaGR3SVA2MTAwaDEvekkKQ1DK/aX2wRIcAIWNUjx8vZUP2+F848xy
            SySA6vkHJvuR6K4Jf4dBGYTKmcoRDS5cQhNBcaBjYfyvHhmKaGv7cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:XoF0AoQ0SraqXCxh5VC1+ENHX4IZI7Vb241/GOin6sr/7R+kLMq0pjDMwLdhvaOR0DB5339y5g6q0WWIIw+aOzBLcqR4NQn/S/OyAiRQNItUEL226ZfZFpxv6FV/RtqV0u+HF2igt1hGwLtULBhYM9JoSslNIixwOTzqZdYlKKs=,iv:f2MVzZ9kxrWBiV6rHF0IhtovYhlt9KgSSoSj/k1w3Ms=,tag:gT0Xg7qE3d3Te2FkplOMWA==,type:str]
    version: 3.13.1
---
# Ceph S3 credentials for CNPG barman backups
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-backup-s3
    namespace: forgejo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:5FHJKHLs3cceUA==,iv:CdZFTfJJQ6a59rrj6SkRQhw9Rmz0d5GvNfzSw4PLzdk=,tag:Sp2VPbROAHLfPqoqtLUg7w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vmMRxXMfRPatPg==,iv:Zdys5cjE4Q9tAJKKOKjBLCjokMIY+RukjwwWT8HYYXc=,tag:GZNiNwxubIPc8qGiGV1TnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT05BbU5sTTl2L1RpQ1h1
            MW1jQ2hIU3ppSk1odXhaa0FVK0xiTkE2TmpBClBuWUFwVW1kWlBLN21zRmZ2OWQ1
            SnpCY0NZbGJCUVVkVkJoNWpaNHh1QXMKLS0tIFRwRnowWWNJM3V0V2J3U3dPSGFI
            QjZsWHl2TG5ZaGR3SVA2MTAwaDEvekkKQ1DK/aX2wRIcAIWNUjx8vZUP2+F848xy
            SySA6vkHJvuR6K4Jf4dBGYTKmcoRDS5cQhNBcaBjYfyvHhmKaGv7cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmm7srdkne4js7edykzgk39ltvamkps0y88xe4mxkx7gz7rmf3eqvvg4u5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:06:23Z"
    mac: ENC[AES256_GCM,data:XoF0AoQ0SraqXCxh5VC1+ENHX4IZI7Vb241/GOin6sr/7R+kLMq0pjDMwLdhvaOR0DB5339y5g6q0WWIIw+aOzBLcqR4NQn/S/OyAiRQNItUEL226ZfZFpxv6FV/RtqV0u+HF2igt1hGwLtULBhYM9JoSslNIixwOTzqZdYlKKs=,iv:f2MVzZ9kxrWBiV6rHF0IhtovYhlt9KgSSoSj/k1w3Ms=,tag:gT0Xg7qE3d3Te2FkplOMWA==,type:str]
    version: 3.13.1
