apiVersion: v1
kind: Secret
metadata:
    name: flurfunk-secrets
    namespace: flurfunk
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:LMMhPLw0cemwk+6xtN/AMwhn5qR6erAupbICVyUvhhZ4nPLC04/64Wjz6wbsqHEriId9nkTJVtYHweeVk5M8NQ==,iv:LaIjHBa4NbKk87pUtxdsKtly4ec1a2fli/9DCYpPxyI=,tag:ZOqfPDH1ky8+fNxWj6yiew==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:U//4DFKwsXf4TUUgPexzNXeNEB13Af1m,iv:aDihpP94dSr/x04lRvyeV620Camg1G3Yuq97clWC3k0=,tag:wXY35+6boXGWdaABeVhNrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS2wxelprbjRNVjB2b3NZ
            cnVHbWV5V3NOTUh1KzlmNjdvV0k1eHBLc0hvClcrSVlvL1lxb3E5RFU5ZzBqd1ZO
            UlNrQks5VUhIQ214Zzl5eUZhanhpRlEKLS0tIG5ra0NuZ21rSVMwMFRqWGU3TGVI
            dkNCM29yRm1MUEJLek1xMGNWbEl0WGMKwmjIuIGGMougPLMXzgOfXJJXcUhxmYaB
            PhJqPT01GBOKOPCd4rs0JSyNSBaYDJ4IIogZw5o7cLF7w7XGH+SeSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdlFoSU41M0Rzb0RRakNQ
            bUJvTloxWk9RaHR6VEFuSlpUblc4eTJPa1QwClU5WVZNUWVsd3FTNEhRM3IxS0ls
            eXl3TU45cU1hbkNNa3lPZjhQeXdGN1EKLS0tIHJFaGhDS2ViZ1dva2g0V1JLNmY5
            VnpBUXpiUjU3WW5VbUlQWTZVQVFVSWsK6A5pQduBBRRcFOUOxwGg+jPNWioL6z0G
            bzUcHhrSFC+9t9YojoCH/JClfmihONO5ggKHO5nSX7cbWNmTCqPH6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T08:57:12Z"
    mac: ENC[AES256_GCM,data:D3XTvSN4mDuN81Sp0prza/BsaX4QkGM3hTqsLRz+yNhVHgPafhyK4hf/iTMC7o2kqacm8j68lEN9lTBHoI93k1/EGcguWJik2pF/d7W8Ed/wylCf9mRK8LWmrqAWA9g0S8Q4IbkNCmES2K6MrjSaLD3XhgMusVYGHAh5vRtJ0Pg=,iv:cwPPEMqPaHOq7Tfmu5FnB0Yvp53FlDB8X1VTUQwCxhY=,tag:wJJGVtvhqiSrxbqGoDioaw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry
    namespace: flurfunk
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:y5wfEYaABcznI2hJT91ImkJ41Cde/weWRoTHUTyvLhNRH1PjmgVWCQ2FpkKzYYRQeYkr5Ev/1xOHX2p/2QcMKW1krutYySxONz0+af1lcpRXUS8DgpYujDJlaZNzCVWNN9+JIxTFf9/v01giTIS0LCPVD3lXy/nOFvRaUjmJ8HBSXchh0LrCoEQ5Cc+Dq4Q+ej8w6AMAS2NDgFOOxpnCIqCzK+kbFBcYd896sWkY1nly9Yx0J1nO8h1MHqU7sw==,iv:XuSp5P8P9V7FmBzZOsDYaSsrmBtHA/P5iz6yo4YrQO8=,tag:1a/bTem1LsVDisqcFqTQ4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS2wxelprbjRNVjB2b3NZ
            cnVHbWV5V3NOTUh1KzlmNjdvV0k1eHBLc0hvClcrSVlvL1lxb3E5RFU5ZzBqd1ZO
            UlNrQks5VUhIQ214Zzl5eUZhanhpRlEKLS0tIG5ra0NuZ21rSVMwMFRqWGU3TGVI
            dkNCM29yRm1MUEJLek1xMGNWbEl0WGMKwmjIuIGGMougPLMXzgOfXJJXcUhxmYaB
            PhJqPT01GBOKOPCd4rs0JSyNSBaYDJ4IIogZw5o7cLF7w7XGH+SeSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdlFoSU41M0Rzb0RRakNQ
            bUJvTloxWk9RaHR6VEFuSlpUblc4eTJPa1QwClU5WVZNUWVsd3FTNEhRM3IxS0ls
            eXl3TU45cU1hbkNNa3lPZjhQeXdGN1EKLS0tIHJFaGhDS2ViZ1dva2g0V1JLNmY5
            VnpBUXpiUjU3WW5VbUlQWTZVQVFVSWsK6A5pQduBBRRcFOUOxwGg+jPNWioL6z0G
            bzUcHhrSFC+9t9YojoCH/JClfmihONO5ggKHO5nSX7cbWNmTCqPH6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T08:57:12Z"
    mac: ENC[AES256_GCM,data:D3XTvSN4mDuN81Sp0prza/BsaX4QkGM3hTqsLRz+yNhVHgPafhyK4hf/iTMC7o2kqacm8j68lEN9lTBHoI93k1/EGcguWJik2pF/d7W8Ed/wylCf9mRK8LWmrqAWA9g0S8Q4IbkNCmES2K6MrjSaLD3XhgMusVYGHAh5vRtJ0Pg=,iv:cwPPEMqPaHOq7Tfmu5FnB0Yvp53FlDB8X1VTUQwCxhY=,tag:wJJGVtvhqiSrxbqGoDioaw==,type:str]
    version: 3.13.3
