apiVersion: v1
kind: Secret
metadata:
    name: flurfunk-secrets
    namespace: flurfunk
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:yEOnNYlyewB+EMQcMifhF8L3b+xr4Gv/gR17Fd1TFI7e3ZMwnw5IzfJHHNpfL1fq3+zDA6cxfXuq235PsQapyg==,iv:NlGlnFLkM9Ucadnfvh0TUDtS/9BYZrST3epNffdPpLM=,tag:0++OquWDYxvn3xLRBo/E4A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:lWnf2lEaV42IsYp9a9mr1qqVTYwn7Muv,iv:U4Dzn5hgQF4yrwouMwhbMxiUI360WhETwrwTaqdSK6w=,tag:/7+5M7jZBfWoGRFaejX53w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MlVWeXIzdk1HTkw5YlBP
            YWtzSllZMkRzY1NyZk9GQ2RzUHB5bVk3OEVZCndaRUpyTjVnU0hPWVBmT28wWHVP
            eStZOHBSRkFGU3ZYK0J4QXR3MXhYMFUKLS0tIFRCK3RNVXNiVGJQb2tMTmlyTG01
            YkdhYzVzdG13RElacTM2YWFOTmMwQWMK+eAF+JWYic9sy36IzkN8h8K0QigXMczb
            7kePOqqlhmhLyvms0wBQ2JtPm/vIPMIJMNpTxmb002k1KQD8f2W/gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T06:49:07Z"
    mac: ENC[AES256_GCM,data:5aAen139Rl07jNLmNBZFl3VJHbZdzKDQUA31nY6ad8Um6/StHASSGdJBSTr58RX+d0XpML27VUDAejTPnGwbagj3FUwp705aosp0OqR0aCUZNpvGPRm086nuTrAeMPUEobh8Y642kDHOKHZUhOEf5KVnr5+5aiAuugHmoodiH6g=,iv:NX4aCXY65fPaSC6xVAMuXefK31tE7UEE5QLtbM6C6W4=,tag:/4hVw5b/AiqyCOwdWF/S/g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry
    namespace: flurfunk
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:XizHGcoAnpsMst+cK9gxaixmK0m4bdwaSYaVXmCM/1PW9LBrBjWT/6kKwFUr+T+fmBJcfa96PFEfTwj6V3hOK1AVxKeSWkvKGkcdkMXuCxenvkSViO7+t5O9XQ96PFR/a1Gyl5vEDSWlWYrhXaLeTsAuqXwYDLoAQDM7AF9WtslFzBY6PiKoiovAsWWV+ao5ORnixMEvQ7114TuSQwSS0jnAuJ2Lr+ykaW/wMFNSkJJGTPq7Rui7oBKS9+V1Sg==,iv:G0KI/vA6dS4OJGo/ZrNdf6DH2Y365UcZkAOc16T1uU0=,tag:JScnXyFvMwJ8HT9cSyIlJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MlVWeXIzdk1HTkw5YlBP
            YWtzSllZMkRzY1NyZk9GQ2RzUHB5bVk3OEVZCndaRUpyTjVnU0hPWVBmT28wWHVP
            eStZOHBSRkFGU3ZYK0J4QXR3MXhYMFUKLS0tIFRCK3RNVXNiVGJQb2tMTmlyTG01
            YkdhYzVzdG13RElacTM2YWFOTmMwQWMK+eAF+JWYic9sy36IzkN8h8K0QigXMczb
            7kePOqqlhmhLyvms0wBQ2JtPm/vIPMIJMNpTxmb002k1KQD8f2W/gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T06:49:07Z"
    mac: ENC[AES256_GCM,data:5aAen139Rl07jNLmNBZFl3VJHbZdzKDQUA31nY6ad8Um6/StHASSGdJBSTr58RX+d0XpML27VUDAejTPnGwbagj3FUwp705aosp0OqR0aCUZNpvGPRm086nuTrAeMPUEobh8Y642kDHOKHZUhOEf5KVnr5+5aiAuugHmoodiH6g=,iv:NX4aCXY65fPaSC6xVAMuXefK31tE7UEE5QLtbM6C6W4=,tag:/4hVw5b/AiqyCOwdWF/S/g==,type:str]
    version: 3.13.3
