apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: crowdsec-pg
  namespace: crowdsec
spec:
  schedule: "0 10 2 * * *" # 6-field (CNPG = Sekunden zuerst): taeglich 02:10, versetzt zu den uebrigen
  backupOwnerReference: self
  cluster:
    name: crowdsec-pg
