apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-lapi-secrets
    namespace: crowdsec
stringData:
    csLapiSecret: ENC[AES256_GCM,data:zqdthlk/Tsx07J6GbZo3D+kPNrabiIy+UIMeio9lhlLEOSXdsSMP78ymcWtuNu9c1DYmzUUl7nUHMj5k/LajDQ==,iv:j3UpbPfmL2SvKkk69drKim6KfRmqH5wE0tTSrhyjvvI=,tag:CPYaXeUHr6QyEWuJVrb2WA==,type:str]
    registrationToken: ENC[AES256_GCM,data:ffnMDSsyp0Vx+f9xMejYXUq0AdyaOgWd0l3UwfLrpwNq83dY9C+UzeeATFQr5EYb,iv:w0WWwMhdGzvDfVluUL+YsP1sIS7NURn5pyXZtqCjvD4=,tag:tofp7tnDHcxycZReLjcC8A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZERVZXdKMXdrR0NCaGlx
            Q08wTU1jUkVsNFdLdDlLaWdPMUFMTHhhUWh3CnRwOU05Tzk2OTNrVEhSU08xK1JR
            YlRFZ0d0UmE2cDJNZHlac1R3TXdKc1kKLS0tIGZTK29LWWtITExMS09wNzdRUDZJ
            bWtka28wNnZtK3hEdVlsVG5IalBnTVUKFxFcqYTMGTE1wHZ1HzKRBP6h+Da2Uuk4
            SfDeDloM1Wq/lc+9ClV5Ojcc/nyRre/aw9YBRASlBB1m99172v9RMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T14:51:56Z"
    mac: ENC[AES256_GCM,data:OXpLl90TKUImh2tXD2w8gJLQKc9xNy36cJGp4vLUbal/40TDr7Fc4QjaAt3Ma5XSwMbrxSBbGeYQTuhdlYvmijA21ei/wZg0W0zFTFQoqYJAEVDIrz2wdXYu61UdI7w+c+LBdun078ZAD/l/xLSZcy/mvbZeSt7KiIx603i1aec=,iv:+Srpo8FXNfxJoSvRM9pYmkyRo0MmBHBJcduLvAxhxeI=,tag:6W04BEOxsoFNFfIWXh1vfQ==,type:str]
    version: 3.13.3
