apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-lapi-secrets
    namespace: crowdsec
stringData:
    csLapiSecret: ENC[AES256_GCM,data:zqdthlk/Tsx07J6GbZo3D+kPNrabiIy+UIMeio9lhlLEOSXdsSMP78ymcWtuNu9c1DYmzUUl7nUHMj5k/LajDQ==,iv:j3UpbPfmL2SvKkk69drKim6KfRmqH5wE0tTSrhyjvvI=,tag:CPYaXeUHr6QyEWuJVrb2WA==,type:str]
    registrationToken: ENC[AES256_GCM,data:ffnMDSsyp0Vx+f9xMejYXUq0AdyaOgWd0l3UwfLrpwNq83dY9C+UzeeATFQr5EYb,iv:w0WWwMhdGzvDfVluUL+YsP1sIS7NURn5pyXZtqCjvD4=,tag:tofp7tnDHcxycZReLjcC8A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTnNDQUxhajJMYUxRNW1N
            TjlnVmdMWFZ4c3p0VStpRVRXaEkvYThUYVdNCkpoSUVyc3BxdlpqdWc1Wmg5L2pO
            Vks2N1E1bU8ySkZjV1NXd1BWWnBsRkkKLS0tIHFDNGFURGF3ZXBBNUJvcGFlNDdM
            ajh5ZXJoMlpML2xHVEpLd29zZFJOS3MKcdBtvDCEerEkBObjUpnfp4vkxTPKG4q8
            Y3YIVo6R8KYOlIM0DzDycCzERXTqDk+uMPISS8lyIzqmpGnA6fSkmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQVIxVHFNZlg3SWxKVHNu
            OW1zVnZGeG9ISXFCR21mV3p5Y09zY1Z1dDF3CnV0dGQ5YStFOWw4VUx4ZnpGQ2pP
            SDkwRW9jTUZQU1pTZ1lzb3Zwa0NMTzQKLS0tIGpTSnpaWjkrcU42QzV4bFpLK0I1
            cXFMRHhKOW9JUmhRcC9Rb0NyVWVVbUkK8Gm0gSxaTkgvNoocbfNt1FYa+5LHpC6a
            qZnLv8vacvIPvJFlwOywhP9ltvNKUo9VauVUa1nJYvntWXF2CVlbuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T14:51:56Z"
    mac: ENC[AES256_GCM,data:OXpLl90TKUImh2tXD2w8gJLQKc9xNy36cJGp4vLUbal/40TDr7Fc4QjaAt3Ma5XSwMbrxSBbGeYQTuhdlYvmijA21ei/wZg0W0zFTFQoqYJAEVDIrz2wdXYu61UdI7w+c+LBdun078ZAD/l/xLSZcy/mvbZeSt7KiIx603i1aec=,iv:+Srpo8FXNfxJoSvRM9pYmkyRo0MmBHBJcduLvAxhxeI=,tag:6W04BEOxsoFNFfIWXh1vfQ==,type:str]
    version: 3.13.3
