apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-db-app
    namespace: crowdsec
stringData:
    username: ENC[AES256_GCM,data:7huZOUGxsao=,iv:wGMvv5XK+How/vKzHHwAxunFCBtj2fvQxtyesaWQdIo=,tag:0ST+gm56oIQ3tIox3AXcKA==,type:str]
    password: ENC[AES256_GCM,data:GbNNYwIH0Yc52jEZLC8sAI6Q9jsmU0dFDCU6G/k0Xjg=,iv:ZNMOoD3qSE0B3S7Y3vDCdxuASmi/x3P+b9u6tySXwqE=,tag:4P3EejSTC5/XOxCCQN5j7w==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdkF4eS9YWFRESEhEajh6
            Nkt6OHNCcUtPaXJsaVFiUUJNSnh2NGFCVlF3Ckl3U211SVhNT2QvZ0c0bnBRTW9Q
            VFY5ZzVWMUtKcVB1aXVES2tidjROT2cKLS0tIDQzZ3dzZGw4QWVLTlBWdDNZVGQr
            M2hHVVBJMjBwclJIRDdFSng3d3M1Y0UK2cRrSBBFwDHl80nMFtIsKbzVdNdjanWn
            sg/n6sv9AaPa+MWXlDKkVCn/LZfgtuyYG3+gadxUH3diygkeTwJpHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T09:33:16Z"
    mac: ENC[AES256_GCM,data:5vSsjvYhvkMVGDD7fOzaaS7D43tuBpBf52AjyRNnALlgC3XYDKsfm49bhFOo/CoqS0jGUe3Tf4DH8W//Y2M8+EnSNyGpdEywEvgiyhVaDd+f0IvPE0exCO2Z025TDz7UhYGzZ1aAj79JTqAj666CcSZA3GRmVRKiKsgWT3OSrN0=,iv:GaecLaU5COhMZHeQp/T2xghWL3I5RAiAhgR7LRh90Z0=,tag:DYKf6U5jN1ahNfirVWClMQ==,type:str]
    version: 3.13.1
