apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-db-app
    namespace: crowdsec
stringData:
    username: ENC[AES256_GCM,data:7huZOUGxsao=,iv:wGMvv5XK+How/vKzHHwAxunFCBtj2fvQxtyesaWQdIo=,tag:0ST+gm56oIQ3tIox3AXcKA==,type:str]
    password: ENC[AES256_GCM,data:GbNNYwIH0Yc52jEZLC8sAI6Q9jsmU0dFDCU6G/k0Xjg=,iv:ZNMOoD3qSE0B3S7Y3vDCdxuASmi/x3P+b9u6tySXwqE=,tag:4P3EejSTC5/XOxCCQN5j7w==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRG45YWJ4b2ZsQVZCUlFP
            VHZGOHgvOFFPakhGaUROMzhDQ2Y0aGlzbXc4CmJmYkZYQjF3YUlnMjJPSnFFYWND
            blR0clFHODRpRTQ1Yk1QN0hMck5rSFEKLS0tIFZrNXdCL1pyQmZCcDA0c2h1b2lC
            YURqQWVPMHNPMWRWRkV5Nkw4QmZYb1EK24zMC8MJZeaEVj+9mhwbdmsxpXI6VZaQ
            6nUCb33ZYWQoWaj52NUO81o7EzJcK28ePey65QalH3bY24Er1Ijk2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd05lN3hUbFFwNmF5NE9Y
            QktuNGdwRWVxZVNWcmJDZzZ2YjI0Y3lWR25VCkZpcVRuSEYvRnRKek9DODVqV3Vl
            RlljU1lacXJqRUUzZFJWRmdlVU9EWTAKLS0tIHJha29vM28vbFJ1S3JpZlAvUzFC
            V29KRGM1dko3YkM0NlUrcTJYY2ZFWmsKmzQP3gk4ZO11kaI+1IC30610PINPWh2n
            SXo9gyo3shLYi2vuVXmDqo4nDD9mqp2HjrNFMbLwWGJHq7kze/wZFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T09:33:16Z"
    mac: ENC[AES256_GCM,data:5vSsjvYhvkMVGDD7fOzaaS7D43tuBpBf52AjyRNnALlgC3XYDKsfm49bhFOo/CoqS0jGUe3Tf4DH8W//Y2M8+EnSNyGpdEywEvgiyhVaDd+f0IvPE0exCO2Z025TDz7UhYGzZ1aAj79JTqAj666CcSZA3GRmVRKiKsgWT3OSrN0=,iv:GaecLaU5COhMZHeQp/T2xghWL3I5RAiAhgR7LRh90Z0=,tag:DYKf6U5jN1ahNfirVWClMQ==,type:str]
    version: 3.13.1
