apiVersion: v1
kind: Secret
metadata:
    name: roundcube-dev-app
    namespace: roundcube-dev
type: Opaque
stringData:
    des_key: ENC[AES256_GCM,data:jf6pc97cPfBjiZTtMupb/ms743pXVfRu,iv:kbnEruUandVgKlokTGFSI0GGpkNiscwAcK4onqBKWi8=,tag:b+fTLeUNSJNHfkkCzruaew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc2tJa0c4bTRxcS96N1hP
            aVM2b3FFQWdGdUZXNlFOK3IwYkc1V3owQ1FvClllSmNiQXlnanY1d2p3UFJKc0dz
            cEFYYzZpaDBXTGpWZGpFaVNmSXVRdjgKLS0tIDQ4RlYvMFFTeXVYRC9Iam9pUHQ0
            Y2JsaC9Ja0NIYkZ5MUhJelFuWVNhK0kKorIpoLjfiCSFmm8hMcjKFCTxwaepQTJ7
            xrS8bUhxfECmPh+pcE3+4u4VGPdHJvIojojo6MI+pXzCDeuym4esmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T07:57:11Z"
    mac: ENC[AES256_GCM,data:y732JfGg1MXNKbVyBqrMkY5qDVCsQzdvZZLN0yWe+ezmLqG79yFcOmlvuq9cqJLnbvw+PL97bgXaakowe+yfN9rfVhWOjtdYI+30G6V/+YcAhDwgibuzz7dfUose4zQpLQDKmypTk3JdshBAkV23pOGXse1DhVfxsfNtUZ+UaXs=,iv:2Nnp/B1f1W6Omz/IOtITm1uvyFrD5q79QRGZY62ePA8=,tag:WRAfgaxKMFQzaFNklMEJag==,type:str]
    version: 3.13.3
