apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kite
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Y7m2k2FSIlu2ehTs55k3tqjYpGdLn4/sDU+JB1Vrg0zuSn1sIXS7VEmIdTFZgH5GV0gYZl43z4JeQOh4iCY2jw==,iv:I8zOXQYV4JK/WJO8JW0mwAP631/h5zWnqbtWODn6nBA=,tag:EfyVylnhAxOBh5FFTM02jw==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:PoUjmJU0Rfr0bOXS92O2Xl+bbO9O3SI7tpPpcY+rGM0=,iv:efOfT6Eu/ryjX8rjim25A8G/0KFO0JXWFxfWXlO1oRs=,tag:ByLAm5FkFQkWa73fePqHDg==,type:str]
    KITE_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:/hIk9Ij7gc0AY4HWRCcmkp2opQOF3g==,iv:XEyv5znE6FP0NVx0MNebDkTSuCGNeji91y7kV+XIA+E=,tag:aisZKw5oTZzivVt0RDZQpw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Fl2M0C7xYUzC1g==,iv:5FZpz/MLPXtjk8jbZbjjyiaCvxKSSln24yM84nHbHFw=,tag:2G2KbXKfWmNK0JObL+VUuw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVU1c2xJSXlUQkFkOVJy
            dkNZZm41OUUxeWdXY05KNitwUE5JR2M2aGhRCkswZTZ6TTBVL3l2K240ZTVFYmxx
            NmNKZ3h2WFBSeEprQ3l6azl3T1V6cjQKLS0tIHM0OEZMbHEwNmZ0M041QWFvai8z
            UXlWNi9TTUV2R0R0biszOFlTSTJWM0UK1HwNMt37LSoY3/Fb8JvzPBx0wYc5q7qH
            Etqj2QJl3/bB+H3Wn0XdJLSHdicHj3tbZNRz2EMgJFAJYFu8EOY7oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTcyQW5OOThaUzBLTkE5
            R1kvTFlHWEdQeXZwQlRPOVZJZTRYbG14UmtNCnR6OW12NWJGZ1NJNjArekF4VDky
            U2hENE1MNUdyeUIxV0loYWxqOVNPeWcKLS0tIHpLdXE4VFVaVzdMY0lFbmhUUVBs
            UEJrUmFIU2Yzb1UwaWg3RHplK1Y5NXMKaWhrg2D2cC/I2zRSL8uqF05wmY7aiml+
            Uro+3fTxmIc+bJkYpwsDOnCGWvfBrACrdkJLHn6T6xpGfkeKpdYMaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hjq0mgzc2npw9lhtwr49qqrfvkxzc2ss8qu7e06fk5n84qm7xs7qrgxfxa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T18:56:17Z"
    mac: ENC[AES256_GCM,data:2Vspm952vBSt8feupdO3JYIMwdvXgKTftyMgbhM4887hau1d9/ytxo9aGD5TA7szoWSW96m1TmnvNW0cStcoxVsu71V0Qo+SdyThs9/kDTpqeQfHWsKCbdQubLe7LsMUFghQ/5sXzuiHorhR8tq0OyKnNrPynbfZo7bqOZa2Lvc=,iv:XjYcHpvbyjt65TU1mQfLRr5/CU3h2HPYFB+UAhSCWmg=,tag:BnZ7buPF+A/myL2O/UZQTQ==,type:str]
    version: 3.13.1
