apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kite
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Y7m2k2FSIlu2ehTs55k3tqjYpGdLn4/sDU+JB1Vrg0zuSn1sIXS7VEmIdTFZgH5GV0gYZl43z4JeQOh4iCY2jw==,iv:I8zOXQYV4JK/WJO8JW0mwAP631/h5zWnqbtWODn6nBA=,tag:EfyVylnhAxOBh5FFTM02jw==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:PoUjmJU0Rfr0bOXS92O2Xl+bbO9O3SI7tpPpcY+rGM0=,iv:efOfT6Eu/ryjX8rjim25A8G/0KFO0JXWFxfWXlO1oRs=,tag:ByLAm5FkFQkWa73fePqHDg==,type:str]
    KITE_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:/hIk9Ij7gc0AY4HWRCcmkp2opQOF3g==,iv:XEyv5znE6FP0NVx0MNebDkTSuCGNeji91y7kV+XIA+E=,tag:aisZKw5oTZzivVt0RDZQpw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Fl2M0C7xYUzC1g==,iv:5FZpz/MLPXtjk8jbZbjjyiaCvxKSSln24yM84nHbHFw=,tag:2G2KbXKfWmNK0JObL+VUuw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY1JBc3RISnc5b2o2Mkd5
            ZDZnMlg0NHAxcmh6OGU2MGY4RWo1R3N0bUJVCm5iZGttcWNza2szaUtwTmpkdUZz
            aXBKL0tjcXhobFFrdDlVSEp5Rllrc0kKLS0tIGxNMzhlelNLM2hiQVRqVmQzbGlr
            SWpvb2g4ZWY4VlJuYUE0L05ZNDZvNm8KvT6AIeYMokRqXVrhHJkQYV0QFgpILFsA
            Pi16QwO9nApvrs30NQbAQBkHmZxB1gvp3jkLArB5H+bP0dcvEeXRIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T18:56:17Z"
    mac: ENC[AES256_GCM,data:2Vspm952vBSt8feupdO3JYIMwdvXgKTftyMgbhM4887hau1d9/ytxo9aGD5TA7szoWSW96m1TmnvNW0cStcoxVsu71V0Qo+SdyThs9/kDTpqeQfHWsKCbdQubLe7LsMUFghQ/5sXzuiHorhR8tq0OyKnNrPynbfZo7bqOZa2Lvc=,iv:XjYcHpvbyjt65TU1mQfLRr5/CU3h2HPYFB+UAhSCWmg=,tag:BnZ7buPF+A/myL2O/UZQTQ==,type:str]
    version: 3.13.1
