# ENCRYPT BEFORE COMMIT:  sops --encrypt --in-place secret.sops.yaml
# BasicAuth für metrics.jit.services (vmsingle). "password" ist der Klartext
# fuer die Grafana-Datasource auf 192.168.23.9 (User: grafana).
apiVersion: v1
kind: Secret
metadata:
    name: vmsingle-basic-auth
    namespace: monitoring
type: nginx.org/htpasswd
stringData:
    htpasswd: ENC[AES256_GCM,data:SE6GJM+VKWRbZmkFO0YX2RHTWGH7y5GUDhKWVNngGv4hGMdZEQM46EkX3/Mz,iv:9VIQRshL2CxYMY+nLg2YTyi4xQcmYr4rzPDLwHtyK1U=,tag:QtM9JPv6r89f7PHTlKfZTg==,type:str]
    password: ENC[AES256_GCM,data:m/ovBAgD5u7vUTkeT8FnWIx48Kr9mxwC8lg+,iv:zkPvauXWMSCCQ1aQXaJFXukG7YHAYK4r2suF1j/7HkU=,tag:AKCJCKHrtN47XTIFnuFviA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SkFpUGZpMDFVejFQdXpt
            cldUZUkwbStPVDgybVJySjZDYjJEczJVd0JzCkx3eW15c0lScnQvQjFNUGdJL0U3
            akpaQmdORndEY0kwL3lkVlZUSVI3TXcKLS0tIG9vZEpQWHA5OWVadmJBTW1wVlli
            dit2Q3pwcE9STWFPRDhPRGNoQVkxK0UKDGtuyvFxXJj8i02gaAXpMJtaV2aDTd39
            5qO9RKWEppy8LxTjVX59byHTTrOh0P4vL6b7Ppfy/ITrXFtv2bf00Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17x04ga87qyu9lzcuja9k83z90veew9cez7jusul4y5xyr09xaejs9rq755
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T06:23:52Z"
    mac: ENC[AES256_GCM,data:NqeyHlPN9m0gg6dJBiXJjSn6YhtWKLOkIhMFpiKT9kuPOVmJJJK30+wKFmTGUjcLWd+ZJoG8AldfrFwwGdLWzlOvi9klQAOETGaQhzs76SF2/bh9ZLkYRr2BraMfBz/sNAdV3QNI+Zc0zVdNE2TievnP+46t1BHYxhXKKxcPzEA=,iv:ytJUeX14GICOy2t0WOIuUlQnhYigbccpT5haOC3/4p0=,tag:e3xPw2jDb71P6N19ePci4w==,type:str]
    version: 3.13.1
